import Image from './public-image';
import {WebsiteStructuredData,ProductStructuredData} from './structured-data';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {publishedProducts} from '@/lib/shop-catalogue';
import type {ShopProduct} from '@/lib/shop-model';
import {collectionLinks,collectionLabels,productCare,relatedProducts} from '@/lib/shop-discovery';
import {ShopShell} from './shop-shell';
export {ShopShell} from './shop-shell';
import {CatalogueBrowser,Gallery,ProductCard} from './catalogue-browser';
import {OrderForm} from './order-form';
import {EditorialPage,ArticleCard} from './editorial';
import {publishedContent} from '@/lib/published-content';
import type {ContentDocument} from '@/lib/content-model';
import s from './shop.module.css';
const button=(outline=false)=>`${s.button} ${outline?s.outline:''}`;
const card=(p:ShopProduct)=>({id:p.id,slug:p.slug,name:p.name,subtitle:p.subtitle,category:p.category,tier:p.tier,material:p.material,image:p.image,imageAlt:p.imageAlt,imagePosition:p.imagePosition});
export function Invitation(){return <section className={s.invitation}><span className={s.eyebrow}>A place for your idea</span><h2>Let’s make it<br/><em>meaningful.</em></h2><p>A room in mind. A memory to hold. A person to celebrate. Tell us where your piece begins.</p><div className={s.actions}><Link className={button()} href="/commission">Begin your piece ↗</Link></div></section>;}
export function Intro({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <header className={s.pageIntro}><span className={s.eyebrow}>{eyebrow}</span><h1>{title}</h1>{children&&<p>{children}</p>}</header>;}
function Home({products,articles}:{products:ShopProduct[];articles:ContentDocument[]}){const selected=products.filter(p=>p.tier==='large').slice(0,3),lead=selected.find(p=>p.slug==='river-channel')||selected[0],memory=products.find(p=>p.tier==='memory'),gift=products.find(p=>p.tier==='personal');return <><WebsiteStructuredData/>
 <section className={s.hero}><div className={s.heroImage}>{lead&&<Image src={lead.scene||lead.image} alt={lead.sceneAlt||lead.imageAlt||lead.name} fill priority sizes="100vw"/>}</div><div className={s.heroCopy}><span className={s.eyebrow}>RivyaLivingArt / Furniture, resin & personal stories</span><h1>Art for the way<br/>you <em>live.</em></h1><p>Furniture with presence. Objects with meaning. Discover a piece, then make its story your own.</p><div className={s.actions}><Link className={button()} href="/collectible-design">Explore the collection ↗</Link><Link className={button(true)} href="/process">Our approach</Link></div></div>{lead&&<div className={s.heroNote}><span>01 / {lead.name}<br/>Design visualization</span><Link href={'/pieces/'+lead.slug}>Discover the piece ↗</Link></div>}</section>
 <div className={s.strip}><span>Designed around your brief</span><span>Furniture · Memory art · Personal gifts</span><span>A conversation, then a creation</span></div>
 <section className={`${s.section} ${s.light}`}><div className={s.sectionHead}><div><span className={s.eyebrow}>The collection / Selected forms</span><h2>Objects that<br/>hold a room.</h2></div><p>A natural edge. A pool of colour. A silhouette that draws you closer. Begin with a design and explore what it could become in your space.</p><Link className={s.textLink} href="/collectible-design">View all pieces ↗</Link></div>{selected.length?<div className={s.grid}>{selected.map(p=><ProductCard key={p.id} product={card(p)}/>)}</div>:<p className={s.empty}>Published furniture designs will appear here. <Link className={s.textLink} href="/contact">Discuss your space with the atelier ↗</Link></p>}</section>
 <section className={`${s.section} ${s.editorial}`}><div className={s.editorialImage}>{lead?<Image src={lead.image} alt={lead.imageAlt||lead.name} fill sizes="(max-width:780px) 88vw, 45vw"/>:<span className={s.imageUnavailable}>Material, colour and proportion — considered for your space.</span>}</div><div className={s.editorialCopy}><span className={s.eyebrow}>Material / Movement / Meaning</span><h2>The beauty is<br/>in the <em>dialogue.</em></h2><p>Wood brings its grain. Resin brings depth, colour and light. Together, they invite a different way of looking at an everyday object.</p><p>Our collection gives that conversation a starting point. Your room, your references and your preferences give it direction.</p><Link className={s.textLink} href="/materials-care#materials">Explore the material language ↗</Link></div></section>
 <section className={`${s.section} ${s.green}`}><div className={s.sectionHead}><div><span className={s.eyebrow}>Beyond the room</span><h2>Some things deserve<br/>to stay with us.</h2></div><p>For a moment you want to keep, or a person you know by heart. Explore the more personal side of RivyaLivingArt.</p></div><div className={s.journeys}><Link className={s.journey} href="/memory-art">{memory&&<Image src={memory.image} alt={memory.imageAlt||memory.name} fill sizes="(max-width:780px) 88vw, 44vw"/>}<span className={s.eyebrow}>02 / Memory art</span><h3>A moment.<br/>A lasting form.</h3><p>Flowers, keepsakes and the stories they carry. Begin a preservation conversation.</p><span className={s.textLink}>Explore memory art ↗</span></Link><Link className={s.journey} href="/personal-art">{gift&&<Image src={gift.image} alt={gift.imageAlt||gift.name} fill sizes="(max-width:780px) 88vw, 44vw"/>}<span className={s.eyebrow}>03 / Personal art & gifts</span><h3>For someone.<br/>Like no one else.</h3><p>A name, a message, a colour only they would choose. Give a piece a personal meaning.</p><span className={s.textLink}>Discover personal gifts ↗</span></Link></div></section>
 <section className={`${s.section} ${s.editorial}`}><div><span className={s.eyebrow}>From an idea to your piece</span><h2>Considered together.<br/><em>Made personal.</em></h2></div><div className={s.numbered}>{[['01','Find your starting point','Explore furniture, preservation pieces and gifts. Choose the design that speaks to you.'],['02','Make it your own','Share dimensions, colour choices and references through its customization form.'],['03','Send your saved order details','Your product choices and references are saved in the database and Studio. Then open the prepared order message in WhatsApp and tap Send yourself.']].map(([n,h,p])=><div key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></section><section className={`${s.section} ${s.light}`}><div className={s.sectionHead}><div><span className={s.eyebrow}>The journal</span><h2>A closer look.</h2></div><Link className={s.textLink} href="/journal">All stories ↗</Link></div>{articles.length?<div className={s.grid}>{articles.slice(0,3).map(a=><ArticleCard key={a.id} article={a}/>)}</div>:<p className={s.empty}>Explore our approach to materials and preparing your brief in <Link className={s.textLink} href="/process">the process guide</Link>.</p>}</section><Invitation/>
 </>;}
export async function ShopSite({route}:{route:string}){
 const needsCatalogue=route==='/'||route.startsWith('/pieces/')||['/collectible-design','/memory-art','/personal-art','/search','/commission','/preserve','/personalize','/portfolio'].includes(route);
 const products=needsCatalogue?await publishedProducts():[];let content:React.ReactNode;
 if(route==='/')content=<Home products={products} articles={(await publishedContent()).filter(a=>a.kind==='article')}/>;
 else if(route.startsWith('/pieces/')){
  const slug=route.split('/')[2];const product=products.find(p=>p.slug===slug);if(!product)notFound();
  content=route.endsWith('/customize')?<><Intro eyebrow="A brief for your piece" title="Make it yours.">Your choices. Your references. One conversation with the studio.</Intro><OrderForm key={product.id} product={product}/></>:<><ProductStructuredData product={product}/><div className={s.pageIntro}><nav className={s.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={collectionLinks[product.tier]}>{collectionLabels[product.tier]}</Link><span>/ {product.name}</span></nav></div><section className={s.detail}><div><Gallery key={product.id+':'+product.revision} product={product}/></div><div className={s.detailCopy}><span className={s.eyebrow}>{product.category} / {product.id}</span><h1>{product.name}</h1><p>{product.subtitle}</p><p>{product.story}</p><p>Price on request · Customized to your brief</p><div className={s.actions}><Link className={button()} href={`/pieces/${product.slug}/customize`}>Customize this piece ↗</Link></div><p className={s.help}>Complete this piece’s customization form. Its saved order summary is prepared for you to send to the atelier on WhatsApp.</p><dl className={s.specifications}>{product.dimensions&&<><dt>Design dimensions</dt><dd>{product.dimensions}</dd></>}{product.material&&<><dt>Material direction</dt><dd>{product.material}</dd></>}</dl><p className={s.help}>The displayed design is a starting point. Confirm the final specification and care guidance with the atelier.</p><details><summary>What can I personalize?</summary><p>{product.fields.map(f=>f.label).join(' · ')}. All selections are reviewed for feasibility with the studio.</p></details><details><summary>Materials & final appearance</summary><p>Images communicate the design direction. Final materials, colour, dimensions and finish are agreed with you before confirmation.</p></details><details><summary>Living with your piece</summary><p>{productCare(product)}</p><Link className={s.textLink} href="/materials-care#care">Materials & care ↗</Link></details><details><summary>Ordering & delivery</summary><p>Your customization details and references are saved in the database and Studio before WhatsApp opens. Tap Send there to share the prepared order message. Submitting a brief does not confirm an order.</p></details></div></section><section className={`${s.section} ${s.light}`}><div className={s.sectionHead}><h2>In the same spirit.</h2><Link className={s.textLink} href={collectionLinks[product.tier]}>Explore {collectionLabels[product.tier].toLowerCase()} ↗</Link></div>{!relatedProducts(products,product).length&&<p className={s.empty}>Explore the collection or contact the atelier about another direction.</p>}<div className={s.grid}>{relatedProducts(products,product).map(p=><ProductCard key={p.id} product={card(p)}/>)}</div></section></>;
 }else if(['/collectible-design','/memory-art','/personal-art','/search','/commission','/preserve','/personalize','/portfolio'].includes(route)){
  const tier=['/memory-art','/preserve'].includes(route)?'memory':['/personal-art','/personalize'].includes(route)?'personal':['/collectible-design','/portfolio'].includes(route)?'large':null;
  const choosing=['/commission','/preserve','/personalize'].includes(route);
  const feature=products.find(p=>p.tier===tier);
  const title=choosing?'Choose your starting point.':tier==='memory'?'For what stays with you.':tier==='personal'?'A little more personal.':route==='/search'?'Find your piece.':'Presence, in every form.';
  content=<><Intro eyebrow={choosing?'Begin a piece':route==='/search'?'All collections':tier==='memory'?'Memory art':tier==='personal'?'Personal art & gifts':'Furniture & spatial art'} title={title}>{choosing?'Select a piece to open its own customization form. Your saved details and references become the order message you send to the atelier.':route==='/search'?'Search by name, form, reference or material across the published collection.':tier==='memory'?'Explore forms for flowers, keepsakes and the memories they hold. Each inquiry starts a careful conversation about what can be preserved.':tier==='personal'?'Thoughtful forms for names, messages and individual colour choices. Find a gift with room for your own meaning.':'Discover furniture and sculptural objects shaped by the meeting of timber, resin and light. Make their proportions and colour direction your own.'}</Intro>{tier&&<div className={s.collectionFeature}><div className={s.collectionFeatureImage}>{feature?<Image src={feature.scene||feature.image} alt={feature.sceneAlt||feature.imageAlt||feature.name} fill priority sizes="(max-width:780px) 90vw, 60vw"/>:<span className={s.imageUnavailable}>A starting point for your {tier==='large'?'space':tier==='memory'?'memory':'gift'}.</span>}</div><div><span className={s.eyebrow}>{tier==='large'?'01 / A place in your space':tier==='memory'?'02 / A story to keep':'03 / A personal gesture'}</span><h2>{tier==='large'?'Consider the room around it.':tier==='memory'?'Begin with what matters.':'Small details. Personal meaning.'}</h2><p>{tier==='large'?'Bring your dimensions, light and everyday use to the conversation.':tier==='memory'?'Tell us about the flowers or keepsake and its condition. Wait for our guidance before sending anything irreplaceable.':'Choose a form, then share your size, message, occasion and quantity.'}</p></div></div>}<section className={s.section} style={{paddingTop:0}}>{choosing&&<div className={s.bespokeEntry}><h2>A piece of your own.</h2><p>If your idea does not start with a catalogue design, describe its purpose, scale and material direction.</p><Link className={s.button} href="/commission/customize">Prepare a custom-piece brief ↗</Link><p className={s.help}>Prepare and review your brief here. Saving becomes available when the secure order form is ready.</p></div>}<CatalogueBrowser products={products.filter(p=>!tier||p.tier===tier).map(card)}/><p className={s.caption}>Collection images are design visualizations. Final details and quotations are agreed individually.</p></section><Invitation/></>;
 }else content=<EditorialPage route={route}/>;
 return <ShopShell>{content}</ShopShell>;
}
