import type {ContentDocument,ContentSection} from './content-model';
import type {ShopProduct} from './shop-model';

export const discoveryRoutes=['/collectible-design','/memory-art','/personal-art','/search','/commission'] as const;
export const discoveryTier=(route:string):ShopProduct['tier']|undefined=>route==='/collectible-design'?'large':route==='/memory-art'?'memory':route==='/personal-art'?'personal':undefined;
export const isDiscoveryRoute=(route:string)=>discoveryRoutes.some(r=>r===route);
const chapter=(id:string,heading:string,paragraphs:string[],extra:Partial<ContentSection>={}):ContentSection=>({id,heading,paragraphs,...extra});
const page=(route:string,title:string,eyebrow:string,description:string,sections:ContentSection[]):ContentDocument=>({id:'page:'+route.slice(1),kind:'page',route,title,eyebrow,description,sections});
export const detailedPageCandidates:ContentDocument[]=[
 page('/collectible-design','Presence, in every form.','Furniture & spatial art','Start with the room, then find a form. Explore furniture and sculptural objects and bring your dimensions, light and everyday use into the conversation.',[
  chapter('browse','Find a piece for your space.',['Browse the existing collection by form or material direction. The images are design visualizations; the individual piece’s specification and quotation are agreed with the atelier.']),
  chapter('proportion','The room is part of the brief.',['A piece has a presence beyond its outline. Think about the sightline from the doorway, the furniture around it and the space people need to move. A rough plan and a few room photographs can make your intention clearer.','Keep proposed product dimensions separate from measurements of the room. These references begin a discussion; they do not establish structural performance or installation suitability.'],{layout:'statement',checklist:['Intended use and position','Approximate size, with units','Nearby colours, finishes and light','Doorways, stairs, lifts and delivery city'],action:{label:'Prepare a project brief',href:'/architects'}}),
  chapter('material','Read the grain. Notice the colour.',['Timber brings natural variation; resin introduces colour, depth and transparency. Look at how the materials meet rather than expecting an image to define the final surface.','Bring references with a note about what matters to you. Discuss material availability, finish and everyday care before agreeing the specification.'],{layout:'split',action:{label:'Explore materials and care',href:'/materials-care'}}),
  chapter('delivery','Plan the arrival as well as the setting.',['Share known access constraints and the intended destination early. Packing, transport, installation needs and charges are discussed for the individual quotation. No standard delivery date is promised for a custom piece.'],{policyHref:'/shipping-delivery'}),
  chapter('next','Begin with a piece or a possibility.',['Use a product’s customization form when a design is close to your idea. If the starting point is a space or a different form, prepare a bespoke brief. Saving a request starts a conversation, not a production booking.'],{action:{label:'Prepare a bespoke brief',href:'/commission/customize'}})
 ]),
 page('/memory-art','For what stays with you.','Memory art','Flowers, keepsakes and the stories they carry. Begin with the material’s condition and the meaning you want the piece to hold.',[
  chapter('browse','Find a format for the memory.',['Explore the existing preservation designs. Frames, clocks and keepsake forms offer different starting points; suitability depends on your materials and their condition.']),
  chapter('prepare','Keep the original with you for now.',['Share clear photographs and explain what you would like to preserve. Tell the atelier what the materials are and their current condition. A photograph supports the conversation but cannot guarantee suitability.','Wait for the atelier’s guidance before sending anything irreplaceable. Confirm the recipient, destination and agreed transport arrangements for your particular item.'],{layout:'statement',checklist:['What the keepsake is and why it matters','Its present condition','Your preferred format or display setting','Any intended date, as a request rather than a promise'],action:{label:'Read how the inquiry works',href:'/process'}}),
  chapter('appearance','Leave room for the material’s character.',['A visualization communicates a design direction. Colour, arrangement and final appearance are discussed for your individual keepsake. No identical appearance or preservation result is guaranteed.','Bring references for the composition and explain the details you most want to retain. Agree the approach before the work is confirmed.'],{action:{label:'Read the practical questions',href:'/faq'}}),
  chapter('care','Consider where the memory will live.',['Discuss display position, sunlight, heat, moisture and cleaning with the atelier. Follow the guidance for the finished piece rather than treating every preserved material in the same way.'],{policyHref:'/materials-care#care'}),
  chapter('next','Tell us the story behind it.',['Choose a design to open its existing customization form, or begin a bespoke request. Private reference images stay with the inquiry and are not added to the public collection.'],{action:{label:'Begin a preservation brief',href:'/commission/customize'}})
 ]),
 page('/personal-art','A little more personal.','Personal art & gifts','A name, a short message or a colour with meaning. Discover existing gift designs and use their available options to make your brief specific.',[
  chapter('browse','Find the right small gesture.',['Browse gifts by their existing category and name. Product pages show the current price basis and supported customization choices; no new option or quantity is implied by this guide.']),
  chapter('personalize','The small details deserve a second look.',['Choose the closest design, then use its form to describe your direction. An occasion can explain the intention without deciding the design for you.','Check names, initials, dates and short messages carefully. If spelling or punctuation matters, include it exactly as you want it reviewed. The final specification is agreed with the atelier.'],{layout:'statement',checklist:['The person or purpose','The exact text to discuss','Colour direction and useful references','Quantity only where the product offers it']}),
  chapter('expectations','Agree the practical details.',['A fixed or starting price applies only as stated on the current product record. Other pieces are quoted individually. Ask about the intended quantity, packaging, timing and delivery before confirming an order.','No packaging inclusion, discount or guaranteed arrival is assumed. Mention a preferred date as a request so the atelier can discuss feasibility.'],{policyHref:'/shipping-delivery'}),
  chapter('next','A thoughtful brief is a useful beginning.',['Save your choices, review the prepared message and send it yourself in WhatsApp. A saved inquiry is not a paid order or an accepted quotation.'],{action:{label:'Choose your starting point',href:'/commission'}})
 ]),
 page('/search','Find your piece.','All collections','Search the published collection by name, form, reference or material. Your filters stay in the address so you can return to the same view.',[
  chapter('browse','Explore the published pieces.',['Combine a search with a collection or category, remove one filter at a time, or clear the view. Only currently published designs appear.']),
  chapter('next','Still finding the direction?',['A room, a memory or a person can be enough to start. Describe your purpose and what is still undecided in a bespoke brief.'],{action:{label:'Prepare a bespoke brief',href:'/commission/customize'}})
 ]),
 page('/commission','Choose your starting point.','Begin a piece','Start from an existing design or describe an idea of your own. Both paths preserve your brief before you choose to send the prepared message.',[
  chapter('choice','Two ways to begin.',['Choose a catalogue piece when its form or purpose is close to your idea; its own form keeps the available choices together. Use a bespoke brief when your starting point is a space, a keepsake or a different kind of object.'],{layout:'statement',action:{label:'Prepare a bespoke brief',href:'/commission/customize'}}),
  chapter('browse','Begin with an existing design.',['Explore all three collections below. Open a piece to read its details and use its supported customization form.']),
  chapter('prepare','Bring context, not a finished specification.',['Tell us the purpose, approximate dimensions if known, intended setting and the parts of a reference that matter. For a keepsake, explain its condition and wait for guidance before sending it.'],{checklist:['Choose a design or describe the idea','Add useful preferences and private references','Review your name, phone and brief','Save, then open or copy the message and tap Send yourself']}),
  chapter('agreement','The conversation comes before confirmation.',['Saving records an inquiry. Feasibility, materials, quotation, payment arrangements and delivery require a separate agreement with the atelier. The website does not take payment or confirm a production booking.'],{policyHref:'/terms'})
 ]),
 page('/journal','A closer look.','The journal','Notes on materials, spaces and preparing a thoughtful commission. Choose a topic or search for the question on your mind.',[
  chapter('reading','A notebook for your next piece.',['These stories offer a way to observe, ask questions and prepare a brief. Product images remain design visualizations; each individual specification is agreed with the atelier.'])
 ])
];

export const detailedChapters:Record<string,ContentSection[]>={
 '/our-story':[
  chapter('point-of-view','A room, a memory, a personal gesture.',['Different pieces begin with different intentions. Furniture asks how an object belongs in a space. A keepsake begins with what someone wants to hold onto. A personal gift starts with the details that make it meaningful to its recipient.','The existing collection brings those intentions into view. Use it to explain what draws you in, while leaving room to discuss the material and practical decisions.'],{layout:'statement'}),
  chapter('material-conversation','Look closely at the meeting of materials.',['Notice the edge, the grain and the way colour changes the reading of a form. These visual relationships are useful starting points for a brief. They are not proof of a particular technique, finish or performance.','A reference is most helpful when you say what you see in it. Explain whether it is the silhouette, the balance of timber and resin or the setting that you want to discuss.'],{layout:'split',action:{label:'Read the material guide',href:'/materials-care'}}),
  chapter('practice','A specification, shaped in conversation.',['Bring the proposed use, dimensions and references into the discussion. Clarify the final appearance, materials, quotation and delivery before confirming an order.','The illustrations on this website describe a direction. They are not a record of completed client installations or a substitute for the agreed specification.'],{layout:'reverse',action:{label:'Follow the process',href:'/process'}}),
  chapter('atelier-contact','Meet the atelier through your brief.',['For an existing design, its customization form gives the conversation a useful structure. For a different idea, begin with a bespoke brief. General questions can use the current phone and email on Contact.'],{action:{label:'Contact the atelier',href:'/contact'}})
 ],
 '/process':[
  chapter('making-discussion','From design direction to material decisions.',['After discussing the brief, ask how the chosen materials and intended use affect the proposed piece. Confirm the timber or keepsake, resin colour direction, dimensions and appearance as part of that discussion.','Images of pouring or polishing on this website are illustrative. They do not establish Rivya’s equipment, fabrication method or a curing schedule. The atelier should explain the approach for your agreed specification.'],{stage:'making',layout:'split',checklist:['Confirm the design and material direction','Discuss preparation and how the materials will be arranged','Clarify finish, final checks and the care guidance needed']}),
  chapter('material-selection','Begin with the actual material.',['Ask which timber, resin colour direction or sentimental materials are proposed for your piece. A reference image is useful for explaining grain, contrast and transparency, but the available material may read differently.','Agree which variations are welcome and which details need another conversation. For flowers or keepsakes, suitability and condition should be discussed before anything irreplaceable changes hands.'],{stage:'making',action:{label:'Explore the material questions',href:'/materials-care'}}),
  chapter('preparation-arrangement','Talk through preparation and arrangement.',['If the design includes timber, ask how its condition and intended setting influence the proposal. If it includes preserved objects, discuss their position, orientation and the details that must remain visible.','Clarify what you will be asked to approve and how changes should be recorded. This is a conversation about your specification, not a published instruction for treating wood or handling sentimental originals.'],{stage:'making',layout:'statement'}),
  chapter('casting-curing','Ask what the chosen method requires.',['Where a proposed piece involves resin casting, ask how the composition and making sequence affect its appearance. A pouring illustration cannot show the full method or establish that every design follows the same steps.','Discuss when the next decision or review is expected. There is no universal curing duration promised here: material, method and the individual specification need the atelier’s explanation.'],{stage:'making'}),
  chapter('surface-finish','Read the edge, the surface and the finish.',['Explain the character you want to discuss: a quiet surface, a strong edge, more transparency or a particular balance of materials. Ask how the proposed finish relates to the intended use and everyday care.','If a sample or another approval step is needed, agree its scope and availability. A photograph cannot certify a finish, establish a tolerance or replace the final specification.'],{stage:'making',layout:'statement',action:{label:'Plan everyday care',href:'/materials-care#care'}}),
  chapter('review-checks','Make the final review clear.',['Ask what the final review will cover and how any unresolved detail will be recorded. Refer back to the agreed dimensions, material direction, appearance and responsibilities rather than a changing set of informal references.','Clarify the arrangements for reporting a concern, preparing the piece for transport and receiving its care guidance. No test certificate or performance rating is implied by the design images.'],{stage:'making',policyHref:'/terms'}),
  chapter('timing','Discuss the sequence and the timing.',['Ask which decisions are needed before work can begin and when your approval will be requested. Timing depends on the design, material availability and current capacity; share a preferred date without treating it as a guarantee.','Keep the agreed specification and inquiry reference together. Discuss changes promptly rather than assuming an edited reference will alter confirmed work.'],{stage:'customer',layout:'statement',policyHref:'/returns-cancellations'}),
  chapter('arrival-and-care','Finish the conversation with arrival and care.',['Confirm the destination, known access constraints, packing, transport and installation needs in the quotation. Keep sentimental originals with you until transfer instructions have been agreed.','Request the care instructions for the final material and finish. A completed request, a prepared WhatsApp message and a confirmed order are different stages.'],{stage:'customer',policyHref:'/shipping-delivery',action:{label:'Read materials and care',href:'/materials-care'}})
 ],
 '/materials-care':[
  chapter('material-questions','Ask about the material in your piece.',['The photographs and visualizations help describe an appearance. They cannot establish heat limits, food suitability, outdoor use or chemical resistance. Ask about any intended use that depends on a specific material property.'],{layout:'statement',checklist:['What material and finish are proposed?','What variation should I expect?','What placement and cleaning guidance applies?','Who should I contact before attempting a repair?']}),
  chapter('keepsakes','Different objects need different conversations.',['For preserved flowers or keepsakes, discuss the material’s condition and display position. For a wearable gift, ask about fittings and suitability. For a large object, include support, access and installation in the brief.','Do not apply a technique shown for one object to a different finished piece without advice. Follow the instructions supplied for your individual specification.'],{action:{label:'Ask about your piece',href:'/contact'}})
 ],
 '/architects':[
  chapter('project-checklist','Give the setting a clear brief.',['A concise package can explain the intent without sharing unnecessary client information. Label the dimensions and the part of each reference that matters, and distinguish an idea from a confirmed requirement.'],{layout:'statement',checklist:['Room purpose and intended location','Measured site dimensions versus proposed product dimensions','Plans or photographs with useful context','Material and colour direction','Delivery city and known access constraints','Preferred timing and questions to resolve'],action:{label:'Prepare a bespoke project brief',href:'/commission/customize'}}),
  chapter('scope','Make the responsibilities explicit.',['Discuss drawings, samples, support, installation, transport and final checks where they are relevant. Confirm what the atelier will provide and what needs a separate arrangement before agreeing the quotation.','This page does not promise engineering, trade pricing, installation services or a particular production capacity. Approved project examples will appear only when genuine details and permissions are available.'],{policyHref:'/terms'})
 ]
};
export function restoreDetailedChapters(document:ContentDocument):ContentDocument{
 const templates=detailedChapters[document.route]||[],missing=templates.filter(t=>!document.sections.some(s=>s.id===t.id));
 if(document.sections.length+missing.length>20)throw Error('Adding these chapters would exceed 20 sections. Your current draft has been kept.');
 return {...structuredClone(document),sections:[...structuredClone(document.sections),...missing.map(s=>({...structuredClone(s),enabled:false,sourceNote:'P4 editorial starting point, adapted from existing approved Story, Process, Materials, Architects and inquiry guidance. Review before enabling.'}))]};
}
