import {journeyExtra} from './journey-text-extra';
import {journeyEditorial} from './journey-text-editorial';
/** Presentation translations only. Never use translated values as IDs, answers or saved messages. */
export const journeyCopy:Record<string,readonly [string,string]>={
 ...journeyExtra,
 ...journeyEditorial,
 'Language':['भाषा','ભાષા'],
 'Language could not be changed. Please retry.':['भाषा नहीं बदली जा सकी। फिर से प्रयास करें।','ભાષા બદલી શકાઈ નથી. ફરી પ્રયાસ કરો.'],
 'Language guidance':['भाषा संबंधी जानकारी','ભાષા વિશે માહિતી'],
 'Interface text is available in your selected language. Editorial text without a current review, product details and saved messages remain in English.':['चुनी हुई भाषा में इंटरफ़ेस उपलब्ध है। जिन पृष्ठों के अनुवाद की वर्तमान समीक्षा नहीं हुई है, उत्पाद विवरण और सहेजे गए संदेश अंग्रेज़ी में रहते हैं।','પસંદ કરેલી ભાષામાં ઇન્ટરફેસ ઉપલબ્ધ છે. વર્તમાન સમીક્ષા વગરનું સંપાદકીય લખાણ, ઉત્પાદનની વિગતો અને સાચવેલા સંદેશા અંગ્રેજીમાં રહે છે.'],
 'Search and filters':['खोज और फ़िल्टर','શોધ અને ફિલ્ટર'],
 'Skip to results ↓':['परिणामों पर जाएँ ↓','પરિણામો પર જાઓ ↓'],
 'Your saved pieces ↗':['आपकी सहेजी हुई कृतियाँ ↗','તમારી સાચવેલી કૃતિઓ ↗'],
 'Find your piece':['अपनी कृति खोजें','તમારી કૃતિ શોધો'],
 'Name, form or material':['नाम, आकार या सामग्री','નામ, આકાર અથવા સામગ્રી'],
 'Collection':['संग्रह','સંગ્રહ'],
 'All collections':['सभी संग्रह','બધા સંગ્રહો'],
 'Category':['श्रेणी','શ્રેણી'],
 'All categories':['सभी श्रेणियाँ','બધી શ્રેણીઓ'],
 'Arrange by':['क्रम चुनें','ક્રમ પસંદ કરો'],
 'Collection order':['संग्रह का क्रम','સંગ્રહનો ક્રમ'],
 'Name A–Z':['नाम A–Z','નામ A–Z'],
 'Name Z–A':['नाम Z–A','નામ Z–A'],
 'Pieces per view':['एक बार में कृतियाँ','એક સમયે કૃતિઓ'],
 'Apply filters':['फ़िल्टर लागू करें','ફિલ્ટર લાગુ કરો'],
 'Reset':['रीसेट करें','રીસેટ કરો'],
 'Clear all filters':['सभी फ़िल्टर हटाएँ','બધા ફિલ્ટર દૂર કરો'],
 'Clear filters':['फ़िल्टर हटाएँ','ફિલ્ટર દૂર કરો'],
 'No pieces to show':['कोई कृति नहीं मिली','કોઈ કૃતિ મળી નથી'],
 'No pieces match those filters. Try a broader search or reset your choices.':['इन फ़िल्टरों से कोई कृति नहीं मिली। व्यापक खोज करें या फ़िल्टर हटाएँ।','આ ફિલ્ટરથી કોઈ કૃતિ મળી નથી. વધુ વ્યાપક શોધ કરો અથવા ફિલ્ટર દૂર કરો.'],
 'Contact the atelier ↗':['एटेलियर से संपर्क करें ↗','એટેલિયરનો સંપર્ક કરો ↗'],
 'Furniture & spatial art':['फ़र्नीचर और स्थानिक कला','ફર્નિચર અને અવકાશીય કલા'],
 'Memory art':['स्मृति कला','સ્મૃતિ કલા'],
 'Personal art & gifts':['व्यक्तिगत कला और उपहार','વ્યક્તિગત કલા અને ભેટો'],
 'Our Atelier':['हमारा एटेलियर','અમારું એટેલિયર'],
 'Process':['प्रक्रिया','પ્રક્રિયા'],
 'Journal':['जर्नल','જર્નલ'],
 'Contact':['संपर्क','સંપર્ક'],
 'How it works':['यह कैसे होता है','તે કેવી રીતે થાય છે'],
 'Your questions':['आपके प्रश्न','તમારા પ્રશ્નો'],
 'Privacy':['गोपनीयता','ગોપનીયતા'],
 'Terms':['शर्तें','શરતો'],
 'Accessibility':['सुगम्यता','સુલભતા'],
 'Delivery':['डिलीवरी','ડિલિવરી'],
 'Changes & cancellations':['बदलाव और रद्द करना','ફેરફારો અને રદ કરવું'],
 'Imprint':['व्यावसायिक जानकारी','વ્યવસાયની માહિતી'],
 'Search the journal':['जर्नल में खोजें','જર્નલમાં શોધો'],
 'Find stories':['लेख खोजें','લેખો શોધો'],
 'All topics':['सभी विषय','બધા વિષયો'],
 'From the notebook':['नोटबुक से','નોટબુકમાંથી'],
 'Show more stories ↓':['और लेख दिखाएँ ↓','વધુ લેખો બતાવો ↓'],
 'No stories match this view.':['इस खोज में कोई लेख नहीं मिला।','આ શોધમાં કોઈ લેખ મળ્યો નથી.'],
 'Try a different word or return to all topics.':['दूसरा शब्द खोजें या सभी विषय देखें।','બીજો શબ્દ શોધો અથવા બધા વિષયો જુઓ.'],
 'Clear journal filters':['जर्नल फ़िल्टर हटाएँ','જર્નલના ફિલ્ટર દૂર કરો'],
 'Read materials and care ↗':['सामग्री और देखभाल पढ़ें ↗','સામગ્રી અને સંભાળ વિશે વાંચો ↗'],
 'Your piece':['आपकी कृति','તમારી કૃતિ'],
 'Your details & references':['आपकी जानकारी और संदर्भ','તમારી વિગતો અને સંદર્ભો'],
 'Review':['समीक्षा','સમીક્ષા'],
 'Your preferences':['आपकी पसंद','તમારી પસંદગી'],
 'Your name *':['आपका नाम *','તમારું નામ *'],
 'Phone number *':['फ़ोन नंबर *','ફોન નંબર *'],
 'Email (optional)':['ईमेल (वैकल्पिक)','ઈમેલ (વૈકલ્પિક)'],
 'Notes (optional)':['नोट्स (वैकल्पिक)','નોંધો (વૈકલ્પિક)'],
 'Reference images (optional)':['संदर्भ चित्र (वैकल्पिक)','સંદર્ભ ચિત્રો (વૈકલ્પિક)'],
 'Choose a direction':['एक विकल्प चुनें','એક વિકલ્પ પસંદ કરો'],
 'Please check:':['कृपया जाँचें:','કૃપા કરીને તપાસો:'],
 'Enter your name (2–100 characters).':['अपना नाम लिखें (2–100 अक्षर)।','તમારું નામ લખો (2–100 અક્ષર).'],
 'Enter a valid phone number, including country code when outside India.':['मान्य फ़ोन नंबर लिखें; भारत के बाहर का नंबर हो तो देश कोड जोड़ें।','માન્ય ફોન નંબર લખો; ભારત બહારનો નંબર હોય તો દેશનો કોડ ઉમેરો.'],
 'Enter a valid email or leave it blank.':['मान्य ईमेल लिखें या खाली छोड़ें।','માન્ય ઈમેલ લખો અથવા ખાલી રાખો.'],
 'Keep notes within 1,200 characters.':['नोट्स 1,200 अक्षरों तक रखें।','નોંધો 1,200 અક્ષર સુધી રાખો.'],
 'Please agree to saving your order details and references.':['कृपया अनुरोध की जानकारी और संदर्भ सहेजने की सहमति दें।','કૃપા કરીને વિનંતીની વિગતો અને સંદર્ભો સાચવવાની સંમતિ આપો.'],
 'Please complete this field, or choose help where available.':['यह जानकारी भरें या उपलब्ध सहायता का विकल्प चुनें।','આ વિગતો ભરો અથવા ઉપલબ્ધ સહાયનો વિકલ્પ પસંદ કરો.'],
 'Choose an available option.':['उपलब्ध विकल्प चुनें।','ઉપલબ્ધ વિકલ્પ પસંદ કરો.'],
 'Name':['नाम','નામ'], 'Phone':['फ़ोन','ફોન'], 'Email':['ईमेल','ઈમેલ'], 'Notes':['नोट्स','નોંધો'],
 'Request':['अनुरोध','વિનંતી'], 'Piece':['कृति','કૃતિ'],
 'Private references':['निजी संदर्भ','ખાનગી સંદર્ભો'],
 'Not provided':['नहीं दिया गया','આપેલ નથી'], 'Not specified':['नहीं बताया गया','જણાવેલ નથી'], 'None':['कोई नहीं','કંઈ નહીં'],
 'Retry':['फिर प्रयास करें','ફરી પ્રયાસ કરો'], 'Remove':['हटाएँ','દૂર કરો'],
 'Saved privately':['निजी रूप से सहेजा गया','ખાનગી રીતે સાચવેલ'],
 'Processing securely…':['सुरक्षित रूप से संसाधित हो रहा है…','સુરક્ષિત રીતે પ્રક્રિયા ચાલી રહી છે…'],
 'Uploading…':['अपलोड हो रहा है…','અપલોડ થઈ રહ્યું છે…'], 'Waiting…':['प्रतीक्षा में…','રાહમાં…'],
 'Edit your piece':['कृति की पसंद बदलें','કૃતિની પસંદગી બદલો'],
 'Edit details & references':['जानकारी और संदर्भ बदलें','વિગતો અને સંદર્ભો બદલો'],
 '← Back':['← पीछे','← પાછા'],
 'Your details →':['आपकी जानकारी →','તમારી વિગતો →'],
 'Review your brief →':['अपनी जानकारी जाँचें →','તમારી વિગતો તપાસો →'],
 'Save order details →':['अनुरोध की जानकारी सहेजें →','વિનંતીની વિગતો સાચવો →'],
 'Saving inquiry…':['अनुरोध सहेजा जा रहा है…','વિનંતી સાચવાઈ રહી છે…'],
 'Retry the same save':['वही जानकारी फिर सहेजें','એ જ વિગતો ફરી સાચવો'],
 'Saving temporarily unavailable':['सहेजना अभी उपलब्ध नहीं है','હમણાં સાચવી શકાતું નથી'],
 'Reconnect form':['फ़ॉर्म फिर जोड़ें','ફોર્મ ફરી જોડો'], 'Connecting…':['जुड़ रहा है…','જોડાઈ રહ્યું છે…'],
 'Check current options':['वर्तमान विकल्प जाँचें','વર્તમાન વિકલ્પો તપાસો'], 'Checking options…':['विकल्प जाँचे जा रहे हैं…','વિકલ્પો તપાસાઈ રહ્યા છે…'],
 'Select all text':['पूरा पाठ चुनें','બધું લખાણ પસંદ કરો'],
 'Copy my unsaved brief':['बिना सहेजी जानकारी कॉपी करें','સાચવ્યા વગરની વિગતો કૉપી કરો'],
 'Copy your unsaved brief':['बिना सहेजी जानकारी कॉपी करें','સાચવ્યા વગરની વિગતો કૉપી કરો'],
 'Your secure form is ready.':['आपका सुरक्षित फ़ॉर्म तैयार है।','તમારું સુરક્ષિત ફોર્મ તૈયાર છે.'],
 'Please check the linked fields below.':['नीचे दिए गए फ़ील्ड जाँचें।','નીચે આપેલા ક્ષેત્રો તપાસો.'],
 'Please check your details.':['कृपया अपनी जानकारी जाँचें।','કૃપા કરીને તમારી વિગતો તપાસો.'],
 'Your brief is with us.':['आपकी जानकारी सहेज ली गई है।','તમારી વિગતો સાચવી લેવામાં આવી છે.'],
 'Inquiry saved ·':['अनुरोध सहेजा गया ·','વિનંતી સાચવી ·'],
 '1 · Brief saved':['1 · जानकारी सहेजी गई','1 · વિગતો સાચવી'],
 '2 · Message prepared':['2 · संदेश तैयार','2 · સંદેશ તૈયાર'],
 '2 · Message preparation':['2 · संदेश की तैयारी','2 · સંદેશની તૈયારી'],
 '3 · You choose to send':['3 · भेजना आप चुनते हैं','3 · મોકલવાનું તમે પસંદ કરો છો'],
 'Your reference identifies this request.':['आपका संदर्भ नंबर इस अनुरोध की पहचान है।','તમારો સંદર્ભ નંબર આ વિનંતીની ઓળખ છે.'],
 'Review or copy the prepared message below.':['नीचे तैयार संदेश जाँचें या कॉपी करें।','નીચે તૈયાર સંદેશ તપાસો અથવા કૉપી કરો.'],
 'Open WhatsApp and press Send yourself. Sending status is not tracked here.':['WhatsApp खोलें और स्वयं भेजें दबाएँ। यहाँ भेजने की स्थिति नहीं देखी जाती।','WhatsApp ખોલો અને જાતે મોકલો દબાવો. અહીં મોકલવાની સ્થિતિ નોંધાતી નથી.'],
 'Your saved order message':['आपका सहेजा हुआ अनुरोध संदेश','તમારો સાચવેલો વિનંતી સંદેશ'],
 'Your saved brief':['आपकी सहेजी हुई जानकारी','તમારી સાચવેલી વિગતો'],
 'Return to the collection':['संग्रह पर लौटें','સંગ્રહ પર પાછા જાઓ'],
 'Copy saved order summary':['सहेजा हुआ सारांश कॉपी करें','સાચવેલો સારાંશ કૉપી કરો'],
 '✓ Summary copied to clipboard':['✓ सारांश कॉपी हुआ','✓ સારાંશ કૉપી થયો'],
 'Open WhatsApp ↗':['WhatsApp खोलें ↗','WhatsApp ખોલો ↗'],
 'Prepare saved order message':['सहेजे अनुरोध का संदेश तैयार करें','સાચવેલી વિનંતીનો સંદેશ તૈયાર કરો'],
 'Refresh saved inquiry':['सहेजा अनुरोध फिर लोड करें','સાચવેલી વિનંતી ફરી લોડ કરો'],
 'Checking your saved inquiry…':['सहेजा अनुरोध जाँचा जा रहा है…','સાચવેલી વિનંતી તપાસાઈ રહી છે…'],
 'Complete saved summary':['पूरा सहेजा हुआ सारांश','સંપૂર્ણ સાચવેલો સારાંશ'],
 'Saved inquiry refreshed.':['सहेजा अनुरोध फिर लोड हुआ।','સાચવેલી વિનંતી ફરી લોડ થઈ.'],
 'Complete saved order summary copied.':['अनुरोध का पूरा सहेजा सारांश कॉपी हुआ।','વિનંતીનો સંપૂર્ણ સાચવેલો સારાંશ કૉપી થયો.'],
 'I have copied the complete summary and can paste it in WhatsApp.':['मैंने पूरा सारांश कॉपी कर लिया है और WhatsApp में पेस्ट कर सकता/सकती हूँ।','મેં સંપૂર્ણ સારાંશ કૉપી કર્યો છે અને WhatsAppમાં પેસ્ટ કરી શકું છું.'],
 'Clear saved pieces':['सहेजी कृतियाँ हटाएँ','સાચવેલી કૃતિઓ દૂર કરો'],
 'Explore all pieces ↗':['सभी कृतियाँ देखें ↗','બધી કૃતિઓ જુઓ ↗'],
 'No saved pieces yet.':['अभी कोई कृति सहेजी नहीं है।','હજુ કોઈ કૃતિ સાચવેલી નથી.'],
 'Save piece':['कृति सहेजें','કૃતિ સાચવો'], 'Saved':['सहेजा गया','સાચવેલ'],
 'Price on request':['कीमत के लिए पूछें','કિંમત માટે પૂછો'],
 'Your request has been saved for the atelier to review. A saved request is not a confirmed quotation or production booking. Final design, quotation and delivery need the atelier’s agreement.':['आपका अनुरोध एटेलियर की समीक्षा के लिए सहेजा गया है। यह पक्की कीमत या निर्माण की बुकिंग नहीं है। अंतिम डिज़ाइन, कीमत और डिलीवरी के लिए एटेलियर की सहमति ज़रूरी है।','તમારી વિનંતી એટેલિયરની સમીક્ષા માટે સાચવી છે. આ નક્કી કિંમત કે ઉત્પાદનનું બુકિંગ નથી. અંતિમ ડિઝાઇન, કિંમત અને ડિલિવરી માટે એટેલિયરની સંમતિ જરૂરી છે.'],
 'Final design, quotation and delivery are agreed with the atelier.':['अंतिम डिज़ाइन, कीमत और डिलीवरी एटेलियर के साथ तय होती है।','અંતિમ ડિઝાઇન, કિંમત અને ડિલિવરી એટેલિયર સાથે નક્કી થાય છે.'],
 'Check your brief before it is saved. Return to either step to make a change.':['सहेजने से पहले जानकारी जाँचें। बदलाव के लिए पिछले चरण पर जाएँ।','સાચવતા પહેલાં વિગતો તપાસો. ફેરફાર માટે અગાઉના પગલા પર જાઓ.'],
 'Privacy details (opens a new tab)':['गोपनीयता विवरण (नए टैब में)','ગોપનીયતાની વિગતો (નવા ટૅબમાં)'],
 'Your unsaved brief is kept only in this tab’s temporary memory. Copy it before closing or reloading.':['बिना सहेजी जानकारी केवल इस टैब की अस्थायी मेमोरी में रहती है। बंद करने या फिर लोड करने से पहले कॉपी करें।','સાચવ્યા વગરની વિગતો ફક્ત આ ટૅબની અસ્થાયી મેમરીમાં રહે છે. બંધ કરતા કે ફરી લોડ કરતા પહેલાં કૉપી કરો.'],
 'Fields marked * are required. Ask for help where you are unsure; preferences are requests for review.':['* वाले फ़ील्ड आवश्यक हैं। संदेह हो तो सहायता माँगें; आपकी पसंद समीक्षा के लिए अनुरोध है।','* ધરાવતા ક્ષેત્રો જરૂરી છે. શંકા હોય તો સહાય પૂછો; તમારી પસંદગી સમીક્ષા માટેની વિનંતી છે.'],
};
export function journeyText(locale:string,text:string):string{
 const row=Object.hasOwn(journeyCopy,text)?journeyCopy[text]:undefined;
 return locale==='hi'?row?.[0]||text:locale==='gu'?row?.[1]||text:text;
}
