/** Public navigation and reading controls; English keys never replace stored content. */
export const journeyEditorial:Record<string,readonly [string,string]>={
 'Find an answer':['उत्तर खोजें','જવાબ શોધો'],
 'Question groups':['प्रश्न समूह','પ્રશ્નોના સમૂહ'],
 'All questions':['सभी प्रश्न','બધા પ્રશ્નો'],
 'Useful questions':['उपयोगी प्रश्न','ઉપયોગી પ્રશ્નો'],
 'answer':['उत्तर','જવાબ'], 'answers':['उत्तर','જવાબો'],
 'Link to this answer':['इस उत्तर का लिंक','આ જવાબની લિંક'],
 'No answers match.':['कोई उत्तर नहीं मिला।','કોઈ જવાબ મળ્યો નથી.'],
 'Try another phrase or show all questions.':['दूसरे शब्द खोजें या सभी प्रश्न देखें।','બીજા શબ્દો શોધો અથવા બધા પ્રશ્નો જુઓ.'],
 'Show all questions':['सभी प्रश्न देखें','બધા પ્રશ્નો જુઓ'],
 'Journal topics':['जर्नल के विषय','જર્નલના વિષયો'],
 'The journal':['जर्नल','જર્નલ'],
 'All stories':['सभी लेख','બધા લેખો'],
 'story':['लेख','લેખ'], 'stories':['लेख','લેખો'], 'Search term':['खोज के शब्द','શોધના શબ્દો'],
 'Spaces':['स्थान','જગ્યાઓ'], 'Materials':['सामग्री','સામગ્રી'], 'Commissioning':['कृति बनवाना','કૃતિ બનાવડાવવી'],
 'min read':['मिनट पढ़ने का समय','મિનિટ વાંચન'], 'minute read':['मिनट पढ़ने का समय','મિનિટ વાંચન'],
 'Read the story':['लेख पढ़ें','લેખ વાંચો'],
 'Breadcrumb':['पृष्ठ का रास्ता','પાનાનો માર્ગ'], 'Home':['मुखपृष्ठ','મુખ્ય પાનું'],
 'Design visualization':['डिज़ाइन का दृश्य','ડિઝાઇનનું દૃશ્ય'],
 'Effective':['लागू तिथि','અમલની તારીખ'], 'Effective date not recorded':['लागू तिथि दर्ज नहीं है','અમલની તારીખ નોંધાયેલી નથી'],
 'Call the atelier':['एटेलियर को फ़ोन करें','એટેલિયરને ફોન કરો'],
 'General questions & existing inquiries':['सामान्य प्रश्न और मौजूदा अनुरोध','સામાન્ય પ્રશ્નો અને હાલની વિનંતીઓ'],
 'Location':['स्थान','સ્થળ'], 'Open the atelier map':['एटेलियर का नक्शा खोलें','એટેલિયરનો નકશો ખોલો'],
 'Product & custom-piece requests':['उत्पाद और कस्टम कृति के अनुरोध','ઉત્પાદન અને કસ્ટમ કૃતિ માટેની વિનંતીઓ'],
 'Prepare your saved order brief':['सहेजने के लिए अनुरोध तैयार करें','સાચવવા માટે વિનંતીની વિગતો તૈયાર કરો'],
 'Read common questions before you write':['लिखने से पहले सामान्य प्रश्न पढ़ें','લખતાં પહેલાં સામાન્ય પ્રશ્નો વાંચો'],
 'On this page':['इस पृष्ठ पर','આ પાનામાં'],
 'By RivyaLivingArt':['RivyaLivingArt द्वारा','RivyaLivingArt દ્વારા'],
 'Customer steps':['ग्राहक के चरण','ગ્રાહકનાં પગલાં'], 'Making steps':['निर्माण के चरण','બનાવવાનાં પગલાં'],
 'Telephone':['फ़ोन','ફોન'], 'Policies and help':['नीतियाँ और सहायता','નીતિઓ અને મદદ'],
 'Ordering terms':['ऑर्डर की शर्तें','ઓર્ડરની શરતો'],
 'Contact the atelier':['एटेलियर से संपर्क करें','એટેલિયરનો સંપર્ક કરો'],
 'Email about this page':['इस पृष्ठ के बारे में ईमेल करें','આ પાના વિશે ઈમેલ કરો'],
 'Ideas to explore.':['विचारों को देखें.','વિચારો જુઓ.'], 'Keep exploring.':['और जानें.','વધુ જાણો.'],
 'Explore furniture & spatial art':['फ़र्नीचर और स्थानिक कला देखें','ફર્નિચર અને અવકાશીય કલા જુઓ'],
 'How a piece begins':['कृति की शुरुआत कैसे होती है','કૃતિની શરૂઆત કેવી રીતે થાય છે'],
 'Begin your piece':['अपनी कृति शुरू करें','તમારી કૃતિ શરૂ કરો'],
 'Read your questions':['अपने प्रश्नों के उत्तर पढ़ें','તમારા પ્રશ્નોના જવાબ વાંચો'],
 'Explore the collection':['संग्रह देखें','સંગ્રહ જુઓ'], 'Ask about your piece':['अपनी कृति के बारे में पूछें','તમારી કૃતિ વિશે પૂછો'],
 'Prepare a project brief':['परियोजना की जानकारी तैयार करें','પ્રોજેક્ટની વિગતો તૈયાર કરો'],
 'Explore materials & care':['सामग्री और देखभाल जानें','સામગ્રી અને સંભાળ વિશે જાણો'],
 'Call or email the atelier':['एटेलियर को फ़ोन या ईमेल करें','એટેલિયરને ફોન કે ઈમેલ કરો'],
 'Return to the journal':['जर्नल पर लौटें','જર્નલ પર પાછા જાઓ'],
 'Your request and agreement':['आपका अनुरोध और सहमति','તમારી વિનંતી અને સંમતિ'],
 'Making: questions for your specification':['निर्माण: विवरण तय करने के प्रश्न','બનાવટ: વિશિષ્ટતાઓ માટેના પ્રશ્નો'],
 'Appearance':['दिखावट','દેખાવ'], 'Limitations':['सीमाएँ','મર્યાદાઓ'], 'Care':['देखभाल','સંભાળ'], 'Placement':['रखने की जगह','મૂકવાની જગ્યા'],
 'Read the related policy ↗':['संबंधित नीति पढ़ें ↗','સંબંધિત નીતિ વાંચો ↗'],
 'Browse the pieces ↓':['कृतियाँ देखें ↓','કૃતિઓ જુઓ ↓'], 'Your saved pieces':['आपकी सहेजी कृतियाँ','તમારી સાચવેલી કૃતિઓ'],
 'Collection chapters':['संग्रह के भाग','સંગ્રહના વિભાગો'], 'Explore this collection':['यह संग्रह देखें','આ સંગ્રહ જુઓ'],
 'Design visualizations. Final specifications and quotations are agreed individually.':['डिज़ाइन के दृश्य। अंतिम विवरण और कीमत प्रत्येक कृति के लिए अलग तय होते हैं।','ડિઝાઇનનાં દૃશ્યો. અંતિમ વિશિષ્ટતાઓ અને ભાવપત્રક દરેક કૃતિ માટે અલગ નક્કી થાય છે.'],
 'Product gallery. Use left and right arrow keys to change image.':['उत्पाद चित्र। चित्र बदलने के लिए बाएँ और दाएँ तीर की कुंजियाँ दबाएँ।','ઉત્પાદનનાં ચિત્રો. ચિત્ર બદલવા ડાબી અને જમણી તીર કી વાપરો.'],
 'Enlarge image of':['इसका चित्र बड़ा करें:','આનું ચિત્ર મોટું કરો:'], 'Enlarge ↗':['बड़ा करें ↗','મોટું કરો ↗'],
 'Previous image':['पिछला चित्र','અગાઉનું ચિત્ર'], 'Next image':['अगला चित्र','આગળનું ચિત્ર'],
 'Choose a product image':['उत्पाद का चित्र चुनें','ઉત્પાદનનું ચિત્ર પસંદ કરો'],
 'View image':['चित्र देखें','ચિત્ર જુઓ'], 'of':['का','નું'],
 'Images unavailable':['चित्र उपलब्ध नहीं हैं','ચિત્રો ઉપલબ્ધ નથી'],
 'The written design details remain below.':['डिज़ाइन का लिखित विवरण नीचे है।','ડિઝાઇનની લેખિત વિગતો નીચે છે.'],
 'final materials, proportions and colour are agreed with you.':['अंतिम सामग्री, अनुपात और रंग आपके साथ तय होते हैं।','અંતિમ સામગ્રી, પ્રમાણ અને રંગ તમારી સાથે નક્કી થાય છે.'],
 'Enlarged product gallery':['उत्पाद के बड़े चित्र','ઉત્પાદનનાં મોટાં ચિત્રો'], '← Previous':['← पिछला','← અગાઉનું'], 'Next →':['अगला →','આગળનું →'],
 'Image unavailable':['चित्र उपलब्ध नहीं है','ચિત્ર ઉપલબ્ધ નથી'],
 'Skip to main content':['मुख्य सामग्री पर जाएँ','મુખ્ય સામગ્રી પર જાઓ'],
 'Main navigation':['मुख्य नेविगेशन','મુખ્ય નેવિગેશન'],
 'RivyaLivingArt home':['RivyaLivingArt मुखपृष्ठ','RivyaLivingArt મુખ્ય પાનું'],
 'Mobile navigation':['मोबाइल नेविगेशन','મોબાઇલ નેવિગેશન'],
 'Navigation without JavaScript':['JavaScript के बिना नेविगेशन','JavaScript વગરનું નેવિગેશન'],
 'Objects for the spaces we inhabit. Art for the stories we keep.':['हमारे रहने की जगहों के लिए वस्तुएँ। हमारी सँजोई कहानियों के लिए कला।','આપણે વસીએ તે જગ્યાઓ માટે વસ્તુઓ. આપણે સાચવીએ તે વાર્તાઓ માટે કલા.'],
 'Show all categories':['सभी श्रेणियाँ दिखाएँ','બધી શ્રેણીઓ બતાવો'],
 'Discover the piece':['कृति को जानें','કૃતિ વિશે જાણો'],
 'A space for your next piece.':['आपकी अगली कृति के लिए एक जगह।','તમારી આગામી કૃતિ માટે એક જગ્યા.'],
 'Materials & care':['सामग्री और देखभाल','સામગ્રી અને સંભાળ'],
 'Filter the collection':['संग्रह फ़िल्टर करें','સંગ્રહ ફિલ્ટર કરો'], 'Applied filters':['लागू फ़िल्टर','લાગુ ફિલ્ટર'],
 'Updated customization form':['बदला हुआ कस्टमाइज़ेशन फ़ॉर्म','સુધારેલું કસ્ટમાઇઝેશન ફોર્મ'],
 'Saved request status':['सहेजे अनुरोध की स्थिति','સાચવેલી વિનંતીની સ્થિતિ'],
 'Try again':['फिर प्रयास करें','ફરી પ્રયાસ કરો'], 'Explore the collection ↗':['संग्रह देखें ↗','સંગ્રહ જુઓ ↗'],
 'Retry image':['चित्र फिर लोड करें','ચિત્ર ફરી લોડ કરો'],
 'Close dialog':['संवाद बंद करें','સંવાદ બંધ કરો'], 'Close navigation':['नेविगेशन बंद करें','નેવિગેશન બંધ કરો'], 'Close':['बंद करें','બંધ કરો'],
 'Opening this page.':['पृष्ठ खुल रहा है।','પાનું ખુલી રહ્યું છે.'],
 'Please wait while the published content loads.':['प्रकाशित सामग्री लोड होने तक प्रतीक्षा करें।','પ્રકાશિત સામગ્રી લોડ થાય ત્યાં સુધી રાહ જુઓ.'],
 'Customizable':['अपनी पसंद अनुसार बनवाएँ','તમારી પસંદ મુજબ બનાવડાવો'], 'Personalizable':['व्यक्तिगत स्पर्श दें','વ્યક્તિગત સ્પર્શ આપો'],
 'Some filters from the previous website are unavailable here. Supported search choices were retained; review the current filters below.':['पुरानी वेबसाइट के कुछ फ़िल्टर यहाँ उपलब्ध नहीं हैं। समर्थित खोज विकल्प रखे गए हैं; नीचे वर्तमान फ़िल्टर जाँचें।','જૂની વેબસાઇટના કેટલાક ફિલ્ટર અહીં ઉપલબ્ધ નથી. સમર્થિત શોધ વિકલ્પો રાખ્યા છે; નીચે હાલના ફિલ્ટર તપાસો.'],
 'Customize this piece':['यह कृति अपनी पसंद की बनाएँ','આ કૃતિ તમારી પસંદની બનાવો'],
 'Customized to your brief':['आपकी ज़रूरत के अनुसार','તમારી જરૂરિયાત મુજબ'],
 'Complete this piece\'s customization form. Its saved order summary is prepared for you to send to the atelier on WhatsApp.':['इस कृति का कस्टमाइज़ेशन फ़ॉर्म भरें। उसका सहेजा सारांश आपके लिए तैयार होता है, जिसे आप WhatsApp पर एटेलियर को भेज सकते हैं।','આ કૃતિનું કસ્ટમાઇઝેશન ફોર્મ ભરો. તેનો સાચવેલો સારાંશ તમારા માટે તૈયાર થાય છે, જેને તમે WhatsApp પર એટેલિયરને મોકલી શકો છો.'],
 'First-time preservation?':['पहली बार यादगार सँजो रहे हैं?','પહેલી વાર યાદગાર સાચવી રહ્યા છો?'],
 'Share clear photographs and wait for the studio\'s guidance before sending anything irreplaceable.':['स्पष्ट तस्वीरें भेजें और कोई अनमोल मूल वस्तु भेजने से पहले स्टूडियो के निर्देशों की प्रतीक्षा करें।','સ્પષ્ટ ફોટા શેર કરો અને અમૂલ્ય મૂળ વસ્તુ મોકલતાં પહેલાં સ્ટુડિયોની સૂચનાની રાહ જુઓ.'],
 'process guide':['प्रक्रिया की जानकारी','પ્રક્રિયાની માહિતી'],
 'Design dimensions':['डिज़ाइन के माप','ડિઝાઇનનાં માપ'], 'Room centerpiece scale':['कमरे के मुख्य आकर्षण का आकार','રૂમના મુખ્ય આકર્ષણનું કદ'],
 'Room-scale spatial piece':['कमरे के स्तर की स्थानिक कृति','રૂમના કદને અનુરૂપ અવકાશીય કૃતિ'],
 'Material direction':['सामग्री की दिशा','સામગ્રીની દિશા'],
 'The displayed design is a starting point. Confirm the final specification and care guidance with the atelier.':['दिखाया गया डिज़ाइन शुरुआत है। अंतिम विवरण और देखभाल के निर्देश एटेलियर से तय करें।','દર્શાવેલી ડિઝાઇન શરૂઆત છે. અંતિમ વિશિષ્ટતાઓ અને સંભાળની સૂચનાઓ એટેલિયર સાથે નક્કી કરો.'],
 'What can I personalize?':['मैं क्या अपनी पसंद का बना सकता हूँ?','હું શું મારી પસંદ મુજબ બનાવી શકું?'],
 'All selections are reviewed for feasibility with the studio.':['हर चयन की व्यवहार्यता स्टूडियो के साथ जाँची जाती है।','દરેક પસંદગીની શક્યતા સ્ટુડિયો સાથે તપાસવામાં આવે છે.'],
 'Materials & final appearance':['सामग्री और अंतिम रूप','સામગ્રી અને અંતિમ દેખાવ'],
 'Images communicate the design direction. Final materials, colour, dimensions and finish are agreed with you before confirmation.':['चित्र डिज़ाइन की दिशा दिखाते हैं। पुष्टि से पहले अंतिम सामग्री, रंग, माप और फ़िनिश आपके साथ तय होते हैं।','ચિત્રો ડિઝાઇનની દિશા બતાવે છે. પુષ્ટિ પહેલાં અંતિમ સામગ્રી, રંગ, માપ અને ફિનિશ તમારી સાથે નક્કી થાય છે.'],
 'Living with your piece':['अपनी कृति के साथ रोज़मर्रा','તમારી કૃતિ સાથે રોજિંદું જીવન'],
 'Ordering & delivery':['ऑर्डर और डिलीवरी','ઓર્ડર અને ડિલિવરી'],
 'Your customization details and references are saved for the atelier. You can then open WhatsApp and tap Send to share the prepared message. Submitting a brief does not confirm an order.':['कस्टमाइज़ेशन के विवरण और संदर्भ एटेलियर के लिए सहेजे जाते हैं। इसके बाद WhatsApp खोलकर Send दबाने से तैयार संदेश भेज सकते हैं। जानकारी जमा करना ऑर्डर की पुष्टि नहीं है।','કસ્ટમાઇઝેશનની વિગતો અને સંદર્ભો એટેલિયર માટે સાચવાય છે. પછી WhatsApp ખોલીને Send દબાવી તૈયાર સંદેશ મોકલી શકો છો. વિગતો સબમિટ કરવી એ ઓર્ડરની પુષ્ટિ નથી.'],
 'In the same spirit.':['इसी भाव की अन्य कृतियाँ।','આ જ ભાવની અન્ય કૃતિઓ.'],
 'Explore the collection or contact the atelier about another direction.':['संग्रह देखें या किसी अन्य विचार के लिए एटेलियर से संपर्क करें।','સંગ્રહ જુઓ અથવા બીજા વિચાર માટે એટેલિયરનો સંપર્ક કરો.'],
 'Explore':['देखें','જુઓ'], 'Make it yours.':['इसे अपना बनाएँ।','તેને તમારી બનાવો.'],
 'A brief for your piece':['आपकी कृति की जानकारी','તમારી કૃતિની વિગતો'],
 'Your choices. Your references. One conversation with the studio.':['आपकी पसंद। आपके संदर्भ। स्टूडियो के साथ एक बातचीत।','તમારી પસંદગીઓ. તમારા સંદર્ભો. સ્ટુડિયો સાથે એક વાતચીત.'],
 'A completed project':['एक पूरी हुई परियोजना','એક પૂર્ણ થયેલો પ્રોજેક્ટ'], 'Project chapters':['परियोजना के भाग','પ્રોજેક્ટના વિભાગો'],
 'The setting':['स्थान','સ્થળ'], 'The brief':['आवश्यकताएँ','જરૂરિયાતો'], 'The response':['डिज़ाइन समाधान','ડિઝાઇનનો ઉકેલ'],
 'A place to begin.':['शुरुआत की जगह।','શરૂઆતની જગ્યા.'], 'The intention.':['उद्देश्य।','હેતુ.'], 'A considered response.':['सोच-समझकर समाधान।','વિચારપૂર્વકનો ઉકેલ.'],
 'Begin your own brief ↗':['अपनी जानकारी से शुरुआत करें ↗','તમારી વિગતો સાથે શરૂઆત કરો ↗'], 'More projects':['और परियोजनाएँ','વધુ પ્રોજેક્ટ'],
 'piece':['कृति','કૃતિ'], 'pieces':['कृतियाँ','કૃતિઓ'], 'min':['मिनट','મિનિટ'], 'applied':['लागू','લાગુ'],
 'Showing':['दिखा रहे हैं','દર્શાવેલ'], 'out of':['कुल में से','કુલમાંથી'],
 'A different starting point.':['दूसरी शुरुआत करें।','બીજી શરૂઆત કરો.'], 'Explore a piece with the atelier.':['एटेलियर के साथ कृति पर चर्चा करें।','એટેલિયર સાથે કૃતિની ચર્ચા કરો.'],
 'There are no published pieces in this collection yet. Contact the atelier to discuss the piece you have in mind.':['इस संग्रह में अभी कोई कृति प्रकाशित नहीं है। अपने विचार पर चर्चा के लिए एटेलियर से संपर्क करें।','આ સંગ્રહમાં હજી કોઈ કૃતિ પ્રકાશિત નથી. તમારા વિચારની ચર્ચા માટે એટેલિયરનો સંપર્ક કરો.'],
 'Remove from saved pieces':['सहेजी कृतियों से हटाएँ','સાચવેલી કૃતિઓમાંથી દૂર કરો'], 'Save to saved pieces':['सहेजी कृतियों में जोड़ें','સાચવેલી કૃતિઓમાં ઉમેરો'],
 'Your list has 60 pieces. Remove one before adding another.':['सूची में 60 कृतियाँ हैं। नई जोड़ने से पहले एक हटाएँ।','યાદીમાં 60 કૃતિઓ છે. નવી ઉમેરતાં પહેલાં એક દૂર કરો.'],
 'Removed from saved pieces.':['सहेजी कृतियों से हटा दिया गया।','સાચવેલી કૃતિઓમાંથી દૂર કરી.'],
 'Saved on this browser.':['इस ब्राउज़र में सहेजा गया।','આ બ્રાઉઝરમાં સાચવ્યું.'],
 'This browser could not store your selection. Keep the piece’s page address instead.':['यह ब्राउज़र आपका चयन सहेज नहीं सका। कृति के पृष्ठ का पता रख लें।','આ બ્રાઉઝર તમારી પસંદગી સાચવી શક્યું નથી. કૃતિના પાનાનું સરનામું રાખો.'],
 'Remove filter':['फ़िल्टर हटाएँ','ફિલ્ટર દૂર કરો'], 'Search':['खोज','શોધ'], 'Sort':['क्रम','ક્રમ'],
 'No journal stories are published yet.':['अभी कोई जर्नल लेख प्रकाशित नहीं है।','હજી કોઈ જર્નલ લેખ પ્રકાશિત નથી.'],
 'Explore the material guide or prepare the first notes for your piece.':['सामग्री की जानकारी पढ़ें या अपनी कृति की शुरुआती जानकारी तैयार करें।','સામગ્રીની માહિતી વાંચો અથવા તમારી કૃતિની શરૂઆતની નોંધો તૈયાર કરો.'],
 'Loading saved pieces…':['सहेजी कृतियाँ लोड हो रही हैं…','સાચવેલી કૃતિઓ લોડ થઈ રહી છે…'],
 'Saved list updated.':['सहेजी सूची बदल दी गई।','સાચવેલી યાદી સુધારી.'],
 'This browser could not update your saved list.':['यह ब्राउज़र सहेजी सूची बदल नहीं सका।','આ બ્રાઉઝર સાચવેલી યાદી સુધારી શક્યું નથી.'],
 'Browser storage is unavailable. Save individual page addresses to return to them.':['ब्राउज़र स्टोरेज उपलब्ध नहीं है। फिर खोलने के लिए पृष्ठों के पते सहेजें।','બ્રાઉઝર સ્ટોરેજ ઉપલબ્ધ નથી. ફરી ખોલવા પાનાંનાં સરનામાં સાચવો.'],
};
