/** Owner decisions: docs/decisions/2026-09-24-operating-policies.md.
 * These are publication candidates, not a fallback for unpublished database content.
 */
export const operatingPolicies: Record<string, {title:string;eyebrow:string;description?:string;sections:[string,string][]}> = {
 '/shipping-delivery': {title:'A considered arrival.',eyebrow:'Delivery & installation',description:'Delivery from Surat, India, with serviceability, transport, installation and charges confirmed for your individual order.',sections:[
  ['From Surat, with a plan','RivyaLivingArt is based in Surat, Gujarat, India. Local delivery within Surat is subject to confirming your address. For other Indian locations, we accept orders only after checking courier serviceability for your PIN code and whether the piece can travel safely. International delivery is unavailable at launch.'],
  ['Installation by arrangement','Installation is available only by prior arrangement within Surat, after confirming the job and installer availability. We do not promise installation elsewhere. Tell us about doorways, lifts, stairs, mounting surfaces and access restrictions before accepting your quotation.'],
  ['Charges agreed before acceptance','Delivery is calculated individually using destination, actual or volumetric weight, dimensions, protective packaging and courier or local transport costs. Installation is quoted separately using product size, mounting requirements, access and labour. All applicable charges and taxes are shown in INR in the final quotation before you accept or pay. Delivery and installation are not universally free.'],
  ['Timing for your piece','We confirm production and delivery estimates individually before accepting an order. Share any important dates early so the proposed schedule can be discussed.'],
  ['Before sending a keepsake','Keep sentimental originals with you until we confirm suitability and provide current transfer instructions. Confirm the recipient, destination and transport arrangements for your particular item.']
 ]},
 '/returns-cancellations': {title:'Clear choices when plans change.',eyebrow:'Cancellations, returns & refunds',sections:[
  ['Before work begins','Submitting a website form creates an order request. It does not confirm a booking or require payment. Before production or specifically approved non-recoverable procurement begins, you may cancel for a full refund of any amount paid.'],
  ['Your approval comes first','We obtain your recorded approval of the final design, dimensions, spelling, colours, quotation and production commencement. Please review these details carefully before work begins.'],
  ['After approved production starts','Change-of-mind cancellation and design changes are not guaranteed; we assess each request individually. We do not apply automatic blanket deposit forfeiture. Any proposed deduction must be lawful, supported by actual non-recoverable costs and covered by terms disclosed before acceptance. We do not impose one-sided cancellation charges.'],
  ['Custom pieces and remedies','Correctly supplied custom products are not eligible for change-of-mind returns. Damaged, defective, incorrect or materially non-conforming products remain eligible for appropriate remedies, including a refund where applicable. Nothing in these terms restricts your statutory consumer rights.'],
  ['Report a concern','Please report visible damage promptly, preferably within seven days, with photographs where possible. This preferred reporting period is not an automatic rejection deadline. Include your inquiry reference and a description of the concern; discuss the piece with us before attempting repairs.'],
  ['Refunds','If we cannot fulfil the agreed order, we provide a full refund. We initiate approved refunds within seven business days. Your bank or payment provider may require additional processing time.']
 ]},
 '/terms': {title:'Clear from the beginning.',eyebrow:'Ordering terms',description:'How an order request becomes an agreed specification, with your recorded approval before production begins.',sections:[
  ['A request starts the conversation','Place Order saves your requirements in the database and Studio. It does not accept a quotation, confirm production or take payment. Choose Open WhatsApp or Copy on the saved receipt and press Send yourself to discuss your order. Opening WhatsApp is not proof that a message was sent, delivered or read.'],
  ['Agree the details','Before production begins, we obtain your recorded approval of the final design, dimensions, spelling, colours, quotation and production commencement. All applicable charges and taxes are quoted in INR before acceptance or payment, with production and delivery estimates confirmed individually.'],
  ['Images and specifications','Collection images are design visualizations. Material selection, dimensions, colour, availability and feasibility must be confirmed for your individual piece. Prices are provided by quotation.'],
  ['Your references','Only upload images you are entitled to share. Avoid unnecessary sensitive information in notes and references. Reference images remain private and are not added to the public catalogue.'],
  ['Changes, delivery and your rights','Our delivery and installation policy and cancellation, return and refund policy describe the applicable arrangements. Individual quotations record the agreed scope. Statutory consumer rights remain intact. The website has no payment gateway or customer accounts.']
 ]},
 '/privacy': {title:'Your brief stays personal.',eyebrow:'Privacy & retention',sections:[
  ['What we collect and why','We collect your name, phone number, optional email, customization choices, notes and reference images to respond to your order request and manage the agreed work. Do not include information that the design discussion does not need.'],
  ['Private records and service providers','Inquiries are stored in our database and reference images in private file storage. Signed-in administrators and staff assigned to an inquiry can access its private details. They are not published in the catalogue. Our service infrastructure uses Vercel and Neon; encrypted recovery archives are held in owner-controlled Google Drive.'],
  ['You choose the WhatsApp handoff','After saving the inquiry, we prepare a message from its saved details. WhatsApp receives the prepared text when you choose Open WhatsApp. You must press Send yourself. You may instead copy the summary. Private image addresses are never included. WhatsApp applies its own privacy terms.'],
  ['Inquiries and orders','For inquiries that do not become orders, we delete or anonymize personal details and reference images 90 days after the last meaningful customer interaction, unless you requested ongoing follow-up. For fulfilled or cancelled orders, necessary customer-service and customization records are retained for 12 months after closure.'],
  ['Reference images and temporary files','Customer reference images are deleted 90 days after order closure unless needed for an active complaint, agreed warranty work or another documented retention requirement. Temporary, unsubmitted uploads are removed after 24 hours through cleanup that excludes active uploads and references linked to saved orders. Generated exports expire after seven days; downloaded managed copies are included in our deletion procedure.'],
  ['Required records and recovery copies','Invoices, accounting records and legally required evidence are retained separately for the applicable mandatory period. Necessary retention exceptions and legal holds are documented with restricted access. Routine encrypted backups use a rolling 30-day retention cycle. Applicable data is deleted from active systems and managed copies; restricted backup copies expire through that cycle, and completed deletions must be reapplied after restoration.'],
  ['Access, correction and deletion','Email rivyalivingart2.0@gmail.com with your inquiry reference to request access, correction or deletion. Bhavya Gondaliya, business owner and Studio administrator, is responsible. We acknowledge requests within two business days and target completion within 30 calendar days after proportionate identity verification. We explain any lawful retention exception. Do not send passwords or unnecessary identity documents.'],
  ['Cookies and browser control','An essential cookie links your form, uploads and private receipt for up to 24 hours. Clearing it or changing browsers may remove receipt access; it does not delete the saved inquiry. No customer account is created. Contact details and reference images are not stored in browser local storage. Unsaved form details remain in the current tab and may be lost when it closes.'],
  ['Service protection','A protected identifier derived from the network address limits repeated requests. Hosting and storage providers process information required to operate their services. Opening a map, email application or WhatsApp takes you to a separate service.']
 ]}
};
