export const shopArticles=[
 {slug:'the-space-around-an-object',title:'The space around an object',category:'In perspective',image:'/media/product-scene-005-16x9.webp',intro:'The room is part of the piece. Begin with the space it leaves behind.',paragraphs:['Before choosing a table or console, mark its proposed footprint on the floor. Walk around it. Pull out a chair. Follow the route you take through the room every day. A generous object needs room to feel generous.','Look at the light, too. A glossy surface can hold the reflection of a window; a more restrained finish can soften that relationship. Notice your space in the morning and again after sunset. A few photographs can make the design conversation much clearer.','Bring the approximate dimensions, the way you use the room and any access constraints into your inquiry. These practical details help give a sculptural idea a place in everyday life.']},
 {slug:'following-the-natural-edge',title:'Following the natural edge',category:'Material notes',image:'/media/product-hero-026-4x5.webp',intro:'Grain, colour and the line where one material meets another.',paragraphs:['A natural edge gives a surface its own rhythm. Its line can lead the eye, interrupt symmetry or shape the space that resin occupies. The relationship between the two materials is as important as either one alone.','Think about the colour of the room around the piece. A deep blue can feel still beside warm timber. A clear resin direction places more emphasis on the edge itself. Neither choice is simply decorative: it changes what you notice first.','A visualization is a way to discuss this relationship. The selected timber, colour and finish will each affect the final appearance, so resolve those details with the studio before confirming a piece.']},
 {slug:'a-commission-begins-with-a-conversation',title:'An idea is enough to begin',category:'From the atelier',image:'/media/product-scene-001-16x9.webp',intro:'You do not need a finished design. You need a starting point.',paragraphs:['Perhaps it is a room that feels unfinished, a flower you cannot bear to throw away or a gift that should say something specific. Start there. The purpose of a brief is to open a conversation, not to arrive with every answer.','Choose the closest piece in the collection and tell us what draws you to it. Include dimensions if you know them, a colour direction and a few references. Explain which parts matter most to you; a photograph alone rarely tells the whole story.','After you place your inquiry, the website saves the brief and prepares a WhatsApp message. Send it to discuss feasibility, price and timing with the studio. Those decisions happen together, before an order is finalized.']}
];
export const shopFaqs=[['How do I place an order?','Choose a piece, complete its customization form and select Place Order. We save your inquiry and private references first, then prepare your order message and try to open WhatsApp. You must press Send yourself. The saved receipt also offers Open WhatsApp and Copy controls.'],['When is my order confirmed?','Submitting the form creates an inquiry. Your design, quotation, payment arrangements and delivery are confirmed separately with the studio on WhatsApp.'],['Can I change the size or colour?','Tell us the proportions and colour direction you have in mind. We will review material availability and feasibility before confirming the final design.'],['Can I upload a reference?','Yes. You can attach up to three JPG, PNG or WebP images, each up to 3 MB. They are stored privately for the studio and are not added to the public catalogue.'],['Do the images show finished pieces?','The collection uses design visualizations to communicate shape, colour and material direction. They do not promise an exact finished appearance. Final details are agreed individually.'],['How long will my piece take?','Timing depends on the design, materials and current studio capacity. Share your preferred date in the brief; we will discuss what is possible before confirming your order.'],['Can you preserve any flower or keepsake?','Suitability depends on the material and its condition. Tell us what you would like to preserve and share clear photographs. Please wait for the studio’s guidance before sending an irreplaceable item.']];
export const shopPages:Record<string,{title:string;eyebrow:string;description?:string;image?:string;imageAlt?:string;sections:[string,string][]}>={
 '/process':{title:'A piece, shaped together.',eyebrow:'The process',sections:[['01 / Discover','Explore the collection and choose a starting point. Look at the shape, the material direction and how it could belong in your space or story.'],['02 / Personalize','Complete the piece’s form with your preferred dimensions, colours, personalization and reference images. Share your name and phone number so the studio can respond.'],['03 / Place your inquiry','Place Order saves your requirements and private references in our Studio. The saved receipt prepares your order message and tries to open WhatsApp. If it cannot open, use the receipt to reopen it or copy the summary. You press Send yourself.'],['04 / Agree the details','Discuss feasibility, the final design, quotation, payment and delivery directly on WhatsApp. Submitting a website inquiry does not confirm an order or collect payment.']]},
 '/our-story':{title:'Art for the way you live.',eyebrow:'RivyaLivingArt',sections:[['Objects with a point of view','RivyaLivingArt brings furniture, resin art and personal expression into one conversation. A dining table can anchor a room. A preserved flower can hold a memory. A small object can say something that a conventional gift cannot.'],['A starting point, not a fixed answer','The collection helps you articulate what you like. Each piece opens a conversation about proportion, colour and purpose. We develop the final details with you.'],['The personal part matters','Your references, the space around a piece and the story behind it give the design its direction. Every order is finalized in a direct WhatsApp conversation with the studio.']]},
 '/materials':{title:'Texture meets depth.',eyebrow:'Material language',sections:[['Timber and resin','Natural grain gives an object movement and variation. Resin introduces a contrasting depth and a way to work with colour and transparency. The balance between them begins with your brief.'],['Colour in context','Consider the surrounding finishes and the light in your room. Share photographs and references so we can discuss the colour direction together. Screen images are useful references, but they cannot guarantee the appearance of a finished material.'],['A finish for your setting','Tell us how the piece will be used. The studio will discuss a suitable surface direction and any care considerations as part of the final specification.']]},
 '/care':{title:'Live with it, thoughtfully.',eyebrow:'Care & materials',sections:[['Follow the guidance for your piece','Different finishes and preserved materials need different care. Ask the studio for the instructions that apply to your final specification.'],['Begin gently','Use a soft cloth and avoid abrasive tools, harsh solvents and direct contact with hot cookware. Confirm any cleaning product with the studio before applying it to a resin surface.'],['Mind the setting','Discuss exposure to sunlight, heat and moisture when placing your order. If a piece changes or is accidentally damaged, share photographs with the studio before attempting a repair.']]},
 '/privacy':{title:'Your brief stays personal.',eyebrow:'Privacy',sections:[['What the form collects','We collect your name, phone number, optional email, customization choices, notes and any reference images you upload. We use them to respond to your inquiry and manage the work you discuss with us.'],['Where your details go','Inquiry records are stored in our database. Reference images are held in private file storage. Administrators and staff assigned to the inquiry can access them after signing in. They are not published in the catalogue. Our current infrastructure uses Vercel and Neon.'],['The WhatsApp handoff','After saving your inquiry, the website prepares a message containing your contact details and brief. WhatsApp receives that text when you open the link. You choose whether to send the message. Private image links are not included. WhatsApp applies its own privacy terms.'],['Cookies and control','An essential cookie links your form, uploads and private receipt for up to 24 hours. Clearing it or changing browsers can remove receipt access; it does not delete a saved inquiry. No customer account is created. Contact details and reference images are not kept in browser local storage. Unsaved form details remain in the current browser tab and may be lost if it is closed.']]},
 '/terms':{title:'Clear from the beginning.',eyebrow:'Ordering terms',sections:[['An inquiry starts the conversation','Place Order submits your requirements to the studio. It does not accept a quotation, confirm production or take payment. Final terms are agreed directly with you on WhatsApp.'],['Images and specifications','Collection images are design visualizations. Material selection, dimensions, colour, availability and feasibility must be confirmed for your individual piece. Prices are provided by quotation.'],['Your references','Only upload images you are entitled to share. Please avoid unnecessary sensitive information in notes and references.'],['Changes, cancellations and delivery','Ask the studio to record the change, cancellation and delivery terms in your individual quotation before agreeing to the order. An inquiry is not acceptance of those terms.']]},
 '/shipping-delivery':{title:'A considered arrival.',eyebrow:'Delivery',sections:[['Discuss the destination','Share your delivery city, preferred timing and relevant access details in your inquiry. For larger furniture, lifts, stairs and doorways may affect the plan.'],['Agree before confirming','Availability, packing, transport, installation needs and charges are discussed with the studio as part of your quotation. We do not promise a standard delivery date for a custom piece.']]},
 '/returns-cancellations':{title:'Talk to us about a change.',eyebrow:'Changes & cancellations',sections:[['Before your order is confirmed','Use the WhatsApp conversation to resolve design details and ask about the applicable cancellation terms before accepting a quotation.'],['After confirmation','Contact the studio promptly with your inquiry reference. What can be changed depends on the agreed specification and the current stage of work.']]},
 '/accessibility':{title:'A website for more people.',eyebrow:'Accessibility',sections:[['Our approach','We aim to make the collection and order forms usable with a keyboard, readable at larger text sizes and considerate of reduced-motion preferences. The redesign includes labelled fields, visible focus indicators and written error guidance.'],['Evaluation status','A complete accessibility evaluation of this redesign has not yet been completed. We do not currently claim conformance with a particular accessibility standard.'],['If something gets in the way','Call +91 83204 04132 or email rivyalivingart2.0@gmail.com. Tell us the page and the difficulty you encountered so we can help with your inquiry.']]},
 '/architects':{title:'A material partner for your vision.',eyebrow:'For architects & interior designers',sections:[['Begin with the space','Share the piece, intended use, approximate dimensions and references. Include the delivery city and access constraints to help frame the design discussion.'],['Develop the specification together','Choose a design from the collection and use its customization form. Add project requirements in the notes; we will discuss feasibility and the quotation with you on WhatsApp.']]},
 '/contact':{title:'Let’s begin a conversation.',eyebrow:'Contact the atelier',sections:[['For a new piece','Choose a design and complete its customization form. That gives the studio a saved brief and prepares the WhatsApp conversation.'],['For general questions','Use the phone or email details below for questions about the atelier, accessibility or the website. General contact does not open a WhatsApp order message.'],['For an existing inquiry','Call or email the atelier and include your RLA inquiry reference so we can find the saved details. Do not submit another order form solely to recover an existing inquiry.']]}
};

shopPages['/privacy'].sections.push(
 ['Unsubmitted and saved references','Images uploaded without a submitted inquiry become eligible for administrator cleanup after 24 hours; removal is not automatic at that deadline. Saved inquiries and their reference images do not currently have an automatic deletion deadline.'],
 ['Requests about your information','Email rivyalivingart2.0@gmail.com with your inquiry reference to request access, a correction or deletion. The atelier will review the request and may need to verify that it comes from the person concerned. Receipt expiry does not remove database records, private references or backup copies.'],
 ['Service protection','The service uses a protected identifier derived from the network address to limit repeated requests. Hosting and storage providers also process information needed to operate their services. Opening a map, email application or WhatsApp takes you to a separate service.']
);
shopPages['/architects'].sections.push(
 ['Make the brief useful','Distinguish measured site dimensions from proposed product dimensions. Label references with what matters: a silhouette, a material relationship or an intended use. Do not include confidential client details that the design discussion does not need.'],
 ['Keep responsibilities clear','Ask the atelier to clarify the proposed scope, required drawings, material references and installation responsibilities. A catalogue visualization does not resolve construction, performance or site conditions.']
);
shopPages['/shipping-delivery'].sections.push(
 ['Before sending a keepsake','Keep sentimental originals with you until the atelier confirms suitability and provides current transfer instructions. Confirm the recipient, destination and agreed transport arrangements for your particular item.']
);
shopPages['/returns-cancellations'].sections.push(
 ['If something arrives with a concern','Contact the atelier with the inquiry reference and a clear description of the issue. Keep the relevant photographs and agreed specification available for review. Do not attempt a repair before discussing the piece with the atelier.']
);
shopFaqs.push(
 ['Can I start without choosing a catalogue piece?','Yes. Begin a piece offers a custom brief for furniture, memory art or a personal gift. Your requirements are saved before the order message is prepared for WhatsApp.'],
 ['Does the website send a WhatsApp message for me?','No. It prepares the saved order details and may open WhatsApp after a successful save. You press Send yourself. The website cannot confirm whether you sent the message.'],
 ['What if WhatsApp does not open?','Use Open WhatsApp on the saved receipt or copy its complete order summary and paste it into the conversation. A long brief may require copying before opening. Do not create another inquiry just to send the same details.'],
 ['Does my receipt expiring delete the inquiry?','No. Private receipt access lasts up to 24 hours in the original browser. The saved inquiry remains with the studio. Keep your RLA reference and contact the atelier if you need help finding it.'],
 ['Can I use WhatsApp for a general website question?','The website prepares WhatsApp messages only for saved product or custom-piece requests. Use the contact page to call or email the atelier about general questions.']
);


const descriptions:Record<string,string>={
 '/our-story':'Furniture, resin art and personal expression. Discover how your space, references and story give a piece its direction.',
 '/process':'Find a starting point, prepare your brief and send the saved order details. The final design is agreed with you.',
 '/materials':'Explore the visual relationship between timber, resin, colour and the room around your piece.',
 '/care':'Care begins with the materials and finish agreed for your individual piece.',
 '/architects':'Prepare a clear project brief with dimensions, intended use and material references, then develop the specification with the atelier.',
 '/contact':'Call or email the atelier for general questions. For a new product or custom piece, start with a saved order brief.',
 '/privacy':'How your brief, private references and receipt are handled, and how to contact the atelier about your information.',
 '/terms':'What submitting an inquiry means and which details need agreement before a custom order is confirmed.',
 '/shipping-delivery':'Discuss the destination, access, timing and transport arrangements for your individual piece.',
 '/returns-cancellations':'How to raise a change, cancellation or concern and keep it connected to your agreed specification.',
 '/accessibility':'Our approach to access, the current evaluation status and a way to report a difficulty.'
};
for(const [route,description]of Object.entries(descriptions))shopPages[route].description=description;
for(const [route,image,imageAlt]of [
 ['/our-story','/media/product-hero-026-4x5.webp','Timber grain and resin in a sculptural design visualization'],
 ['/process','/media/product-scene-001-16x9.webp','River Channel dining table in a room, a design visualization'],
 ['/architects','/media/product-scene-005-16x9.webp','Estuary dining table in a room, a design visualization']
])Object.assign(shopPages[route],{image,imageAlt});
// Retain the existing accessibility contact section identity; evaluation is appended.
const accessibility=shopPages['/accessibility'].sections;
const evaluation=accessibility.splice(accessibility.findIndex(s=>s[0]==='Evaluation status'),1)[0];
accessibility.push(evaluation);

// Keep the original existing-inquiry section at section-2.
const contactSections=shopPages['/contact'].sections;
const generalContact=contactSections.splice(contactSections.findIndex(s=>s[0]==='For general questions'),1)[0];
contactSections.push(generalContact);
