import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {login,launch,origin,record,output} from './common.mjs';
const require=createRequire(import.meta.url),{browser,page,context}=await launch(await login(),{viewport:{width:390,height:844},reducedMotion:'reduce'});
const checks=[],states=[],layouts=[],errors=[];let complete=false;
page.on('pageerror',error=>errors.push(error.message));
const pass=(name,value)=>{assert.ok(value,name);checks.push(name);};
const open=async path=>{await page.goto(origin+path,{waitUntil:'networkidle'});};
async function axe(name){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const r=await page.evaluate(async()=>{const r=await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return {violations:r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))};});states.push({name,...r});pass(name+' has no automated violations',!r.violations.length);}
async function modal(opener,name){await opener.focus();await page.keyboard.press('Enter');const dialog=page.locator('dialog[open]');await dialog.waitFor();pass(name+' has an accessible name',!!await dialog.getAttribute('aria-labelledby'));await axe(name);if(name==='Mobile navigation')await page.screenshot({path:resolve(output,'navigation-mobile.png')});
 const ends=await dialog.evaluate(el=>{const nodes=[...el.querySelectorAll('a[href],button,input,select,textarea,[tabindex]')].filter(n=>n.tabIndex>=0&&!n.matches(':disabled')&&n.getClientRects().length);nodes[0].setAttribute('data-c6-first','');nodes.at(-1).setAttribute('data-c6-last','');return nodes.length;});pass(name+' exposes controls',ends>1);
 await dialog.locator('[data-c6-first]').focus();await page.keyboard.press('Shift+Tab');pass(name+' wraps backward',await dialog.locator('[data-c6-last]').evaluate(n=>n===document.activeElement));await page.keyboard.press('Tab');pass(name+' wraps forward',await dialog.locator('[data-c6-first]').evaluate(n=>n===document.activeElement));await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});pass(name+' restores opener focus',await opener.evaluate(n=>n===document.activeElement));}
try{
 await open('/process');await page.keyboard.press('Tab');pass('Skip link is first keyboard stop',await page.locator('.skip-link').evaluate(n=>n===document.activeElement));await page.keyboard.press('Enter');pass('Skip targets the main content',await page.locator('#main-content').evaluate(n=>n===document.activeElement));
 await modal(page.getByRole('button',{name:'Open navigation',exact:true}),'Mobile navigation');await modal(page.getByRole('button',{name:'Search pieces',exact:true}),'Search dialog');
 await open('/pieces/river-channel');const gallery=page.getByRole('group',{name:'Product gallery. Use left and right arrow keys to change image.',exact:true});await gallery.getByRole('button',{name:'Next image',exact:true}).focus();await page.keyboard.press('End');const count=await gallery.locator('[aria-pressed]').count();pass('Gallery End selects last image',await gallery.locator('[aria-pressed]').last().getAttribute('aria-pressed')==='true');await page.keyboard.press('Home');pass('Gallery Home selects first image',await gallery.locator('[aria-pressed]').first().getAttribute('aria-pressed')==='true');await page.keyboard.press('ArrowRight');pass('Gallery Right selects next image',count>1&&await gallery.locator('[aria-pressed]').nth(1).getAttribute('aria-pressed')==='true');await modal(page.getByRole('button',{name:/Enlarge image of/}),'Enlarged gallery');
 await open('/pieces/river-channel/customize');pass('Customization starts at the top without input autofocus',await page.evaluate(()=>scrollY<10&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)));await page.getByRole('button',{name:'Your details →',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-invalid')==='true');pass('Invalid form field receives focus',await page.locator('[aria-invalid=true]').count()>0);pass('Invalid field references a visible explanation',await page.evaluate(()=>{const el=document.activeElement;return (el.getAttribute('aria-describedby')||'').split(' ').some(id=>document.getElementById(id)?.textContent.trim());}));await axe('Customization validation');await page.screenshot({path:resolve(output,'form-errors-mobile.png'),fullPage:true});
 await open('/search?q=river');pass('Applied filters expose named remove actions',await page.getByRole('link',{name:/Remove.*river/i}).count()>0);await page.getByRole('link',{name:/Remove.*river/i}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!location.search.includes('q='));pass('Removing a filter focuses the result announcement',await page.locator('#catalogue-results').evaluate(n=>n===document.activeElement));await axe('Search filter result');
 await open('/faq');await page.getByRole('searchbox',{name:'Find an answer'}).fill('c6noresultsxyz');pass('FAQ announces empty result',await page.getByRole('status').filter({hasText:'0 answers'}).count()>0);await page.getByRole('button',{name:'Show all questions',exact:true}).click();await page.locator('main summary').first().focus();await page.keyboard.press('Enter');pass('FAQ opens with Enter',await page.locator('main details').first().getAttribute('open')!==null);await axe('Open FAQ answer');
 for(const route of ['/','/collectible-design','/search','/pieces/river-channel','/pieces/river-channel/customize','/commission/customize','/our-story','/process','/materials-care','/journal','/faq','/contact','/privacy']){
  await open(route);for(const width of [720,360]){await page.setViewportSize({width,height:1000});const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,headingVisible:!!document.querySelector('h1')?.getClientRects().length}));layouts.push({route,width,method:'Narrow CSS viewport equivalent of 1440px at 200%/400%; not native browser zoom',...result});pass(route+' '+width+'px reflow',!result.overflow&&result.headingVisible);}
 }
 await page.evaluate(()=>document.documentElement.style.zoom='');await page.setViewportSize({width:390,height:844});await open('/');await page.screenshot({path:resolve(output,'home-mobile.png')});
 await open('/studio/content?record=page%3Ahome');const title=page.locator('#content-field-title');await title.waitFor();const original=await title.inputValue();await title.fill(original+' C6 unsaved test');await modal(page.getByRole('button',{name:'Open Studio navigation',exact:true}),'Studio navigation with an unsaved draft');pass('Navigation retains the unsaved content title',await title.inputValue()===original+' C6 unsaved test');await page.keyboard.press('Control+k');await page.getByRole('searchbox',{name:'Page name'}).fill('images');await page.keyboard.press('Escape');pass('Page-finder search retains the unsaved content title',await title.inputValue()===original+' C6 unsaved test');await title.fill(original);await axe('Selected Studio record status');
 for(const locale of ['hi','gu']){await context.addCookies([{name:'NEXT_LOCALE',value:locale,url:origin}]);await open('/commission/customize');const actual=await page.locator('html').getAttribute('lang');pass(locale+' locale is valid or correctly falls back to English',[locale,'en'].includes(actual));states.push({name:locale+' reviewed-language policy',htmlLang:actual});await axe(locale+' customization');}
 pass('No uncaught browser errors',errors.length===0);complete=true;
}finally{await browser.close();record('interactions',{at:new Date().toISOString(),complete,checks,states,layouts,errors,limitations:'Automation only. No form submission, publication or external message. Narrow-viewport reflow does not replace native browser zoom, human assistive technology or physical devices. CSS zoom was rejected as a proxy because it does not trigger viewport media queries.'});}
