import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {origin,record} from './common.mjs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),samples=[];
try{for(const width of [390,1440])for(const route of ['/','/collectible-design','/pieces/river-channel','/our-story','/process']){
 const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:width===390?3:1,reducedMotion:'no-preference'}),page=await context.newPage();await page.goto(origin+route,{waitUntil:'networkidle'});
 const sample=await page.evaluate(()=>{
  const images=[...document.images].filter(i=>{const r=i.getBoundingClientRect();return r.top<innerHeight&&r.bottom>0&&r.width>0;}).map(i=>{const url=new URL(i.currentSrc),r=i.getBoundingClientRect(),resource=performance.getEntriesByName(i.currentSrc)[0];return {reusedForLargerSlot:[...document.images].some(other=>other!==i&&other.currentSrc===i.currentSrc&&other.getBoundingClientRect().width>r.width*1.5),altPresent:i.hasAttribute('alt'),width:Math.round(r.width),requestedWidth:Number(url.searchParams.get('w')),bytes:resource?.encodedBodySize||0,complete:i.complete&&i.naturalWidth>0,loading:i.loading,priority:i.fetchPriority,sizes:i.sizes};});
  const animations=[...document.querySelectorAll('*')].flatMap(el=>{const s=getComputedStyle(el);return s.animationName==='none'?[]:[{name:s.animationName,timeline:s.animationTimeline,durations:s.animationDuration.split(',').map(v=>v.trim()==='auto'?'auto':parseFloat(v)*1000),iterations:s.animationIterationCount.split(',').map(Number)}];});
  return {images,animations,overflow:document.documentElement.scrollWidth>innerWidth+1};
 });
 const failures=[];for(const i of sample.images){if(!i.complete||!i.altPresent)failures.push('Incomplete or unnamed image');if(i.bytes>200000)failures.push('Visible image exceeds 200KB regression budget');if(!i.reusedForLargerSlot&&i.requestedWidth>Math.max(640,i.width*(width===390?3:1)*1.5))failures.push('Visible image exceeds 1.5x displayed device-pixel width');}
 for(const a of sample.animations)if(a.durations.some(n=>n>1000)||a.iterations.some(n=>n>1||!Number.isFinite(n)))failures.push('Nonessential entrance motion exceeds 1s or repeats');
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const reduced=await page.evaluate(()=>({running:document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target?.checkVisibility({visibilityProperty:true,opacityProperty:true})).length,runningNames:document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target?.checkVisibility({visibilityProperty:true,opacityProperty:true})).map(a=>({name:a.animationName||a.transitionProperty,computed:a.effect?.target?getComputedStyle(a.effect.target).animationName:null})),smoothScroll:getComputedStyle(document.documentElement).scrollBehavior==='smooth'}));if(reduced.running||reduced.smoothScroll)failures.push('Reduced motion has active animation or smooth scroll');
 samples.push({route,width,...sample,reduced,failures});console.log(JSON.stringify({route,width,failures}));await context.close();
}}finally{await browser.close();record('media-motion',{at:new Date().toISOString(),scope:'Local compiled image and motion regression guards adopted for C6; not a field-performance certificate. Initial visible images only; 200KB each, selected width <=1.5x displayed device pixels with 640px floor, timed entrance <=1s once, native scroll timelines separate; reuse of an already loaded larger visible image is exempt from width guard, reduced motion static.',samples});}
assert.ok(samples.every(s=>!s.failures.length),'Image/motion budgets');
