import { concepts, type Concept } from '@/lib/catalogue';
export type Price = { mode: 'request' } | { mode: 'fixed' | 'starting'; amount: number; sample: true };
export type Product = { id: string; slug: string; name: string; subtitle: string; category: string; tier: 'large' | 'memory' | 'personal'; source?: Concept; image: string; scene?: string; story: string; dimensions: string; material: string; price: Price; sample: true };
const portrait = (id: string) => `/media/product-hero-${id}-4x5.webp`;
const scene = (id: string) => `/media/product-scene-${id}-16x9.webp`;
const approvedProducts: Product[] = [
 { id:'SITES-L-001',slug:'river-channel',name:'River Channel',subtitle:'Live-Edge Dining Table',category:'Tables',tier:'large',image:portrait('001'),scene:scene('001'),story:'Two natural edges trace the course of a deep blue resin channel. This dining-table concept explores the meeting of an organic silhouette and an architectural base — a place around which a room can gather.',dimensions:'240 × 100 × 75 cm',material:'Live-edge timber · pigmented resin · metal base',price:{mode:'request'},sample:true },
 { id:'SITES-L-003',slug:'shallow-basin',name:'Shallow Basin',subtitle:'Coffee Table',category:'Tables',tier:'large',image:portrait('003'),scene:scene('003'),story:'A quiet, low circular form holds a pool of colour. The Shallow Basin concept brings the movement of resin close to the floor, inviting a slower look at its depth and the grain around it.',dimensions:'110 × 110 × 35 cm',material:'Timber · pigmented resin',price:{mode:'starting',amount:85000,sample:true},sample:true },
 { id:'SITES-L-005',slug:'narrow-span',name:'Narrow Span',subtitle:'Console Table',category:'Consoles',tier:'large',image:portrait('005'),scene:scene('005'),story:'A fine line of blue runs through a narrow, purposeful surface. Designed as a concept for transitional spaces, Narrow Span gives an entrance or a quiet wall its own moment.',dimensions:'160 × 38 × 80 cm',material:'Timber · pigmented resin · metal base',price:{mode:'request'},sample:true },
 { id:'SITES-L-009',slug:'entryway-bench',name:'Entryway',subtitle:'Bench',category:'Seating',tier:'large',image:portrait('009'),story:'A substantial timber seat becomes a study of the river line. This bench concept offers a simple geometry with a resin detail that can be considered in relation to the surrounding space.',dimensions:'150 × 40 × 45 cm',material:'Timber · pigmented resin',price:{mode:'fixed',amount:65000,sample:true},sample:true },
 { id:'SITES-L-016',slug:'lattice-object',name:'Lattice Object',subtitle:'3D + Resin Study',category:'Spatial art',tier:'large',image:portrait('016'),story:'An open lattice is suspended within a transparent volume. This concept tests the relationship between solid and void; the final scale, fabrication and placement would be resolved through a commission.',dimensions:'Scale to be developed',material:'Fabricated lattice · transparent resin',price:{mode:'request'},sample:true }
];
const identityMap: Record<string,string> = {'SITES-L-001':'DP001','SITES-L-003':'DP013','SITES-L-005':'DP035','SITES-L-009':'DP048','SITES-L-016':'DP069'};
export const products: Product[] = [
 ...approvedProducts.map(p=>({...p,id:identityMap[p.id],source:concepts.find(c=>c.id===identityMap[p.id])})),
 ...concepts.filter(c=>!Object.values(identityMap).includes(c.id)).map(c=>({
 id:c.id,slug:c.slug,name:c.title,subtitle:c.type,category:c.tier==='LARGE'?({tables:'Tables',seating:'Seating',consoles:'Consoles',installations:'Spatial art'} as const)[c.category]:c.category,
 tier:c.tier==='LARGE'?'large' as const:c.tier==='MEDIUM'?'memory' as const:'personal' as const,
 image:c.image || '',
 story:c.description,dimensions:`${c.dimensions.width} × ${c.dimensions.depth} × ${c.dimensions.height} mm`,material:c.materials.map(m=>m.label).join(' · '),
 price:c.priceType==='ON_REQUEST'?{mode:'request' as const}:{mode:c.priceType==='FIXED'?'fixed' as const:'starting' as const,amount:(c.priceAmountMinor||0)/100,sample:true as const},sample:true as const,source:c
 }))
];
export const furnitureProducts = products.filter(p=>p.tier==='large');
export function findProduct(slug:string){return products.find(p=>p.slug===slug || p.source?.slug===slug)}
export function priceLabel(p:Price){ if(p.mode==='request') return 'Price on request'; return `${p.mode==='starting'?'Starting from ':''}₹${p.amount.toLocaleString('en-IN')}`; }
export const journal = [
 {id:'SITES-J-001',title:'The space around an object',category:'In perspective',image:scene('005'),intro:'A collectible piece needs more than a place to stand. Consider the light, the paths through a room and the quiet space around it.',body:'Begin with how a room is used. Mark out the proposed footprint on the floor, then move through the space as you normally would. The empty space around a table or console is part of the composition. A strong silhouette can feel generous in one setting and crowded in another.\n\nLook at the room at different times of day. Resin catches light differently from timber; a placement that works in morning light may tell a different story after sunset. Keep these observations for a future consultation. They can be as useful as a photograph.\n\nThis is sample editorial content for the design trial. Final advice and project-specific requirements need the atelier’s review.'},
 {id:'SITES-J-002',title:'Following the natural edge',category:'Material notes',image:portrait('026'),intro:'Grain, movement and the line between wood and resin. A closer look at the material language of the collection.',body:'A natural edge is a starting point for a composition. Its movement can shape the course of a resin channel and give the surface a direction. The design conversation begins by considering which of these features should remain prominent.\n\nThe concept images here explore deep blue resin beside expressive timber grain. Actual appearance depends on the selected timber, colour sample, resin formulation and finish. A visualization can communicate an intention; it cannot guarantee the exact appearance of a future object.\n\nThis is sample editorial content. Material claims and the final production process remain subject to the atelier’s approval.'},
 {id:'SITES-J-003',title:'A commission begins with a conversation',category:'From the atelier',image:scene('001'),intro:'A room, a reference, an idea. What to bring to the first conversation about a piece made for you.',body:'You do not need a finished design before starting a conversation. A sense of what the piece will do, where it will live and what draws you to a particular material is enough to begin exploring.\n\nUseful references include a simple plan, approximate dimensions and images that explain the atmosphere you want. Access to the space matters too: lifts, stairs and doorways can affect the design and installation discussion. Timing and an optional budget help frame what can be explored.\n\nThe final application will save an enquiry before a manual WhatsApp handoff. This Sites trial prepares a synthetic sample summary only and sends nothing. This article is a short sample draft for review.'}
];
export const media = { material:portrait('026'), memory:portrait('020'), gifts:portrait('029') };
