import {login,launch,origin,record,fingerprint} from './common.mjs';
import {expect as baseExpect} from '@playwright/test';
import assert from 'node:assert/strict';
const expect=baseExpect.configure({timeout:30000}),before=await fingerprint(),{browser,context}=await launch(await login()),checks=[],errors=[];
const done=name=>{checks.push(name);record('administration-browser',{checks,errors,complete:false});console.log('PASS '+name);};
await context.route('**/api/studio/**',route=>route.request().method()==='POST'?route.fulfill({status:503,json:{error:'C5 controlled admin rejection.'}}):route.continue());
try{
 const page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
 let fail=true;const exportsFault=route=>fail?route.fulfill({status:503,json:{error:'C5 exports unavailable.'}}):route.continue();await page.route('**/api/studio/operations?view=exports',exportsFault);await page.goto(origin+'/studio/activity');await expect(page.getByText('Export tracking is unavailable.',{exact:false})).toBeVisible();fail=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByText('Export tracking is unavailable.',{exact:false})).toHaveCount(0);done('Export tracking initial failure is explicit and retry clears it');fail=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByText('Export tracking could not be refreshed.',{exact:false})).toBeVisible();done('Export tracking stale read is labelled');
 await page.goto(origin+'/studio/settings');await expect(page.locator('input[type=email]')).toBeVisible();const original=await page.locator('input[type=email]').inputValue();const contactFault=route=>route.fulfill({status:503,json:{error:'C5 contact read failed.'}});await page.route('**/api/studio/settings',contactFault);await page.getByRole('button',{name:'Reload',exact:true}).click();await expect(page.getByText('C5 contact read failed.',{exact:false})).toBeVisible();await expect(page.locator('input[type=email]')).toHaveValue(original);await page.unroute('**/api/studio/settings',contactFault);await page.getByRole('button',{name:'Reload',exact:true}).click();await expect(page.getByText('C5 contact read failed.',{exact:false})).toHaveCount(0);done('Contact reload failure retains current facts and retry clears warning');
 await page.goto(origin+'/studio/staff');await page.getByRole('button',{name:'Edit access',exact:true}).first().click();const name=page.getByLabel('Name',{exact:true});await name.fill('C5 browser-only unsaved staff name');
 for(const status of [503,409,401]){
  await page.getByRole('button',{name:'Review staff access',exact:true}).click();const fault=route=>route.request().method()==='POST'?route.fulfill({status,json:{error:'C5 staff '+status+' rejected.'}}):route.continue();await page.route('**/api/studio/workspace',fault);await page.getByRole('button',{name:'Confirm staff access',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm staff access',exact:true})).toBeEnabled();if(status===401)await expect(page.getByRole('button',{name:'Check renewed access'})).toHaveCount(1);else await expect(page.getByRole('dialog').getByText('C5 staff '+status+' rejected.',{exact:false})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Keep editing',exact:true}).click();await expect(name).toHaveValue('C5 browser-only unsaved staff name');await page.unroute('**/api/studio/workspace',fault);if(status===401){await page.getByRole('button',{name:'Check renewed access'}).click();await expect(page.getByRole('button',{name:'Check renewed access'})).toHaveCount(0);}done('Staff '+status+' keeps typed access change without committing');
 }
 await page.getByRole('button',{name:'Review staff access',exact:true}).click();const committed=route=>route.request().method()==='POST'?route.fulfill({status:200,json:{saved:true}}):route.fulfill({status:503,json:{error:'C5 staff reload failed.'}});await page.route('**/api/studio/workspace',committed);await page.getByRole('button',{name:'Confirm staff access',exact:true}).click();await expect(page.getByText('Access was saved, but the staff list could not refresh.',{exact:false}).first()).toBeVisible();done('Simulated saved staff access plus failed refresh is distinguished');
 const prompt=page.waitForEvent('dialog');const click=page.getByRole('button',{name:'Revoke sessions',exact:true}).first().click();await(await prompt).accept();await click;await expect(page.getByText('Sessions were revoked, but staff access could not refresh.',{exact:false}).first()).toBeVisible();done('Simulated committed revocation plus failed refresh is distinguished');
 assert.deepEqual(errors,[]);assert.deepEqual(await fingerprint(),before);record('administration-browser',{checkedAt:new Date().toISOString(),checks,errors,complete:true,actualWrites:0,protectedRecordsUnchanged:true});
}finally{await browser.close();}
