import {login,launch,origin,record,modules,output} from './common.mjs';
import {expect as baseExpect} from '@playwright/test';
import assert from 'node:assert/strict';
const expect=baseExpect.configure({timeout:30000}),{browser,context,page}=await launch(await login()),checks=[],zoom=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin+'/studio/navigation');const field=page.getByLabel('English label',{exact:true}).first();await expect(field).toBeVisible();await field.fill('C5 held navigation draft');
 let held,announce;const hit=new Promise(resolve=>{announce=resolve;});await page.route('**/api/studio/site-settings',route=>{if(route.request().method()==='POST'){held=route;announce();}else return route.continue();});
 await page.getByRole('button',{name:'Publish navigation & languages',exact:true}).click();await hit;await expect(field).toBeDisabled();await expect(page.getByRole('button',{name:'Add link',exact:true})).toBeDisabled();await held.fulfill({status:503,json:{error:'C5 held request failed.'}});await expect(field).toBeEnabled();await expect(field).toHaveValue('C5 held navigation draft');checks.push('Navigation locks all editing controls while publishing and retains edits on failure');
 await page.close();
 for(const key of modules){const p=await context.newPage();await p.goto(origin+'/studio'+(key?'/'+key:''));await expect(p.locator('#main-content h1')).toBeVisible();await p.waitForFunction(()=>![...document.querySelectorAll('#main-content [role="status"]')].some(e=>/^(Loading|Opening|Checking saved)/.test(e.textContent.trim())),{},{timeout:40000});await p.evaluate(()=>{document.documentElement.style.zoom='2';});const metrics=await p.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth,zoom:getComputedStyle(document.documentElement).zoom}));assert.equal(metrics.zoom,'2');const overflow=metrics.scroll>metrics.viewport+1||metrics.body>metrics.viewport+1;const elements=overflow?await p.evaluate(()=>[...document.querySelectorAll('#main-content *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,classes:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right}))):[];zoom.push({module:key||'overview',...metrics,overflow,elements});if(key==='navigation')await p.screenshot({path:output+'/navigation-zoom-200.png'});await p.close();record('busy-zoom',{checks,zoom,errors,complete:false});console.log('PASS 200% CSS zoom '+(key||'overview'));}
 assert.deepEqual(errors,[]);assert.ok(zoom.every(row=>!row.overflow),'200% CSS zoom body reflow across all modules');record('busy-zoom',{checkedAt:new Date().toISOString(),checks,zoom,errors,complete:true,method:'Automated 200% CSS page zoom plus separately verified 720 CSS-pixel viewport reflow. Native browser chrome zoom, human screen-reader use and physical hardware are not certified.'});
}finally{await browser.close();}
