'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {businessDatePreset,formatBusinessTime} from '@/lib/business-time';
import {stageLabel} from '@/lib/studio-orders';
import type {StudioAnalytics} from '@/lib/studio-analytics';
import {studioFetch} from './workspace-api';
import s from './workspace.module.css';
export function AnalyticsPanel(){
 const params=useSearchParams(),defaults=businessDatePreset(7);
 const [from,setFrom]=useState(params.get('from')||defaults.from),[to,setTo]=useState(params.get('to')||defaults.to),[range,setRange]=useState({from,to}),[data,setData]=useState<StudioAnalytics|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;void studioFetch('/api/studio/analytics?'+new URLSearchParams(range)).then(v=>{if(active){setData(v);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[range,attempt]);
 const href=(extra:Record<string,string>={})=>'/studio/inquiries?'+new URLSearchParams({...data?.range&&{from:data.range.from,to:data.range.to},mode:'list',...extra});
 return <><div className={s.heading}><div><h1>Inquiry analytics.</h1><p>Saved operational records, with the same account scope as Commissions. Website traffic, revenue and conversion tracking are not configured.</p></div><button onClick={()=>{setLoading(true);setAttempt(v=>v+1);}}>Refresh analytics</button></div><form className={s.panel} onSubmit={e=>{e.preventDefault();setLoading(true);setRange({from,to});window.history.replaceState(null,'','/studio/analytics?'+new URLSearchParams({from,to}));}}><div className={s.actions}>{([1,7,30] as const).map(days=><button type="button" key={days} onClick={()=>{const next=businessDatePreset(days);setFrom(next.from);setTo(next.to);}}>{days===1?'Today':'Last '+days+' days'}</button>)}</div><div className={s.grid}><label>Received from (IST)<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Received through (IST)<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className={s.primary}>Apply period</button></form>{error&&<p role="alert">{error} {data?'Previous results remain below and may be stale.':''}</p>}{loading&&<p role="status">Loading scoped aggregates… Previous results, if shown, belong to their displayed period.</p>}{data&&<><p role="status">{data.range.from} through {data.range.to} · {data.range.days} inclusive IST days · {data.scope==='all'?'All records':'Assigned website inquiries only'} · refreshed {formatBusinessTime(data.asOf)}</p><div className={s.metrics}><Link href={href()}><strong>{data.totals.received}</strong>Records received</Link><Link href={href({source:'website'})}><strong>{data.totals.website}</strong>Website inquiries</Link><Link href={href({source:'manual'})}><strong>{data.totals.manual}</strong>Staff-entered orders</Link><div className={s.panel}><strong>{data.totals.previous}</strong>Records received in preceding {data.range.days} days</div></div><section className={s.panel}><h2>Current stages of this period’s records</h2><p>This is the current stage of each received record, not a conversion funnel or a history of stage changes.</p>{data.stages.length?<div className={s.metrics}>{data.stages.map(v=><Link key={v.status} href={href({stage:v.status})}><strong>{v.count}</strong>{stageLabel(v.status)}</Link>)}</div>:<p>No records were received in this scope and period.</p>}</section><section className={s.panel}><h2>Received by IST date</h2><div className={s.tableWrap} role="region" aria-label="Daily received records" tabIndex={0}><table><thead><tr><th scope="col">Date</th><th scope="col">Records received</th></tr></thead><tbody>{data.days.map(day=><tr key={day.date}><th scope="row"><Link href={'/studio/inquiries?'+new URLSearchParams({from:day.date,to:day.date,mode:'list'})}>{day.date}</Link></th><td><meter aria-label={day.date+' received records'} value={day.count} max={Math.max(1,...data.days.map(d=>d.count))}/>{' '+day.count}</td></tr>)}</tbody></table></div></section></>}</>;
}
