'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ContentCompare} from './content-compare';
import {SavedPreviewFrame} from './saved-preview-frame';
import s from './workspace.module.css';
const states=['Loading','Empty','Draft saved','Validation error','Conflict','Session expired','Published; verification needed','Unavailable image','Long content','Saved preview'] as const;
export function AuthoringStates(){
 const [state,setState]=useState<typeof states[number]>('Loading'),[message,setMessage]=useState('');
 const [record,setRecord]=useState('page:home'),[version,setVersion]=useState(1),[preview,setPreview]=useState<{record:string;version:number;attempt:number}|null>(null);
 return <div className={s.workspace}><main id="main-content" tabIndex={-1} className={s.editor} style={{maxWidth:1000,margin:'auto'}}><h1>Authoring state gallery</h1><p>Isolated QA fixtures · These examples do not save, publish or report successful live tests.</p><Link href="/studio/content">Return to real content</Link><label>State<select value={state} onChange={e=>{setState(e.target.value as typeof state);setMessage('');}}>{states.map(v=><option key={v}>{v}</option>)}</select></label><section className={s.panel} aria-label="Fixture state"><h2>{state}</h2>
 {state==='Loading'?<p role="status" aria-busy="true">Loading saved content…</p>:state==='Empty'?<p>No articles match this search. <button onClick={()=>setMessage('Fixture search cleared.')}>Clear filters</button></p>:state==='Draft saved'?<p role="status">Draft saved. Your public page is unchanged.</p>:state==='Validation error'?<><p role="alert">Add a heading before saving.</p><label>Heading<input aria-invalid="true" aria-describedby="heading-help"/></label><p id="heading-help">Enter a heading of up to 120 characters.</p></>:state==='Conflict'?<><p role="alert">A newer version exists. Your edits are retained.</p><ContentCompare before={{title:'Saved heading'}} after={{title:'Your unsaved heading'}}/></>:state==='Session expired'?<p role="alert">Your session expired. Keep this tab open and renew sign-in.</p>:state==='Published; verification needed'?<><p role="status">Published; verification needs attention. Your publication is saved.</p><button onClick={()=>setMessage('Fixture retry selected; no public request was made.')}>Retry verification</button></>:state==='Unavailable image'?<figure style={{aspectRatio:'3/2',border:'1px solid currentColor',display:'grid',placeContent:'center',margin:0}}><span role="img" aria-label="Editorial illustration unavailable">Image unavailable</span><figcaption>The caption and next action remain usable.</figcaption></figure>:state==='Long content'?<p>{'A meaningful editorial section remains readable with a long title and detailed paragraphs. '.repeat(14)}</p>:null}
 {state==='Saved preview'&&<><p>The real authorized renderer is used below. An unavailable revision must show a recoverable failure.</p><label>Saved preview record<input value={record} onChange={e=>setRecord(e.target.value)}/></label><label>Saved preview version<input type="number" min={1} value={version} onChange={e=>setVersion(Number(e.target.value))}/></label><button disabled={!Number.isSafeInteger(version)||version<1} onClick={()=>setPreview({record,version,attempt:(preview?.attempt||0)+1})}>Load saved preview</button>{preview&&<div className={s.statePreview}><SavedPreviewFrame key={preview.attempt} revision={preview.version} href={'/studio/preview/frame?'+new URLSearchParams({record:preview.record,version:String(preview.version)})}/></div>}</>}
 </section><p role="status">{message}</p><div className={s.actions}><button className={s.primary} onClick={()=>setMessage('Fixture action selected.')}>Primary action</button><button disabled>Disabled action</button><a className={s.controlLink} href="#main-content">Back to heading</a></div></main></div>;
}
