'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {studioFetch} from './workspace-api';
import {Dialog} from '@/components/shop/dialog';
import s from './workspace.module.css';
type Details={phone:string;email:string;whatsapp:string;map:string};
export function BusinessSettingsEditor(){
 const [editing,setEditing]=useState(false);
 const [data,setData]=useState<{details:Details;version:number}|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[message,setMessage]=useState('');
 async function load(){try{setData(await studioFetch('/api/studio/settings'));setDirty(false);}catch(e){setMessage(e instanceof Error?e.message:'Settings unavailable.');}}
 useEffect(()=>{let active=true;void studioFetch('/api/studio/settings').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function save(){if(!data)return;setBusy(true);try{const saved=await studioFetch('/api/studio/settings',data);setData({...data,version:saved.version});setDirty(false);await load();setConfirm(false);setMessage('Business contact details published. Review any phone numbers or email addresses written inside policy and article copy.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 return <section className={s.panel} data-unsaved={dirty} data-studio-saving={busy}><h2>Public contact details</h2><p className={s.protectedNote}>These are the current business contact references. Keep their factual values unchanged during the redesign.</p><div className={s.actions}><Link href="/contact" target="_blank">View public contact page ↗</Link><Link href="/imprint" target="_blank">Review Imprint copy ↗</Link><Link href="/studio/activity">Saved activity ↗</Link></div>{data&&<p>Saved contact revision {data.version}. Footer, contact links and new WhatsApp handoffs use these settings. Policy and article copy must be reviewed separately.</p>}{data?<form onSubmit={e=>{e.preventDefault();setConfirm(true);}}>{data.version===0&&<p>These approved contact details have not been published yet. Review and publish them before accepting orders.</p>}<div className={s.grid}>{([{key:'phone',label:'Phone with country code',type:'tel'},{key:'whatsapp',label:'WhatsApp number — digits only',type:'text'},{key:'email',label:'Public email',type:'email'},{key:'map',label:'Google Maps link',type:'url'}] as const).map(f=><label key={f.key}>{f.label}<input type={f.type} required readOnly={!editing} disabled={busy} value={data.details[f.key]} maxLength={f.key==='map'?500:180} onChange={e=>{setData({...data,details:{...data.details,[f.key]:e.target.value}});setDirty(true);}}/><button type="button" onClick={()=>{void navigator.clipboard.writeText(data.details[f.key]).then(()=>setMessage(f.label+' copied.')).catch(()=>setMessage('Copy unavailable. Select the displayed value and copy it manually.'));}}>Copy {f.label}</button></label>)}</div><div className={s.actions}>{!editing&&<button type="button" onClick={()=>setEditing(true)}>Open existing contact editing controls</button>}<button disabled={!editing||busy||(!dirty&&data.version>0)}>Review contact details</button><button type="button" disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved contact changes?'))void load();}}>Reload</button></div></form>:<button onClick={()=>void load()}>Load contact details</button>}<p role="status">{message}</p><Dialog open={confirm} title="Publish contact details?" onClose={()=>{if(!busy)setConfirm(false);}}><p>New inquiries will open WhatsApp for {data?.details.whatsapp}. Check that this is the atelier’s correct account.</p><p>{data?.details.phone}<br/>{data?.details.email}</p><div className={s.actions}><button disabled={busy} onClick={()=>setConfirm(false)}>Keep editing</button><button disabled={busy} onClick={()=>void save()}>Publish contact details</button></div></Dialog></section>;
}
