'use client';
import {useEffect,useState} from 'react';
import type {ContentDocument,ContentSection} from '@/lib/content-model';
import {studioFetch} from './workspace-api';
import s from './workspace.module.css';
import {RevisionHistory} from './revision-history';
import type {PublicMedia} from '@/lib/public-media';
import Image from 'next/image';
type Entry={document:ContentDocument;version:number;published:ContentDocument|null;visible:boolean};
export function ContentEditor({admin}:{admin:boolean}){
 const [media,setMedia]=useState<PublicMedia[]>([]);
 const [entries,setEntries]=useState<Entry[]>([]),[entry,setEntry]=useState<Entry|null>(null),[query,setQuery]=useState(''),[message,setMessage]=useState('Loading content…'),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false);
 async function load(id?:string){const data=await studioFetch('/api/studio/content');setEntries(data.entries);if(id)setEntry(data.entries.find((e:Entry)=>e.document.id===id)||null);}
 useEffect(()=>{void studioFetch('/api/studio/media').then(d=>setMedia(d.media.map((e:{media:PublicMedia})=>e.media))).catch(()=>{});void load().then(()=>setMessage('Drafts are shared. Public pages use only a published revision.')).catch(e=>setMessage(e.message));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function choose(next:Entry){if(dirty&&!window.confirm('Discard unsaved edits to this document?'))return;setEntry(structuredClone(next));setDirty(false);setPreview(false);}
 function change(patch:Partial<ContentDocument>){setEntry(e=>e?{...e,document:{...e.document,...patch}}:e);setDirty(true);}
 function section(index:number,patch:Partial<ContentSection>){if(entry)change({sections:entry.document.sections.map((b,i)=>i===index?{...b,...patch}:b)});}
 async function save(operation:'draft'|'publish'|'hide'){
  if(!entry||busy)return;setBusy(true);setMessage('Saving…');
  try{await studioFetch('/api/studio/content',{document:entry.document,version:entry.version,operation});await load(entry.document.id);setDirty(false);setMessage(operation==='publish'?'Published. The website now reads this revision.':operation==='hide'?'Hidden from public pages. The draft is retained.':'Draft saved.');}
  catch(e){setMessage(e instanceof Error?e.message:'Save failed. Your edits remain here.');}finally{setBusy(false);}
 }
 return <><div className={s.heading}><div><h1>Words with purpose.</h1><p>Pages, policies and journal stories, with a clear line between draft and publication.</p></div><button disabled={busy} onClick={()=>choose({version:0,published:null,visible:false,document:{id:'article:'+crypto.randomUUID(),kind:'article',route:'/journal/new-story-'+crypto.randomUUID().slice(0,8),title:'New story',eyebrow:'From the atelier',description:'',sections:[{id:'section-1',heading:'Begin here',paragraphs:['']}]}})}>New article</button></div>
 <p className={s.status} role="status">{message}</p><label>Find content<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <div className={s.layout}><div className={s.list}>{entries.filter(e=>(e.document.title+' '+e.document.route).toLowerCase().includes(query.toLowerCase())).map(e=><button disabled={busy} key={e.document.id} aria-pressed={entry?.document.id===e.document.id} onClick={()=>choose(e)}>{e.document.title}<small>{e.visible&&e.published?'Published':'Unpublished'} · {e.version?'Shared draft':'Source candidate'}</small></button>)}</div>
 {entry?<section data-unsaved={dirty} className={s.editor}><div className={s.toolbar}><button onClick={()=>setPreview(v=>!v)}>{preview?'Return to editing':'Preview draft'}</button>{entry.published&&<a href={entry.document.route} target="_blank" rel="noreferrer">View public revision ↗</a>}<span>Revision {entry.version}{dirty?' · Unsaved edits':''}</span></div>
 {preview?<article className={s.panel}><p>Draft preview · {entry.document.eyebrow}</p><h2>{entry.document.title}</h2><p>{entry.document.description}</p>{entry.document.image&&<Image src={entry.document.image} alt={entry.document.imageAlt||''} width={900} height={600} style={{width:'100%',height:'auto'}}/>}{entry.document.sections.map(b=><section key={b.id}><h3>{b.heading}</h3>{b.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{b.checklist&&<ul>{b.checklist.map((p,i)=><li key={i}>{p}</li>)}</ul>}</section>)}</article>:<form onSubmit={e=>{e.preventDefault();void save('draft');}}><div className={s.grid}>
 <label className={s.wide}>Title<input value={entry.document.title} maxLength={120} required onChange={e=>change({title:e.target.value})}/></label><label>Category / eyebrow<input value={entry.document.eyebrow} maxLength={100} required onChange={e=>change({eyebrow:e.target.value})}/></label><label>Public address<input value={entry.document.route} disabled={entry.version>0||!/^article:[0-9a-f-]{36}$/.test(entry.document.id)} onChange={e=>change({route:e.target.value})}/></label>
 <label className={s.wide}>Introduction & search description<textarea value={entry.document.description} maxLength={300} required onChange={e=>change({description:e.target.value})}/></label>
 <label className={s.wide}>Header image<select value={entry.document.image||''} onChange={e=>change({image:e.target.value||undefined,imageAlt:media.find(m=>m.path===e.target.value)?.alt})}><option value="">No header image</option>{media.map(m=><option key={m.path} value={m.path}>{m.alt}</option>)}</select></label><label className={s.wide}>Related product IDs — separated by commas<input value={entry.document.relatedProductIds?.join(', ')||''} placeholder="DP001, DP013" onChange={e=>change({relatedProductIds:e.target.value?e.target.value.split(',').map(v=>v.trim()).filter(Boolean):undefined})}/><small>Up to six approved catalogue IDs. Only published pieces are linked publicly.</small></label>{entry.document.image&&<label className={s.wide}>Image description<input value={entry.document.imageAlt||''} maxLength={180} required onChange={e=>change({imageAlt:e.target.value})}/></label>}</div>
 {entry.document.sections.map((b,i)=><fieldset className={s.panel} key={b.id}><legend>Section {i+1}</legend><label>Heading<input value={b.heading} maxLength={150} required onChange={e=>section(i,{heading:e.target.value})}/></label><label>Paragraphs — separate with an empty line<textarea rows={8} value={b.paragraphs.join('\n\n')} onChange={e=>section(i,{paragraphs:e.target.value.split(/\n\s*\n/)})}/></label><label>Checklist — one item per line<textarea rows={3} value={b.checklist?.join('\n')||''} onChange={e=>section(i,{checklist:e.target.value?e.target.value.split('\n'):undefined})}/></label><div className={s.actions}><button type="button" disabled={i===0} onClick={()=>{const blocks=[...entry.document.sections];[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];change({sections:blocks});}}>Move up</button><button type="button" disabled={entry.document.sections.length===1} onClick={()=>change({sections:entry.document.sections.filter((_,n)=>n!==i)})}>Remove section</button></div></fieldset>)}
 <button type="button" disabled={entry.document.sections.length>=20} onClick={()=>change({sections:[...entry.document.sections,{id:'section-'+crypto.randomUUID().slice(0,8),heading:'New section',paragraphs:['']}]})}>Add section</button><div className={s.actions}><button className={s.primary} disabled={busy}>Save draft</button>{admin&&<><button type="button" disabled={busy} onClick={()=>void save('publish')}>Publish this revision</button><button type="button" disabled={busy||!entry.visible} onClick={()=>void save('hide')}>Hide public page</button></>}</div></form>}
 <RevisionHistory<ContentDocument> key={entry.document.id+':'+entry.version} kind="content" entityKey={entry.document.id} currentVersion={entry.version} onRestore={change}/>{entry.published&&<details className={s.panel}><summary>Compare saved public content</summary><h3>{entry.published.title}</h3><p>{entry.published.description}</p>{entry.published.sections.map(b=><section key={b.id}><h4>{b.heading}</h4>{b.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}</details>}
 </section>:<p className={s.empty}>Select a page or article. Source candidates are not published automatically.</p>}</div></>;
}
