'use client';
import {useEffect,useState} from 'react';
import {usePathname,useSearchParams} from 'next/navigation';
import {studioFetch} from './workspace-api';
import {useUnsavedWork} from './use-unsaved-work';
import s from './workspace.module.css';
type Row={id:string;kind:string;title:string;topic:string;journey:string;state:string;candidateMedia?:string|null;newRecordId:string|null;authoredRecordId?:string;stagedVersion?:number|null;localEditorAvailable?:boolean;deliveryContentDriveId?:string|null;nextStep?:string;meaningReview:string;nativeReview:string;publication:string};
type Register={entries:Row[];total:number;page:number;totalPages:number;created:number;planned:number;authored:number;localStaged:number;driveDelivered:number};
type Check={token:string;expires:number;records:{id:string;title:string;route:string;publicationIssues:string[]}[]};
export function ContentRegister(){
 const params=useSearchParams(),path=usePathname(),key=params.toString();
 const [data,setData]=useState<Register|null>(null),[message,setMessage]=useState('Loading the production register…'),[input,setInput]=useState(''),[checked,setChecked]=useState<Check|null>(null),[busy,setBusy]=useState(false);
 useUnsavedWork(!!input);
 useEffect(()=>{let active=true;void studioFetch('/api/studio/content-register?'+key).then(d=>{if(active){setData(d);setMessage('Authored drafts, recorded local staging, Drive delivery and production links are counted separately. Human approval and publication remain separate.');}}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[key]);
 function navigate(values:Record<string,string>){const p=new URLSearchParams(params);for(const [k,v] of Object.entries(values))if(v)p.set(k,v);else p.delete(k);window.history.pushState(null,'',path+'?'+p);}
 async function intake(mode:'dry-run'|'create'){
  if(busy)return;setBusy(true);
  try{const documents=JSON.parse(input),result=await studioFetch('/api/studio/content-intake',{mode,documents,...(mode==='create'?{token:checked?.token,expires:checked?.expires}:{})});if(mode==='dry-run'){setChecked(result);setMessage('Dry run complete. Review every new identity and publication issue below. Nothing is saved.');}else{setChecked(null);setInput('');setMessage(result.ids.length+' unpublished drafts created. Open them in the library to review and preview.');}}
  catch(e){setMessage((e as Error).message);setChecked(null);}finally{setBusy(false);}
 }
 return <section data-unsaved={!!input} data-studio-saving={busy}><header className={s.heading}><div><h1>Editorial production register</h1><p>120 entries each for Journal, Portfolio, Testimonials and FAQs.</p></div></header><p role="status" className={s.status}>{message}</p><p>{data?data.authored:"Loading…"} authored drafts · {data?data.localStaged:'Loading…'} recorded local Studio drafts · {data?data.driveDelivered:'Loading…'} Drive deliveries</p><p>{data?.created||0} / {data?.planned||480} production records linked. Concepts and fictional samples must stay labelled; genuine claims require approved evidence.</p><form key={key} className={s.toolbar} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);navigate({q:String(f.get('q')||''),kind:String(f.get('kind')||''),page:'1'});}}><label>Find an entry<input name="q" type="search" maxLength={100} defaultValue={params.get('q')||''}/></label><label>Section<select name="kind" defaultValue={params.get('kind')||''}><option value="">All sections</option>{['Journal','Portfolio','Testimonials','FAQs'].map(kind=><option key={kind}>{kind}</option>)}</select></label><button>Apply register filters</button><button type="button" onClick={()=>navigate({q:'',kind:'',page:'1'})}>Clear filters</button></form><p>{data?.total||0} matching entries</p><div className={s.libraryRows}>{data?.entries.map(row=><article className={s.panel} key={row.id}><h2>{row.id} · {row.title}</h2><p>{row.kind} · {row.topic} · {row.journey}</p><p>{row.state} · {row.publication}</p><p>Meaning review: {row.meaningReview} · Native review: {row.nativeReview}</p>{row.localEditorAvailable&&row.authoredRecordId&&<p><a href={'/studio/'+({Journal:'journal',Portfolio:'portfolio',Testimonials:'testimonials',FAQs:'faqs'}[row.kind]||'site-copy')+'?record='+encodeURIComponent(row.authoredRecordId)}>Open local draft · staged revision {row.stagedVersion}</a></p>}{row.deliveryContentDriveId&&<p><a href={'https://drive.google.com/file/d/'+row.deliveryContentDriveId+'/view'} target="_blank" rel="noreferrer">Open Drive draft bundle</a></p>}<details><summary>Production requirements</summary><p>{row.nextStep}</p><p>Media candidate: {row.candidateMedia||'Not selected'} · Studio identity: {row.newRecordId||'Not created'}</p></details></article>)}</div><div className={s.actions}><button disabled={!data||data.page===1} onClick={()=>navigate({page:String(data!.page-1)})}>Previous page</button><span>Page {data?.page||1} of {data?.totalPages||1}</span><button disabled={!data||data.page>=data.totalPages} onClick={()=>navigate({page:String(data!.page+1)})}>Next page</button></div>
 <details className={s.panel}><summary>New draft intake · dry run required</summary><p>Paste an array of 1–10 new editorial documents. Existing IDs, addresses, matching titles and protected snapshots are rejected. A checked batch creates unpublished drafts only. Complete each record’s evidence and preview before any separate publication.</p><label>New draft JSON<textarea rows={8} maxLength={180000} value={input} disabled={busy} onChange={e=>{setInput(e.target.value);setChecked(null);}}/></label><button disabled={busy||!input} onClick={()=>void intake('dry-run')}>Check new drafts without saving</button>{checked&&<div><h2>Checked new identities</h2>{checked.records.map(row=><p key={row.id}><strong>{row.title}</strong> · {row.id} · {row.route}<br/>{row.publicationIssues.join(' ')||'No current evidence blocker identified; publication still needs its separate saved preview.'}</p>)}<button disabled={busy} onClick={()=>void intake('create')}>Create these checked unpublished drafts</button></div>}</details></section>;
}
