'use client';
import {ContentBlockers} from './content-blockers';
import {contentIssues} from '@/lib/content-issues';
import dynamic from 'next/dynamic';
import {ContentCompare} from './content-compare';
import {SectionBody} from '../shop/section-body';
import {sharedCopyId} from '@/lib/shared-copy-model';
import {editorialDocument} from '@/lib/page-dependencies';
import {useRecordSwitch,RecordSwitchNotice} from './record-switch';
import {RecordStatus} from './record-status';
import {DraftRecovery} from './draft-recovery';
import {useLinkedRecord,LinkedRecordNotice} from './linked-record';
import {publicationState,draftState} from '@/lib/content-health';
import {contentListDraftState} from '@/lib/content-list-document';
import {useEffect,useState} from 'react';
import {usePagination,Pagination} from './pagination';
import {editorialAreaLabels,inEditorialArea,newEditorialDocument,type EditorialArea} from '@/lib/editorial-workspaces';
import {EditorialRecordFields} from './editorial-record-fields';
const LandingEditor=dynamic(()=>import('./landing-editor').then(m=>m.LandingEditor),{loading:()=> <p role="status">Opening block editor…</p>});
import {useSearchParams} from 'next/navigation';
import type {ContentDocument} from '@/lib/content-model';
import {TranslationEditor} from './translation-editor';
import {studioFetch,StudioRequestError} from './workspace-api';
import s from './workspace.module.css';
import {RevisionHistory} from './revision-history';
import type {PublicMedia} from '@/lib/public-media';
import Image from 'next/image';
import {previewHref} from '@/lib/homepage-model';
import {HomepageEditor} from './homepage-editor';
const PageSectionsEditor=dynamic(()=>import('./page-sections-editor').then(m=>m.PageSectionsEditor),{loading:()=> <p role="status">Opening section editor…</p>});
type Entry={document:ContentDocument;version:number;publishedVersion?:number;published:ContentDocument|null;visible:boolean;reviewed?:ContentDocument;detailPending?:boolean;draftStatus?:ReturnType<typeof draftState>};
export function ContentEditor({admin,initialKind='all',initialRecord,initialHomeSection,area='all',title}:{admin:boolean;initialKind?:'all'|'page'|'article';initialRecord?:string;initialHomeSection?:string;area?:EditorialArea|'all';title?:string}){
 const searchParams=useSearchParams();
 const [createRequested]=useState(()=>searchParams.get('create')==='1');
 const [initialSelection]=useState(()=>initialRecord||searchParams.get('record')||'');
 const [latest,setLatest]=useState<Entry|null>(null),[verification,setVerification]=useState('');
 const [loaded,setLoaded]=useState(false),[restoredFrom,setRestoredFrom]=useState<number|undefined>();
 const [media,setMedia]=useState<PublicMedia[]>([]),[kindFilter,setKindFilter]=useState<'all'|'page'|'article'>(initialKind);
 const [entries,setEntries]=useState<Entry[]>([]),[entry,setEntry]=useState<Entry|null>(null),[query,setQuery]=useState(''),[message,setMessage]=useState('Loading content…'),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false);
 async function load(id?:string){const data=await studioFetch('/api/studio/content?view=editor'+(id?'&record='+encodeURIComponent(id):''));const next=id?data.entries.find((e:Entry)=>e.document.id===id):null;if(id&&!next)throw Error('Saved page is unavailable. Your local draft is retained.');setEntries(data.entries);setLoaded(true);if(next)setEntry(next);setVerification('');setMessage('Latest saved draft loaded. Your public page is unchanged.');}
 useEffect(()=>{let active=true;void Promise.all([studioFetch('/api/studio/media'),studioFetch('/api/studio/editorial-assets')]).then(([d,e])=>{if(active)setMedia([...d.media,...e.media].filter((e:{published:PublicMedia|null})=>e.published).map((e:{published:PublicMedia})=>e.published));}).catch(()=>{});void studioFetch('/api/studio/content?view=editor'+(initialSelection?'&record='+encodeURIComponent(initialSelection):'')).then(data=>{if(active){setEntries(data.entries);if(createRequested&&area!=='all'&&!initialSelection){setEntry({version:0,published:null,visible:false,document:newEditorialDocument(area,crypto.randomUUID())});setDirty(true);}if(initialSelection)setEntry(data.entries.find((e:Entry)=>e.document.id===initialSelection&&inEditorialArea(area,e.document))||null);setLoaded(true);setMessage('Drafts are shared. Public pages use only a published revision.');}}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[initialSelection,area,createRequested]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const [repairBlock,setRepairBlock]=useState('');
 const [homeSection,setHomeSection]=useState(initialHomeSection||'hero');
 const switching=useRecordSwitch(dirty);
 function choose(next:Entry){if(busy||(initialRecord&&next.document.id!==initialRecord)||!inEditorialArea(area,next.document))return false;if(next.document.id===entry?.document.id)return true;return switching.request(()=>{const apply=(full:Entry)=>{setEntry(structuredClone(full));setDirty(full.version===0);setPreview(false);setRestoredFrom(undefined);setLatest(null);setVerification('');setMessage('Editing '+full.document.title+'. Saving a draft leaves the public page unchanged.');};if(!next.detailPending){apply(next);return;}const previous=entry;setBusy(true);setEntry(null);setMessage('Loading the exact saved record…');void studioFetch('/api/studio/content?record='+encodeURIComponent(next.document.id)).then(data=>{const full=data.entries.find((e:Entry)=>e.document.id===next.document.id);if(!full)throw new Error('This content record is unavailable.');apply(full);}).catch(e=>{setEntry(previous);setMessage(e.message);}).finally(()=>setBusy(false));});}
 function change(patch:Partial<ContentDocument>){setEntry(e=>e?{...e,document:{...e.document,...patch}}:e);setDirty(true);}

 async function verify(target:Entry){
  if(!target.published||!target.visible)return;
  setVerification('Checking the anonymous public page…');
  try{const route=target.document.id===sharedCopyId?'/':target.document.route;const response=await fetch(route+'?verify='+target.publishedVersion+'&t='+Date.now(),{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(15000)});const html=new DOMParser().parseFromString(await response.text(),'text/html');const marker=target.document.id===sharedCopyId?'data-site-copy-revision':'data-content-revision';const page=html.querySelector('['+marker+'="'+target.publishedVersion+'"]');if(!response.ok||!page||(target.document.id!==sharedCopyId&&page.querySelector('h1')?.textContent!==target.published.title))throw Error();setVerification('Published and verified: anonymous public revision '+target.publishedVersion+'.');}catch{setVerification('Published; verification needs attention. Your publication is saved. Retry verification without publishing again.');}
 }
 async function save(operation:'draft'|'publish'|'hide'){
  if(!entry||busy)return;setBusy(true);setMessage('Saving…');
  try{const result=await studioFetch('/api/studio/content',{document:editorialDocument(entry.document),version:entry.version,operation,...(operation==='draft'&&restoredFrom?{restoredFrom}:{})});const next={...entry,document:result.document,version:result.version,publishedVersion:result.publishedVersion,...(operation==='publish'?{published:result.document,visible:true}:operation==='hide'?{visible:false}:{})};setEntry(next);setEntries(rows=>rows.some(e=>e.document.id===next.document.id)?rows.map(e=>e.document.id===next.document.id?next:e):[...rows,next]);setDirty(false);setRestoredFrom(undefined);setLatest(null);setMessage(operation==='publish'?'Publication committed as revision '+result.version+'.':operation==='hide'?'Hidden from public pages. The draft is retained.':'Draft saved. Your public page is unchanged.');if(operation==='publish')await verify(next);}
  catch(e){setMessage(e instanceof Error?e.message:'Save failed. Your edits remain here.');if(e instanceof StudioRequestError&&e.status===409){try{const data=await studioFetch('/api/studio/content?record='+encodeURIComponent(entry.document.id));setLatest(data.entries.find((v:Entry)=>v.document.id===entry.document.id)||null);}catch{/* Local work stays intact. */}}}finally{setBusy(false);}
 }
 const linked=useLinkedRecord({editor:'content',records:entries.filter(e=>(!initialRecord||e.document.id===initialRecord)&&inEditorialArea(area,e.document)),loaded,selectedId:entry?.document.id,idOf:e=>e.document.id,busy,onSelect:(next,target)=>{if(!choose(next))return false;if(target.field.startsWith('block-'))setRepairBlock(target.field.slice(6));setHomeSection(target.field.startsWith('section-')?target.field.slice(8):'hero');setQuery('');setKindFilter('all');return true;}});
 const filteredEntries=entries.filter(e=>(!initialRecord||e.document.id===initialRecord)&&inEditorialArea(area,e.document)&&(kindFilter==='all'||e.document.kind===kindFilter)&&(e.document.title+' '+e.document.route+' '+e.document.eyebrow+' '+e.document.sections.map(b=>b.heading+' '+b.group).join(' ')).toLowerCase().includes(query.toLowerCase()));
 const {page,totalPages,setPage,paginatedItems}=usePagination(filteredEntries,25);
 const create=(kind:EditorialArea)=>{if(choose({version:0,published:null,visible:false,document:newEditorialDocument(kind,crypto.randomUUID())}))setDirty(true);};
 return <><div className={s.heading}><div><h1>{title||(area==='all'?'Words with purpose.':editorialAreaLabels[area]+'.')}</h1><p>Exact saved drafts, source requirements and deliberate publication. Existing records stay unchanged until you save.</p></div>{!initialRecord&&(area==='all'?<><button disabled={busy} onClick={()=>create('journal')}>New article</button><button disabled={busy} onClick={()=>create('pages')}>New custom page</button></>:<button disabled={busy} onClick={()=>create(area)}>New {{journal:'article',portfolio:'portfolio story',testimonials:'testimonial',faqs:'FAQ',pages:'page','landing-pages':'landing page'}[area]}</button>)}</div>
 <p className={s.status} role="status">{message}</p>{!loaded&&message!=='Loading content…'&&<button onClick={()=>void load(initialSelection||undefined).catch(e=>setMessage(e.message))}>Retry content records</button>}<LinkedRecordNotice {...linked}/><RecordSwitchNotice control={switching}/><div className={s.toolbar}><label>Find content<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Title, route or section…" /></label>{area==='all'&&!initialRecord&&<label>Content type<select value={kindFilter} onChange={e=>setKindFilter(e.target.value as 'all'|'page'|'article')}><option value="all">Pages & journal</option><option value="page">Pages & site copy</option><option value="article">Journal articles</option></select></label>}<span role="status">{loaded?filteredEntries.length+(filteredEntries.length===1?' document':' documents'):'Loading records…'}</span></div>
 <div className={s.layout}><div className={s.list}>{paginatedItems.map(e=><button disabled={busy} key={e.document.id} aria-pressed={entry?.document.id===e.document.id} onClick={()=>choose(e)}>{e.document.id==='page:home'?'Homepage':e.document.title}<small>{e.document.route} · Revision {e.version} · {publicationState(e.published,e.visible)} · {contentListDraftState(e)} · {e.document.editorial?.kind|| (e.document.landing?'Landing page':e.document.kind==='page'?'Page copy':'Journal')}</small></button>)}<Pagination page={page} totalPages={totalPages} setPage={setPage}/>{loaded&&!filteredEntries.length&&<p className={s.empty}>No content matches this search and type.</p>}</div>
 {entry?.document.homepage?<HomepageEditor key={entry.document.id+':'+homeSection} entry={entry} admin={admin} dirty={dirty} initialSection={homeSection} onBusy={setBusy} onChange={document=>{setEntry({...entry,document});setDirty(true);}} onSaved={next=>{setEntry(next);setEntries(current=>current.map(e=>e.document.id===next.document.id?next:e));setDirty(false);}}/>:entry?<section data-unsaved={dirty} className={s.editor}><fieldset disabled={busy}><RecordStatus id={entry.document.id} version={entry.version} publication={publicationState(entry.published,entry.visible)} draft={draftState(entry.document,entry.published,entry.version)} dirty={dirty} busy={busy}/><ContentBlockers document={entry.document} dirty={dirty} onRepair={field=>{setPreview(false);if(field.startsWith('block-'))setRepairBlock(field.slice(6));setHomeSection(field.startsWith('section-')?field.slice(8):'hero');}}/>{verification&&<div className={s.panel}><p role="status">{verification}</p><button type="button" onClick={()=>void verify(entry)}>Retry public verification</button></div>}{latest&&<details open className={s.panel}><summary>A newer version exists — your edits are retained</summary><ContentCompare before={latest.document} after={entry.document}/></details>}<p className={s.help}>{!entry.document.pageSnapshot&&entry.version>0?'Save this historical draft again to capture its references before publication. ':''}{publicationState(entry.published,entry.visible)} · {draftState(entry.document,entry.published,entry.version)}. Saving a draft does not publish it.</p><div className={s.toolbar}>{(entry.version>0&&!dirty?<a href={previewHref(entry.document.id,entry.version)} target="_blank" rel="noreferrer">Preview saved page ↗</a>:<span>Save the draft to preview the website page.</span>)}<button onClick={()=>setPreview(v=>!v)}>{preview?'Return to editing':'Review local text'}</button>{entry.published&&entry.visible&&<a href={entry.document.id===sharedCopyId?'/':entry.document.route} target="_blank" rel="noreferrer">View public revision ↗</a>}<span>Draft revision {entry.version} · Public {entry.publishedVersion||'not published'}{dirty?' · Unsaved edits':''}</span></div>
 {preview?<article className={s.panel}><p>Local text review · {entry.document.eyebrow}. Save the draft and open Preview saved page to check the website layout.</p><h2>{entry.document.title}</h2><p>{entry.document.description}</p>{entry.document.image&&<Image src={entry.document.image} alt={entry.document.imageAlt||''} width={900} height={600} style={{width:'100%',height:'auto'}}/>}{entry.document.sections.map(b=><section key={b.id}><h3>{b.heading}</h3><SectionBody section={b}/></section>)}</article>:<form onSubmit={e=>{e.preventDefault();void save('draft');}}>{entry.document.id!==sharedCopyId&&<div className={s.grid}>
 <label className={s.wide}>Title<input id="content-field-title" value={entry.document.title} maxLength={120} required onChange={e=>change({title:e.target.value})}/></label><label>Category / eyebrow<input id="content-field-eyebrow" value={entry.document.eyebrow} maxLength={100} required onChange={e=>change({eyebrow:e.target.value})}/></label><label>Public address<input value={entry.document.route} disabled={entry.version>0||!/^(?:article|custom-page|editorial):[0-9a-f-]{36}$/.test(entry.document.id)} onChange={e=>change({route:e.target.value})}/></label>
 {entry.document.route==='/journal'&&<label className={s.wide}>Featured journal story<select value={entry.document.featuredArticleIds?.[0]||''} onChange={e=>change({featuredArticleIds:e.target.value?[e.target.value]:[]})}><option value="">No featured story</option>{entry.document.featuredArticleIds?.[0]&&!entries.some(e=>e.document.id===entry.document.featuredArticleIds?.[0]&&e.visible&&e.published)&&<option value={entry.document.featuredArticleIds[0]}>Unavailable saved selection — choose a published story</option>}{entries.filter(e=>e.document.kind==='article'&&e.visible&&e.published).map(e=><option key={e.document.id} value={e.document.id}>{e.published!.title} · {e.document.id}</option>)}</select><small>Choose a currently published story. An unavailable record blocks publication.</small></label>}
 <label className={s.wide}>Introduction & search description<textarea id="content-field-description" value={entry.document.description} maxLength={300} required onChange={e=>change({description:e.target.value})}/></label>
 {entry.document.editorial?.kind!=='testimonial'&&!entry.document.landing&&<><p className={s.wide}><a href={'/studio/site-images?record='+encodeURIComponent(entry.document.id)+'&slot=header'}>Edit independent header image and desktop/mobile crops ↗</a>{entry.document.headerImage&&' · An editorial header override is active. Changing the fallback below clears it.'}</p><label className={s.wide}>Header image fallback<select id="content-field-image" value={entry.document.image||''} onChange={e=>change({headerImage:undefined,image:e.target.value||undefined,imageAlt:media.find(m=>m.path===e.target.value)?.alt})}><option value="">No header image</option>{media.map(m=><option key={m.path} value={m.path}>{m.alt}</option>)}</select></label><label className={s.wide}>Related product IDs — separated by commas<input id="content-field-relatedProductIds" value={entry.document.relatedProductIds?.join(', ')||''} placeholder="DP001, DP013" onChange={e=>change({relatedProductIds:e.target.value?e.target.value.split(',').map(v=>v.trim()).filter(Boolean):undefined})}/><small>Up to six approved catalogue IDs. Only published pieces are linked publicly.</small></label>{entry.document.image&&<label className={s.wide}>Image description<input id="content-field-imageAlt" value={entry.document.imageAlt||''} maxLength={180} required onChange={e=>change({imageAlt:e.target.value})}/></label>}</>}<label>Effective date (only when verified)<input type="date" value={entry.document.effectiveDate||''} onChange={e=>change({effectiveDate:e.target.value||undefined})}/></label></div>}
 <EditorialRecordFields document={entry.document} media={media} onChange={change}/>{entry.document.landing?<LandingEditor key={entry.document.id+':'+repairBlock} initialBlock={repairBlock} document={entry.document} media={media} onChange={change}/>:<PageSectionsEditor key={entry.document.id+':'+homeSection} document={entry.document} initialSection={homeSection} onChange={change} media={media}/>}
 <TranslationEditor key={entry.document.id} document={entry.document} onChange={change} version={entry.version} dirty={dirty}/>
 <div className={s.actions}><button className={s.primary} disabled={busy}>Save draft</button>{admin&&<><button type="button" disabled={busy||dirty||entry.version<1||!entry.document.pageSnapshot||!!entry.document.pageSnapshot?.issues.length||contentIssues(entry.document).length>0} onClick={()=>void save('publish')}>Publish this revision</button><button type="button" disabled={busy||dirty||!entry.visible} onClick={()=>void save('hide')}>Hide public page</button></>}</div></form>}
 {entry.reviewed&&<details className={s.panel}><summary>Review the updated website copy</summary><p>This proposed copy is separate from your saved draft. Review any later business changes before using it. Nothing is saved or published by this action.</p><h3>{entry.reviewed.title}</h3><p>{entry.reviewed.description}</p>{entry.reviewed.sections.map(b=><section key={b.id}><h4>{b.heading}</h4>{b.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}<button type="button" onClick={()=>{if(entry.reviewed&&window.confirm('Replace the editor contents with the reviewed copy? Your current saved and published revisions stay unchanged until you save or publish.')){change(structuredClone(entry.reviewed));setMessage('Reviewed copy is in the editor. Check it, then save a draft when ready.');}}}>Use reviewed copy in this draft</button></details>}
 <RevisionHistory<ContentDocument> key={entry.document.id+':'+entry.version} kind="content" entityKey={entry.document.id} currentVersion={entry.version} currentDocument={entry.document} onRestore={(document,version)=>{change(document);setRestoredFrom(version);}}/>{entry.published&&<details className={s.panel}><summary>Compare saved public content</summary><ContentCompare before={entry.published} after={entry.document}/><h3>{entry.published.title}</h3><p>{entry.published.description}</p>{entry.published.sections.map(b=><section key={b.id}><h4>{b.heading}</h4>{b.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}</details>}
 <DraftRecovery value={entry.document} busy={busy} onReload={async()=>{setBusy(true);try{await load(entry.document.id);setDirty(false);setRestoredFrom(undefined);setLatest(null);}finally{setBusy(false);}}}/></fieldset></section>:<p className={s.empty}>{loaded?'Select a record. Source candidates are not published automatically.':'Loading saved content…'}</p>}</div></>;
}
