'use client';
import {bodyFromParagraphs,bodyParagraphs,type EditorialBody,type TextBlock} from '@/lib/editorial-body';
import type {ContentSection} from '@/lib/content-model';
import {SectionBody} from '../shop/section-body';
import s from './workspace.module.css';
/** Small explicit editor: semantic blocks and spans, never a raw HTML input. */
export function EditorialBodyEditor({section,onChange}:{section:ContentSection;onChange:(patch:Partial<ContentSection>)=>void}){
 const body=section.body;
 const update=(value:EditorialBody)=>onChange({body:value,paragraphs:bodyParagraphs(value)});
 const block=(id:string,patch:Partial<TextBlock>)=>body&&update({...body,blocks:body.blocks.map(b=>b.id===id?{...b,...patch}:b)});
 if(!body)return <><label>Paragraphs — separate with an empty line<textarea rows={7} value={section.paragraphs.join('\n\n')} onChange={e=>onChange({paragraphs:e.target.value.split(/\n\s*\n/)})}/></label><button type="button" onClick={()=>update(bodyFromParagraphs(section.paragraphs.length?section.paragraphs:['']))}>Add formatting and links</button></>;
 return <fieldset className={s.panel}><legend>Formatted content</legend><p className={s.help}>Each text span can have emphasis or an internal link. Quotes need a genuine source; this editor does not approve a factual claim.</p>{body.blocks.map((b,i)=><fieldset className={s.panel} key={b.id}><legend>Block {i+1}</legend><label>Block style<select value={b.kind} onChange={e=>block(b.id,{kind:e.target.value as TextBlock['kind'],attribution:undefined})}><option value="paragraph">Paragraph</option><option value="quote">Quote</option></select></label>{b.runs.map((r,n)=><div className={s.panel} key={n}><label>Text {n+1}<textarea maxLength={2500} value={r.text} onChange={e=>block(b.id,{runs:b.runs.map((v,j)=>j===n?{...v,text:e.target.value}:v)})}/></label><div className={s.actions}>{(['bold','italic'] as const).map(mark=><label key={mark} className={s.check}><input type="checkbox" checked={!!r[mark]} onChange={e=>block(b.id,{runs:b.runs.map((v,j)=>j===n?{...v,[mark]:e.target.checked}:v)})}/>{mark}</label>)}</div><label>Internal link (optional)<input placeholder="/materials-care#care" value={r.href||''} onChange={e=>block(b.id,{runs:b.runs.map((v,j)=>j===n?{...v,href:e.target.value||undefined}:v)})}/></label><button type="button" disabled={b.runs.length===1} onClick={()=>block(b.id,{runs:b.runs.filter((_,j)=>j!==n)})}>Remove text span {n+1}</button></div>)}<button type="button" disabled={b.runs.length>=30} onClick={()=>block(b.id,{runs:[...b.runs,{text:''}]})}>Add text span</button>{b.kind==='quote'&&<label>Attribution (only if verified)<input maxLength={180} value={b.attribution||''} onChange={e=>block(b.id,{attribution:e.target.value||undefined})}/></label>}<div className={s.actions}><button type="button" disabled={i===0} onClick={()=>{const blocks=[...body.blocks];[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];update({...body,blocks});}}>Move block up</button><button type="button" disabled={i===body.blocks.length-1} onClick={()=>{const blocks=[...body.blocks];[blocks[i+1],blocks[i]]=[blocks[i],blocks[i+1]];update({...body,blocks});}}>Move block down</button><button type="button" disabled={body.blocks.length===1} onClick={()=>update({...body,blocks:body.blocks.filter(v=>v.id!==b.id)})}>Remove block</button></div></fieldset>)}<button type="button" disabled={body.blocks.length>=12} onClick={()=>update({...body,blocks:[...body.blocks,{id:'text-'+crypto.randomUUID().slice(0,8),kind:'paragraph',runs:[{text:''}]}]})}>Add paragraph</button><details><summary>Formatted text preview</summary><SectionBody section={section}/></details></fieldset>;
}
