'use client';
import {useState} from 'react';
import type {ContentDocument} from '@/lib/content-model';
import {reviewRevision,reviewState,type EditorialReview,type DiscoveryMetadata} from '@/lib/editorial-metadata';
import s from './workspace.module.css';
export function EditorialMetadataFields({document:d,onChange}:{document:ContentDocument;onChange:(patch:Partial<ContentDocument>)=>void}){
 const [locale,setLocale]=useState<'en'|'hi'|'gu'>('en'),[kind,setKind]=useState<'author'|'meaning'|'native'>('author'),[reviewer,setReviewer]=useState(''),[date,setDate]=useState(''),[evidence,setEvidence]=useState('');
 const meta=(patch:Partial<DiscoveryMetadata>)=>onChange({discovery:{...d.discovery,...patch}}),review=(patch:Partial<EditorialReview>)=>onChange({review:{...d.review,...patch}});
 const recorded=[{label:'Author',value:d.review?.authorReview},...(['en','hi','gu'] as const).flatMap(language=>[{label:`Meaning (${language})`,value:d.review?.meaning?.[language]},{label:`Native reader (${language})`,value:d.review?.native?.[language]}])].filter(entry=>entry.value);
 return <details className={s.panel}><summary>Discovery metadata & review evidence</summary><p>Use only known metadata. Existing category labels stay as entered. Empty values appear as Unclassified. Review evidence stays private; publishing does not certify native-language approval.</p><div className={s.grid}>
 {(['journey','format','context'] as const).map(key=><label key={key}>{key==='journey'?'Journey':key==='format'?'Content format':'Room / context'}<input maxLength={80} value={d.discovery?.[key]||''} onChange={e=>meta({[key]:e.target.value||undefined})}/></label>)}
 {(['tags','materials','linkedRecordIds'] as const).map(key=><label key={key}>{key==='tags'?'Tags':key==='materials'?'Confirmed materials':'Related content IDs'}<input maxLength={1200} value={d.discovery?.[key]?.join(', ')||''} onChange={e=>meta({[key]:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/><small>Up to 12 values, separated by commas. Record only established facts.</small></label>)}
 <label>Author (when known)<input maxLength={150} value={d.review?.author||''} onChange={e=>review({author:e.target.value||undefined})}/></label><label>Private source / policy note<textarea maxLength={1500} value={d.review?.source||''} onChange={e=>review({source:e.target.value||undefined})}/></label><label>Possible duplicate of record ID<input maxLength={150} value={d.review?.duplicateOf||''} onChange={e=>review({duplicateOf:e.target.value||undefined})}/></label><label>Last fact verification date<input type="date" value={d.review?.lastVerified||''} onChange={e=>review({lastVerified:e.target.value||undefined})}/></label></div>
 <h3>Recorded evidence</h3>{recorded.length?<dl>{recorded.map(({label,value})=><div key={label}><dt>{label}</dt><dd>{value!.reviewer} · {value!.date}<p>{value!.evidence}</p><small>Reviewed text fingerprint: {value!.revision}. Check the current review state below.</small></dd></div>)}</dl>:<p>No review evidence has been recorded.</p>}
 <h3>Record an actual review</h3><p>Author: {reviewState(d,'author')} · Meaning ({locale}): {reviewState(d,'meaning',locale)} · Native reader ({locale}): {reviewState(d,'native',locale)}</p><p>A completed translation field check is separate from a named native reader’s evidence. Record who reviewed the current text, when and where the evidence can be found.</p><div className={s.grid}><label>Review type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="author">Author review</option><option value="meaning">Meaning review</option><option value="native">Native-reader review</option></select></label><label>Review language<select value={locale} disabled={kind==='author'} onChange={e=>setLocale(e.target.value as typeof locale)}><option value="en">English</option><option value="hi">Hindi</option><option value="gu">Gujarati</option></select></label><label>Actual reviewer<input maxLength={150} value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label>Date of review<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Evidence location / review note<textarea maxLength={1500} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label></div><button type="button" disabled={!reviewer.trim()||!date||!evidence.trim()} onClick={()=>{const record={reviewer,date,evidence,revision:reviewRevision(d,kind==='author'?'en':locale)};review(kind==='author'?{authorReview:record}:{[kind]:{...d.review?.[kind],[locale]:record}});setReviewer('');setDate('');setEvidence('');}}>Add evidence to unsaved draft</button></details>;
}
