'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {editorialAreaLabels,type EditorialArea} from '@/lib/editorial-workspaces';
import type {ContentDocument} from '@/lib/content-model';
import {studioFetch} from './workspace-api';
import s from './workspace.module.css';
const ContentEditor=dynamic(()=>import('./content-editor').then(m=>m.ContentEditor),{loading:()=> <p role="status">Opening the saved editor…</p>});
const filters=['q','status','review','source','missing','topic','journey','locale','author','from','to','sort'] as const;
type Results={entries:{document:ContentDocument;version:number;visible:boolean;published:unknown;draftStatus:string}[];total:number;page:number;totalPages:number;facets:{topics:string[];journeys:string[];authors:string[]}};
export function EditorialLibrary({admin,area='all'}:{admin:boolean;area?:EditorialArea|'all'}){
 const params=useSearchParams(),path=usePathname(),requested=params.get('record')||'',requestedCreate=params.get('create')==='1';
 const [selection,setSelection]=useState({record:requested,create:requestedCreate}),[guardMessage,setGuardMessage]=useState('');
 const record=selection.record,create=selection.create,allowLeave=useRef(false),accepted=useRef(path+'?'+params.toString());
 useEffect(()=>{void Promise.resolve().then(()=>{if(record!==requested||create!==requestedCreate){if(!allowLeave.current&&document.querySelector('[data-unsaved="true"],[data-studio-saving="true"]')){window.history.replaceState(null,'',accepted.current);setGuardMessage('Your unsaved draft was kept. Use Return to filtered records to review leaving it.');return;}allowLeave.current=false;setSelection({record:requested,create:requestedCreate});setGuardMessage('');}accepted.current=path+'?'+params.toString();});},[requested,requestedCreate,record,create,path,params]);
 const key=params.toString(),[data,setData]=useState<Results|null>(null),[message,setMessage]=useState('Loading saved summaries…'),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[reload,setReload]=useState(0);
 const listParams=new URLSearchParams(key);listParams.delete('record');listParams.delete('create');const back=path+(listParams.size?'?'+listParams:'');
 useEffect(()=>{if(record||create)return;let active=true;const p=new URLSearchParams(key);p.set('area',area);void Promise.resolve().then(()=>{if(active){setLoading(true);setFailed(false);}return studioFetch('/api/studio/content-list?'+p);}).then((d:Results)=>{if(active){setData(d);setLoading(false);setMessage('Showing '+d.entries.length+' of '+d.total+' matching records. Full drafts open on demand.');}}).catch(e=>{if(active){setMessage(e.message);setData(null);setFailed(true);setLoading(false);}});return()=>{active=false;};},[key,area,record,create,reload]);
 function navigate(patch:Record<string,string>){const next=new URLSearchParams(params);for(const [k,v] of Object.entries(patch))if(v)next.set(k,v);else next.delete(k);setLoading(true);setReload(value=>value+1);window.history.pushState(null,'',path+(next.size?'?'+next:''));}
 const href=(id:string)=>{const p=new URLSearchParams(listParams);p.set('record',id);return path+'?'+p;};
 if(record||create)return <><Link href={back} onClick={e=>{if(document.querySelector('[data-studio-saving="true"]')||document.querySelector('[data-unsaved="true"]')&&!window.confirm('Leave this record and discard unsaved edits?')){e.preventDefault();return;}allowLeave.current=true;}}>← Return to filtered records</Link>{guardMessage&&<p role="status">{guardMessage}</p>}<ContentEditor key={record||'new'} admin={admin} area={area} initialRecord={record||undefined} detailOnly/></>;
 const select=(name:typeof filters[number],label:string,options:{value:string;label:string}[])=> <label>{label}<select name={name} defaultValue={params.get(name)||''}><option value="">All</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 const opts=(values:string[])=>values.map(value=>({value,label:value}));
 return <section><header className={s.heading}><div><h1>{area==='all'?'Editorial library':editorialAreaLabels[area]}</h1><p>Find drafts and published records using their saved metadata.</p></div><div className={s.actions}>{area==='all'?<><Link href="/studio/journal?create=1">New article</Link><Link href="/studio/pages?create=1">New page</Link></>:<Link href={path+'?create=1'}>New {area==='faqs'?'FAQ':area==='journal'?'article':area==='testimonials'?'testimonial':'record'}</Link>}<Link href="/studio/editorial-order">Curated ordering ↗</Link><Link href="/studio/content-register">Production register ↗</Link></div></header>
 <form key={key} className={s.panel} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);navigate({...Object.fromEntries(filters.map(k=>[k,String(form.get(k)||'')])),page:'1'});}}><div className={s.toolbar}><label>Find content<input name="q" type="search" defaultValue={params.get('q')||''} maxLength={150} placeholder="Title, route or category"/></label>{select('status','Publication',[{value:'draft',label:'Unpublished draft'},{value:'published',label:'Published'},{value:'hidden',label:'Hidden'},{value:'changes',label:'Changes pending'}])}<button className={s.primary} disabled={loading}>Apply filters</button></div>
 <details><summary>More editorial filters</summary><div className={s.grid}>{select('topic','Category / topic',opts(data?.facets.topics||[]))}{select('journey','Journey',opts(data?.facets.journeys||[]))}{select('author','Author',opts(data?.facets.authors||[]))}{select('locale','Translation present',opts(['en','hi','gu']))}{select('review','Review queue',[{value:'needs-author',label:'Author evidence not recorded'},{value:'needs-native',label:'English native-reader evidence not recorded'},{value:'duplicate',label:'Possible duplicate'}])}{select('source','Source / policy',[{value:'present',label:'Source recorded'},{value:'missing',label:'Source not recorded'}])}{select('missing','Missing fields',[{value:'cover',label:'Cover image'},{value:'alt',label:'Image description'},{value:'seo',label:'Title or search description'}])}<label>Updated from (IST)<input name="from" type="date" defaultValue={params.get('from')||''}/></label><label>Updated through (IST)<input name="to" type="date" defaultValue={params.get('to')||''}/></label><label>Sort<select name="sort" defaultValue={params.get('sort')||'title'}><option value="title">Title</option><option value="newest">Recently updated</option><option value="oldest">Oldest updated</option></select></label></div><p>Translation present means text exists; open the record to check completeness and current review evidence. Native-reader evidence is separate from publication.</p></details></form>
 <div className={s.actions} aria-label="Applied editorial filters">{filters.filter(k=>params.get(k)&&!(k==='sort'&&params.get(k)==='title')).map(k=><button key={k} onClick={()=>navigate({[k]:'',page:'1'})}>Remove {k}: {params.get(k)} ×</button>)}<button onClick={()=>navigate({...Object.fromEntries(filters.map(k=>[k,''])),page:'1'})}>Clear filters</button></div><p role="status" className={s.status}>{loading?'Loading saved summaries…':message}</p>
 {failed&&<button onClick={()=>setReload(value=>value+1)}>Retry loading records</button>}<div className={s.libraryRows} aria-busy={loading}>{!loading&&data?.entries.map(entry=><Link prefetch={false} key={entry.document.id} href={href(entry.document.id)}><strong>{entry.document.title}</strong><span>{entry.document.eyebrow||'Unclassified'} · {entry.document.route}</span><small>Revision {entry.version} · {entry.visible?'Published':entry.published?'Hidden':'Unpublished'} · {entry.draftStatus}</small></Link>)}</div>{!loading&&!failed&&!data?.entries.length&&<p className={s.empty}>No records match this view. Clear filters or choose another page.</p>}<div className={s.actions}><button disabled={loading||!data||data.page<=1} onClick={()=>navigate({page:String(data!.page-1)})}>Previous page</button><span>Page {data?.page||1} of {data?.totalPages||1}</span><button disabled={loading||!data||data.page>=data.totalPages} onClick={()=>navigate({page:String(data!.page+1)})}>Next page</button></div></section>;
}
