'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {type EditorialMedia,validPublishedEditorialMedia} from '@/lib/editorial-media-model';
import {editorialUsages,type UsageOwner} from '@/lib/editorial-slots';
import {studioFetch} from './workspace-api';
import {useRecordSwitch,RecordSwitchNotice} from './record-switch';
import {DraftRecovery} from './draft-recovery';
import s from './workspace.module.css';
type Entry={media:EditorialMedia;version:number;published:EditorialMedia|null};
const state=(e:Entry)=>!validPublishedEditorialMedia(e.media)?'Needs review':e.published&&JSON.stringify(e.media)===JSON.stringify(e.published)?'Published':'Reviewed';
export function EditorialAssetLibrary({admin,onPagesLoaded}:{admin:boolean;onPagesLoaded:(pages:UsageOwner[])=>void}){
 const [rows,setRows]=useState<Entry[]>([]),[pages,setPages]=useState<UsageOwner[]>([]),[entry,setEntry]=useState<Entry|null>(null),[file,setFile]=useState<File|null>(null),[driveId,setDriveId]=useState('');
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[used,setUsed]=useState('all'),[message,setMessage]=useState('Loading editorial images…'),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[loaded,setLoaded]=useState(false);
 const switching=useRecordSwitch(dirty);
 async function load(path?:string){const [assets,content]=await Promise.all([studioFetch('/api/studio/editorial-assets'),studioFetch('/api/studio/content')]);setRows(assets.media);setPages(content.entries);onPagesLoaded(content.entries);setLoaded(true);if(path)setEntry(assets.media.find((e:Entry)=>e.media.path===path)||null);}
 useEffect(()=>{let active=true;void Promise.all([studioFetch('/api/studio/editorial-assets'),studioFetch('/api/studio/content')]).then(([assets,content])=>{if(active){setRows(assets.media);setPages(content.entries);onPagesLoaded(content.entries);setLoaded(true);setMessage('Upload → process → review → publish → assign to a page. Originals are retained.');}}).catch(()=>{if(active)setMessage('The editorial library could not load. Retry to see saved images.');});return()=>{active=false;};},[onPagesLoaded]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const usages=entry?editorialUsages(pages,entry.media.path):[];
 const filtered=rows.filter(e=>(e.media.alt+' '+e.media.editorial.filename+' '+e.media.editorial.driveId).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||state(e)===filter)&&(used==='all'||(editorialUsages(pages,e.media.path).length>0)===(used==='used')));
 function patch(values:Partial<EditorialMedia>,editorial?:Partial<EditorialMedia['editorial']>){if(!entry)return;const next={...entry.media,...values,editorial:{...entry.media.editorial,...editorial}};delete next.editorial.reviewedBy;delete next.editorial.reviewedAt;setEntry({...entry,media:next});setDirty(true);}
 async function upload(){if(!file||busy)return;setBusy(true);setMessage('Uploading and processing three responsive sizes…');try{const response=await fetch('/api/studio/editorial-assets',{method:'PUT',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name),'X-Drive-File-Id':driveId.trim()},body:file});const data=await response.json();if(!response.ok)throw Error(data.error||'Upload failed. Retry with your selected file.');await load(data.entry.media.path);setDirty(false);setMessage(data.reused?'The identical original already exists. Its saved record is open.':'Processing complete. Review the subject, description and provenance before publishing.');}catch(e){setMessage(e instanceof Error?e.message:'Upload failed. Your source selection is retained.');}finally{setBusy(false);}}
 async function save(operation:'draft'|'review'|'publish'){if(!entry||busy)return;setBusy(true);try{await studioFetch('/api/studio/editorial-assets',{path:entry.media.path,version:entry.version,operation,alt:entry.media.alt,caption:entry.media.caption,provenance:entry.media.provenance,classification:entry.media.editorial.classification,reviewNote:entry.media.editorial.reviewNote});await load(entry.media.path);setDirty(false);setMessage(operation==='publish'?'Image published to the approved picker. Pages change only when their own revisions are published.':operation==='review'?'Visual review recorded. Publication is a separate step.':'Metadata draft saved. Review is required again before publication.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed. Your edits remain here.');}finally{setBusy(false);}}
 return <section className={s.panel} aria-label="Editorial image library"><h2>Images for your stories.</h2><p>Source: owner-supplied Drive · Still images · Separate from product galleries and customer references.</p><p role="status">{message}</p><RecordSwitchNotice control={switching}/>
 <button disabled={busy} onClick={()=>switching.request(()=>{setBusy(true);void load(entry?.media.path).then(()=>{setDirty(false);setMessage('Saved editorial images reloaded.');}).catch(()=>setMessage('Reload failed. Your current edits remain here.')).finally(()=>setBusy(false));})}>Refresh editorial library</button>
 <details className={s.panel}><summary>Add a Drive image</summary><p>Download the original from your approved Drive folder, then select it here. JPEG, PNG or WebP; up to 4 MB; at least 320 pixels per side. Video is not supported in this image uploader.</p><label>Original image file<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Drive file ID<input value={driveId} maxLength={100} disabled={busy} onChange={e=>setDriveId(e.target.value)}/></label><button disabled={busy||dirty||!file||!driveId.trim()} onClick={()=>void upload()}>Upload and process image</button>{dirty&&<p>Save the current image edits before uploading another original.</p>}</details>
 <div className={s.toolbar}><label>Find editorial image<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Editorial review state<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All states</option>{['Needs review','Reviewed','Published'].map(v=><option key={v}>{v}</option>)}</select></label><label>Editorial usage<select value={used} onChange={e=>setUsed(e.target.value)}><option value="all">All usages</option><option value="used">Used</option><option value="unused">Unused</option></select></label></div>
 <div className={s.layout}><div className={s.mediaGrid}>{filtered.map(e=><button key={e.media.path} disabled={busy} aria-pressed={entry?.media.path===e.media.path} onClick={()=>{if(entry?.media.path!==e.media.path)switching.request(()=>{setEntry(structuredClone(e));setDirty(false);});}}><span><Image unoptimized src={'/api/studio/editorial-assets/image?id='+e.media.editorial.id} alt="" fill sizes="160px"/></span>{e.media.editorial.filename}<small>{state(e)} · {e.media.editorial.width} × {e.media.editorial.height} · {editorialUsages(pages,e.media.path).length} saved usages</small></button>)}{loaded&&!filtered.length&&<p className={s.empty}>No images match. Clear the filters or add a reviewed Drive source.</p>}</div>
 {entry?<div className={s.editor} data-unsaved={dirty}><fieldset disabled={busy}><h3>{entry.media.editorial.filename}</h3><p>Revision {entry.version} · {state(entry)}{dirty?' · Unsaved metadata edits':''}</p><div className={s.mediaPreview}><Image unoptimized src={'/api/studio/editorial-assets/image?id='+entry.media.editorial.id} alt={entry.media.alt} fill sizes="600px" style={{objectFit:'contain'}}/></div>
 <label>Editorial image description<input value={entry.media.alt} maxLength={180} onChange={e=>patch({alt:e.target.value})}/></label><label>Editorial image caption<input value={entry.media.caption} maxLength={180} onChange={e=>patch({caption:e.target.value})}/></label><label>Provenance<textarea value={entry.media.provenance} maxLength={500} onChange={e=>patch({provenance:e.target.value})}/></label><label>Image classification<select value={entry.media.editorial.classification} onChange={e=>patch({},{classification:e.target.value as EditorialMedia['editorial']['classification']})}><option value="unknown">Unknown — cannot publish</option><option value="design-visualization">Design visualization</option><option value="photography">Verified photography</option></select></label><label>Visual review and intended use<textarea value={entry.media.editorial.reviewNote} maxLength={1000} onChange={e=>patch({},{reviewNote:e.target.value})}/></label>
 <p><a href={'https://drive.google.com/file/d/'+entry.media.editorial.driveId+'/view'} target="_blank" rel="noreferrer">Original in Drive ↗</a></p><p className={s.help}>Drive ID: {entry.media.editorial.driveId}<br/>Original: {entry.media.editorial.bytes} bytes · {entry.media.editorial.width} × {entry.media.editorial.height}<br/>SHA-256: {entry.media.editorial.sha256}</p><p>Responsive WebP sizes: {entry.media.editorial.derivatives.map(d=>d.width+' × '+d.height+' / '+Math.round(d.bytes/1024)+' KB').join('; ')}</p>
 <details className={s.panel}><summary>{usages.length} saved editorial usages · 0 product associations</summary>{usages.map(u=><p key={u.record+u.slot+u.state}><a href={'/studio/site-images?record='+encodeURIComponent(u.record)+'&slot='+encodeURIComponent(u.slot)}>{u.title} · {u.label}</a> · {u.state}</p>)}<p>Counts include draft and last-published records, including hidden pages. Revisions retain their image references. Original files and derivatives cannot be replaced or deleted here; upload a new asset and reassign an individual page slot.</p></details>
 <div className={s.actions}><button disabled={!dirty||busy} onClick={()=>void save('draft')}>Save image metadata draft</button>{admin&&<><button disabled={busy} onClick={()=>void save('review')}>Record visual review</button><button disabled={busy||dirty||!validPublishedEditorialMedia(entry.media)} onClick={()=>void save('publish')}>Publish editorial image</button></>}</div>
 {entry.published&&!dirty&&<Link href="/studio/site-images">Assign to a page ↗</Link>}<DraftRecovery value={entry.media} busy={busy} onReload={async()=>{await load(entry.media.path);setDirty(false);}}/>
 </fieldset></div>:<p className={s.empty}>Choose an editorial image to inspect its source, review and usages.</p>}
 </div></section>;
}
