'use client';
import type {ContentDocument} from '@/lib/content-model';
import {editorialDisclosure,type EditorialRecord} from '@/lib/editorial-record-model';
import type {EditorialUsage} from '@/lib/homepage-model';
import type {PublicMedia} from '@/lib/public-media';
import {CropFields} from './editorial-crop-fields';
import s from './workspace.module.css';

export function UsageFields({label,usage,media,onChange}:{label:string;usage?:EditorialUsage;media:PublicMedia[];onChange:(usage:EditorialUsage|undefined)=>void}){
 return <fieldset className={s.panel}><legend>{label}</legend><label>Published image<select value={usage?.path||''} onChange={e=>{const m=media.find(m=>m.path===e.target.value);onChange(m?{path:m.path,alt:m.alt,caption:m.caption,desktop:usage?.desktop||{x:m.focalX,y:m.focalY,ratio:'3/2'},mobile:usage?.mobile||{x:m.focalX,y:m.focalY,ratio:'4/5'}}:undefined);}}><option value="">No image</option>{usage&&!media.some(m=>m.path===usage.path)&&<option value={usage.path}>Unavailable saved selection</option>}{media.map(m=><option key={m.path} value={m.path}>{m.alt}</option>)}</select></label>{usage&&<CropFields usage={usage} onChange={onChange}/>}</fieldset>;
}
export function EditorialGalleryFields({images,media,onChange,limit=12}:{images:EditorialUsage[];media:PublicMedia[];onChange:(images:EditorialUsage[])=>void;limit?:number}){
 return <fieldset className={s.panel}><legend>Independent gallery usages</legend><p>These selections belong to this new editorial record. Original media and product galleries stay unchanged.</p>{images.map((usage,i)=><div key={i}><UsageFields label={'Image '+(i+1)} usage={usage} media={media} onChange={next=>onChange(next?images.map((v,n)=>n===i?next:v):images.filter((_,n)=>n!==i))}/><div className={s.actions}>{[-1,1].map(delta=><button type="button" key={delta} disabled={i+delta<0||i+delta>=images.length} onClick={()=>{const next=[...images];[next[i],next[i+delta]]=[next[i+delta],next[i]];onChange(next);}}>Move image {i+1} {delta===-1?'up':'down'}</button>)}</div></div>)}<label>Add a published image<select value="" disabled={images.length>=limit} onChange={e=>{const m=media.find(m=>m.path===e.target.value);if(m)onChange([...images,{path:m.path,alt:m.alt,caption:m.caption,desktop:{x:m.focalX,y:m.focalY,ratio:'3/2'},mobile:{x:m.focalX,y:m.focalY,ratio:'4/5'}}]);}}><option value="">Choose an image…</option>{media.map(m=><option key={m.path} value={m.path}>{m.alt}</option>)}</select></label><p>{images.length} / {limit} images</p></fieldset>;
}
export function EditorialRecordFields({document:d,media,onChange}:{document:ContentDocument;media:PublicMedia[];onChange:(patch:Partial<ContentDocument>)=>void}){
 const e=d.editorial;if(!e)return null;
 const patch=(value:Partial<EditorialRecord>)=>onChange({editorial:{...e,...value}});
 return <fieldset className={s.panel} id="content-field-editorial" tabIndex={-1}><legend>Source and public classification</legend><p>{editorialDisclosure(e)}</p>{e.kind!=='faq'&&<label>Public classification<select value={e.classification} onChange={v=>patch({classification:v.target.value as EditorialRecord['classification'],...(v.target.value!=='genuine'?{attribution:undefined}:{})})}><option value={e.kind==='portfolio'?'concept':'fictional'}>{e.kind==='portfolio'?'Labelled concept study':'Labelled fictional sample'}</option><option value="genuine">Genuine, with documented approval</option></select></label>}{e.classification==='genuine'&&<><p>Record genuine evidence and permission. Saving these fields does not independently certify consent or a human review.</p><label>Permitted public attribution<input value={e.attribution||''} maxLength={150} onChange={v=>patch({attribution:v.target.value})}/></label>{(['source','permission','reviewer','approvedOn'] as const).map(key=><label key={key}>{({source:'Original source reference (staff only)',permission:'Permission to publish (staff only)',reviewer:'Approval reviewer (staff only)',approvedOn:'Approval date'} as const)[key]}<input type={key==='approvedOn'?'date':'text'} maxLength={1000} value={e.evidence?.[key]||''} onChange={v=>patch({evidence:{source:'',permission:'',reviewer:'',approvedOn:'',...e.evidence,[key]:v.target.value}})}/></label>)}</>}{e.kind==='faq'&&<><label>Related current policy<input placeholder="/terms" value={e.policyHref||''} onChange={v=>patch({policyHref:v.target.value||undefined})}/></label><label>Source for this answer (staff only)<textarea maxLength={1000} value={e.evidence?.source||''} onChange={v=>patch({evidence:{permission:'',reviewer:'',approvedOn:'',...e.evidence,source:v.target.value}})}/></label></>}{e.kind==='portfolio'&&<><EditorialGalleryFields images={e.gallery||[]} media={media} onChange={gallery=>patch({gallery})}/><fieldset className={s.panel}><legend>Story details</legend>{(e.details||[]).map((detail,i)=><div className={s.grid} key={i}><label>Label {i+1}<input maxLength={80} value={detail.label} onChange={v=>patch({details:e.details!.map((d,n)=>n===i?{...d,label:v.target.value}:d)})}/></label><label>Value {i+1}<input maxLength={500} value={detail.value} onChange={v=>patch({details:e.details!.map((d,n)=>n===i?{...d,value:v.target.value}:d)})}/></label><button type="button" onClick={()=>patch({details:e.details!.filter((_,n)=>n!==i)})}>Remove detail {i+1}</button></div>)}<button type="button" disabled={(e.details?.length||0)>=12} onClick={()=>patch({details:[...(e.details||[]),{label:'',value:''}]})}>Add story detail</button></fieldset></>}</fieldset>;
}
