'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import type {ContentDocument,ContentSection} from '@/lib/content-model';
import type {HomeAction,HomeSection,EditorialUsage,ImageCrop} from '@/lib/homepage-model';
import {previewHref} from '@/lib/content-preview';
import {studioFetch,StudioRequestError} from './workspace-api';
import {RevisionHistory} from './revision-history';
import {ContentCompare} from './content-compare';
import {DraftRecovery} from './draft-recovery';
import {publicationState} from '@/lib/content-health';
import s from './workspace.module.css';

export type HomepageEntry={document:ContentDocument;version:number;publishedVersion?:number;published:ContentDocument|null;visible:boolean};
type Options={products:{id:string;name:string;category:string}[];articles:{id:string;name:string}[];media:{path:string;alt:string;caption:string}[];destinations:string[]};
function ActionFields({label,value,onChange}:{label:string;value:HomeAction;onChange:(v:HomeAction)=>void}){return <fieldset className={s.panel}><legend>{label}</legend><div className={s.grid}><label>Button label<input maxLength={80} value={value.label} onChange={e=>onChange({...value,label:e.target.value})}/></label><label>Destination<input list="homepage-destinations" maxLength={240} value={value.href} onChange={e=>onChange({...value,href:e.target.value})}/><small>Published internal page, optionally with a section anchor.</small></label></div></fieldset>;}
function OrderedChoices({label,ids,choices,onChange}:{label:string;ids:string[];choices:{id:string;name:string}[];onChange:(ids:string[])=>void}){
 return <fieldset className={s.panel}><legend>{label}</legend><ol className={s.selectionList}>{ids.map((id,i)=><li key={id}><span>{choices.find(c=>c.id===id)?.name||'Unavailable: '+id}<small>{id}</small></span><div className={s.actions}><button type="button" disabled={i===0} aria-label={'Move '+id+' up'} onClick={()=>{const next=[...ids];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next);}}>↑</button><button type="button" disabled={i===ids.length-1} aria-label={'Move '+id+' down'} onClick={()=>{const next=[...ids];[next[i+1],next[i]]=[next[i],next[i+1]];onChange(next);}}>↓</button><button type="button" aria-label={'Remove '+id+' from selection'} onClick={()=>onChange(ids.filter(x=>x!==id))}>Remove</button></div></li>)}</ol><label>Add a published reference<select value="" disabled={ids.length>=6} onChange={e=>{if(e.target.value)onChange([...ids,e.target.value]);}}><option value="">Choose…</option>{choices.filter(c=>!ids.includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</select></label><p className={s.help}>Up to six references. This changes presentation order only.</p></fieldset>;
}
function CropFields({usage,onChange}:{usage:EditorialUsage;onChange:(v:EditorialUsage)=>void}){return <><label>Contextual image description<input value={usage.alt} maxLength={180} onChange={e=>onChange({...usage,alt:e.target.value})}/></label><label>Caption<input value={usage.caption} maxLength={180} onChange={e=>onChange({...usage,caption:e.target.value})}/></label><div className={s.grid}>{(['desktop','mobile'] as const).map(device=>{const crop=usage[device];return <fieldset className={s.panel} key={device}><legend>{device==='desktop'?'Desktop crop':'Mobile crop'}</legend><div className={s.cropPreview} style={{aspectRatio:crop.ratio}}><Image src={usage.path} alt={usage.alt} fill sizes="300px" style={{objectFit:'cover',objectPosition:`${crop.x}% ${crop.y}%`}}/></div>{(['x','y'] as const).map(axis=><label key={axis}>{axis==='x'?'Horizontal':'Vertical'} focus: {crop[axis]}%<input type="range" min={0} max={100} step={1} value={crop[axis]} onChange={e=>onChange({...usage,[device]:{...crop,[axis]:Number(e.target.value)}})}/></label>)}<label>Frame shape<select value={crop.ratio} onChange={e=>onChange({...usage,[device]:{...crop,ratio:e.target.value as ImageCrop['ratio']}})}><option value="4/5">Portrait 4:5</option><option value="3/2">Landscape 3:2</option><option value="1/1">Square</option></select></label></fieldset>;})}</div></>;}

export function HomepageEditor({entry,admin,dirty,onChange,onSaved,onBusy,initialSection='hero'}:{entry:HomepageEntry;admin:boolean;dirty:boolean;onChange:(document:ContentDocument)=>void;onSaved:(entry:HomepageEntry)=>void;onBusy:(busy:boolean)=>void;initialSection?:string}){
 const d=entry.document,home=d.homepage!;
 const [options,setOptions]=useState<Options|null>(null),[optionsError,setOptionsError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState(initialSection),[latest,setLatest]=useState<HomepageEntry|null>(null),[restoredFrom,setRestoredFrom]=useState<number|undefined>(),[verification,setVerification]=useState('');
 async function loadOptions(){setOptionsError('');try{setOptions(await studioFetch('/api/studio/homepage-options'));}catch(e){setOptionsError(e instanceof Error?e.message:'Choices are unavailable.');}}
 useEffect(()=>{let active=true;void studioFetch('/api/studio/homepage-options').then(data=>{if(active)setOptions(data);}).catch(e=>{if(active)setOptionsError(e.message);});return()=>{active=false;};},[]);
 const changeHome=(patch:Partial<typeof home>)=>onChange({...d,homepage:{...home,...patch}});
 const changeBlock=(id:string,patch:Partial<HomeSection>)=>changeHome({sections:home.sections.map(s=>s.id===id?{...s,...patch}:s)});
 const changeCopy=(id:string,patch:Partial<ContentSection>)=>onChange({...d,sections:d.sections.map(s=>s.id===id?{...s,...patch}:s)});
 async function verify(version:number,title:string){
  setVerification('Checking the anonymous public page…');
  try{const response=await fetch('/?verifyHome='+version+'&t='+Date.now(),{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(15000)});const html=new DOMParser().parseFromString(await response.text(),'text/html');const page=html.querySelector('[data-home-revision="'+version+'"]');if(!response.ok||!page||page.querySelector('h1')?.textContent!==title)throw Error('The public page did not return this revision.');setVerification('Published and verified: anonymous homepage returned revision '+version+'.');}
  catch{setVerification('Published; verification needs attention. Your publication is saved. Retry verification before publishing again.');}
 }
 async function save(operation:'draft'|'publish'|'hide'){
  if(busy)return;setBusy(true);onBusy(true);setMessage('Saving…');if(operation==='publish')setVerification('');
  try{
   const editable={...d};delete editable.homeSnapshot;
   const result=await studioFetch('/api/studio/content',{document:editable,version:entry.version,operation,...(operation==='draft'&&restoredFrom?{restoredFrom}:{})});
   onSaved({...entry,document:result.document,version:result.version,publishedVersion:result.publishedVersion,...(operation==='publish'?{published:result.document,visible:true}:operation==='hide'?{visible:false}:{})});
   setLatest(null);setRestoredFrom(undefined);setMessage(operation==='draft'?'Draft saved. Your public page is unchanged.':operation==='publish'?'Publication committed as revision '+result.version+'.':'Homepage document hidden. The established homepage is visible.');
   if(operation==='publish')await verify(result.version,result.document.title);
  }catch(e){setMessage(e instanceof Error?e.message:'Save failed. Your edits remain here.');if(e instanceof StudioRequestError&&e.status===409){try{const data=await studioFetch('/api/studio/content');setLatest(data.entries.find((e:HomepageEntry)=>e.document.id===d.id)||null);}catch{/* Keep local work when comparison is unavailable. */}}}finally{setBusy(false);onBusy(false);}
 }
 const block=home.sections.find(s=>s.id===selected),copy=d.sections.find(s=>s.id===selected);
 const issues=entry.document.homeSnapshot?.issues||[];
 return <section className={s.editor} data-unsaved={dirty} aria-label="Homepage composer"><header className={s.composerHeader}><div><span className={s.help}>PAGE / HOMEPAGE</span><h2>Shape the first impression.</h2><p>{publicationState(entry.published,entry.visible)} · Draft {entry.version||'not saved'} · Public {entry.publishedVersion||'not published'}{dirty?' · Unsaved edits':''}</p></div><p className={s.help}>Products and their galleries are references. Contact information comes from Business settings.</p></header>
 <div className={s.actions}><button className={s.primary} disabled={busy} onClick={()=>void save('draft')}>Save draft</button>{!dirty&&entry.version>0?<a className={s.controlLink} href={previewHref(d.id,entry.version)} target="_blank" rel="noreferrer">Open saved preview ↗</a>:<span className={s.help}>Save your changes to open the exact preview.</span>}{admin&&<button disabled={busy||dirty||!entry.version||issues.length>0} onClick={()=>void save('publish')}>Publish homepage</button>}<a className={s.controlLink} href="/" target="_blank" rel="noreferrer">View public homepage ↗</a>{entry.visible&&entry.publishedVersion&&<button disabled={busy} onClick={()=>void verify(entry.publishedVersion!,entry.published!.title)}>Verify public homepage</button>}</div>
 <p role="status" className={s.status}>{message}</p>{verification&&<div className={s.panel}><p role="status">{verification}</p><button disabled={busy||!entry.publishedVersion||!entry.visible} onClick={()=>void verify(entry.publishedVersion!,entry.published!.title)}>Retry public verification</button></div>}
 {issues.length>0&&<aside className={s.panel}><h3>Publication blockers in saved revision</h3><ul>{issues.map(issue=><li key={issue}>{issue}</li>)}</ul><p>Fix the fields and save a new draft to recheck.</p></aside>}
 {optionsError&&<div role="alert" className={s.panel}><p>{optionsError}</p><button onClick={()=>void loadOptions()}>Retry published choices</button></div>}
 {latest&&<details open className={s.panel}><summary>A newer version exists — your edits are retained</summary><p>Compare the latest saved draft with your work below. Copy your local draft before choosing to reload.</p><ContentCompare before={latest.document} after={d}/></details>}
 <fieldset disabled={busy} className={s.composerFields}><div className={s.sectionOutline} role="group" aria-label="Homepage sections"><button type="button" aria-pressed={selected==='hero'} onClick={()=>setSelected('hero')}>Hero & opening strip</button>{home.sections.map((section,i)=><div key={section.id}><button type="button" aria-pressed={selected===section.id} onClick={()=>setSelected(section.id)}>{d.sections.find(s=>s.id===section.id)?.heading}<small>{section.type} · {section.enabled?'Visible':'Hidden'}</small></button><button type="button" aria-label={'Move section '+section.id+' up'} disabled={i===0} onClick={()=>{const next=[...home.sections];[next[i-1],next[i]]=[next[i],next[i-1]];changeHome({sections:next});}}>↑</button><button type="button" aria-label={'Move section '+section.id+' down'} disabled={i===home.sections.length-1} onClick={()=>{const next=[...home.sections];[next[i+1],next[i]]=[next[i],next[i+1]];changeHome({sections:next});}}>↓</button></div>)}</div>
 <datalist id="homepage-destinations">{options?.destinations.map(route=><option value={route} key={route}/>)}</datalist>
 <div className={s.panel}>{selected==='hero'?<><h3>Hero & opening strip</h3><label>Homepage heading<input id="content-field-title" maxLength={120} value={d.title} onChange={e=>onChange({...d,title:e.target.value})}/></label><label>Eyebrow<input value={d.eyebrow} maxLength={100} onChange={e=>onChange({...d,eyebrow:e.target.value})}/></label><label>Introduction & search description<textarea id="content-field-description" value={d.description} maxLength={300} onChange={e=>onChange({...d,description:e.target.value})}/></label><label>Hero piece<select value={home.heroProductId} onChange={e=>changeHome({heroProductId:e.target.value})}>{!options?.products.some(p=>p.id===home.heroProductId)&&<option value={home.heroProductId}>{home.heroProductId} · current reference</option>}{options?.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label><ActionFields label="Primary action" value={home.primary} onChange={primary=>changeHome({primary})}/><ActionFields label="Secondary action" value={home.secondary} onChange={secondary=>changeHome({secondary})}/><label>Hero annotation<input value={home.annotation} maxLength={180} onChange={e=>changeHome({annotation:e.target.value})}/></label>{home.strip.map((line,i)=><label key={i}>Opening strip {i+1}<input value={line} maxLength={100} onChange={e=>changeHome({strip:home.strip.map((text,n)=>n===i?e.target.value:text)})}/></label>)}</>:block&&copy?<><h3>{copy.heading}</h3><label className={s.check}><input type="checkbox" checked={block.enabled} onChange={e=>changeBlock(block.id,{enabled:e.target.checked})}/>Visible on the homepage</label><label>Eyebrow<input maxLength={100} value={block.eyebrow} onChange={e=>changeBlock(block.id,{eyebrow:e.target.value})}/></label><label>Heading<input maxLength={150} value={copy.heading} onChange={e=>changeCopy(block.id,{heading:e.target.value})}/></label><label>Paragraphs — separate with an empty line<textarea rows={7} value={copy.paragraphs.join('\n\n')} onChange={e=>changeCopy(block.id,{paragraphs:e.target.value.split(/\n\s*\n/)})}/></label><label>Checklist — one item per line<textarea rows={3} value={copy.checklist?.join('\n')||''} onChange={e=>changeCopy(block.id,{checklist:e.target.value?e.target.value.split('\n'):undefined})}/></label>
 {block.action&&<ActionFields label="Section action" value={block.action} onChange={action=>changeBlock(block.id,{action})}/>}
 {block.type==='selected'&&<OrderedChoices label="Selected pieces" ids={block.productIds||[]} choices={options?.products||[]} onChange={productIds=>changeBlock(block.id,{productIds})}/>}
 {block.type==='journal'&&<OrderedChoices label="Selected journal stories" ids={block.articleIds||[]} choices={options?.articles||[]} onChange={articleIds=>changeBlock(block.id,{articleIds})}/>}
 {block.type==='categories'&&<><p className={s.help}>One existing category per line, in display order. Leave blank to show all published categories.</p><label>Category display order<textarea rows={8} value={block.categories?.join('\n')||''} onChange={e=>changeBlock(block.id,{categories:e.target.value?e.target.value.split('\n').filter(Boolean):[]})}/></label><button type="button" onClick={()=>changeBlock(block.id,{categories:[...new Set(options?.products.map(p=>p.category)||[])]})}>Use current category list</button></>}
 {block.type==='story'&&<fieldset className={s.panel}><legend>Editorial image placement</legend><p className={s.help}>This page slot owns its crops and description. Product gallery associations and original images stay unchanged.</p><label>Published image<select id="content-field-image" value={block.image?.path||''} onChange={e=>{const media=options?.media.find(m=>m.path===e.target.value);changeBlock(block.id,{image:media?{...media,desktop:block.image?.desktop||{x:50,y:50,ratio:'4/5'},mobile:block.image?.mobile||{x:50,y:50,ratio:'1/1'}}:undefined});}}><option value="">Text only</option>{block.image&&!options?.media.some(m=>m.path===block.image?.path)&&<option value={block.image.path}>{block.image.path} · current reference</option>}{options?.media.map(m=><option key={m.path} value={m.path}>{m.alt}</option>)}</select></label>{block.image&&<CropFields usage={block.image} onChange={image=>changeBlock(block.id,{image})}/>}</fieldset>}
 {block.items?.map((item,i)=><fieldset className={s.panel} key={item.id}><legend>{block.type==='steps'?'Step':'Journey'} {i+1}</legend><label>Title<input maxLength={120} value={item.title} onChange={e=>changeBlock(block.id,{items:block.items!.map((v,n)=>n===i?{...v,title:e.target.value}:v)})}/></label><label>Description<textarea maxLength={1000} value={item.body} onChange={e=>changeBlock(block.id,{items:block.items!.map((v,n)=>n===i?{...v,body:e.target.value}:v)})}/></label>{item.productId&&<label>Existing piece for image<select value={item.productId} onChange={e=>changeBlock(block.id,{items:block.items!.map((v,n)=>n===i?{...v,productId:e.target.value}:v)})}>{!options?.products.some(p=>p.id===item.productId)&&<option value={item.productId}>{item.productId}</option>}{options?.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label>}{item.action&&<ActionFields label="Journey action" value={item.action} onChange={action=>changeBlock(block.id,{items:block.items!.map((v,n)=>n===i?{...v,action}:v)})}/>}<div className={s.actions}><button type="button" disabled={i===0} onClick={()=>{const items=[...block.items!];[items[i-1],items[i]]=[items[i],items[i-1]];changeBlock(block.id,{items});}}>Move up</button><button type="button" disabled={i===block.items!.length-1} onClick={()=>{const items=[...block.items!];[items[i+1],items[i]]=[items[i],items[i+1]];changeBlock(block.id,{items});}}>Move down</button></div></fieldset>)}
 </>:null}</div>
 <button type="button" disabled={home.sections.length>=20} onClick={()=>{const id='story-'+crypto.randomUUID().slice(0,8);onChange({...d,sections:[...d.sections,{id,heading:'New editorial chapter',paragraphs:['Describe the idea, material or approach.']}],homepage:{...home,sections:[...home.sections,{id,type:'story',enabled:false,eyebrow:'From the atelier',action:{label:'Our story',href:'/our-story'}}]}});setSelected(id);}}>Add editorial chapter</button>
 {entry.published&&<details className={s.panel}><summary>Compare public version with this draft</summary><ContentCompare before={entry.published} after={d}/></details>}
 <RevisionHistory<ContentDocument> key={d.id+':'+entry.version} kind="content" entityKey={d.id} currentVersion={entry.version} currentDocument={d} onRestore={(document,version)=>{onChange(document);setRestoredFrom(version);setMessage('Earlier content is in your editor. Save a new draft, preview it, then publish when ready.');}}/>
 <DraftRecovery value={d} busy={busy} onReload={async()=>{const data=await studioFetch('/api/studio/content');const next=data.entries.find((e:HomepageEntry)=>e.document.id===d.id);if(next){onSaved(next);setLatest(null);setMessage('Latest saved draft loaded.');setVerification('');setRestoredFrom(undefined);}}}/>
 {admin&&entry.visible&&<details className={s.panel}><summary>Publication settings</summary><p>Hiding this document restores the established homepage until another homepage revision is published.</p><button type="button" disabled={dirty} onClick={()=>void save('hide')}>Hide homepage document</button></details>}
 </fieldset></section>;
}
