'use client';
import {formatBusinessTime} from '@/lib/business-time';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Dialog} from '@/components/shop/dialog';
import {OrderKanban} from '@/components/studio-orders-board';
import {orderStages,stageLabel,type OrderStage,type StudioOrder} from '@/lib/studio-orders';
import {InquiryDetail,type InquiryDetailData} from './inquiry-detail';
import {useUnsavedWork} from './use-unsaved-work';


import { Grid, List, RefreshCw, Plus, X } from 'lucide-react';
import {studioFetch,type StaffMember} from './workspace-api';
import s from './workspace.module.css';
type Detail=InquiryDetailData;
export function InquiryBoard({staff,admin,dueOnly=false}:{staff:StaffMember[];admin:boolean;dueOnly?:boolean}){
 const params=useSearchParams();
 const [product,setProduct]=useState(''),[category,setCategory]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [page,setPage]=useState(1),[stage,setStage]=useState(params.get('stage')||''),[owner,setOwner]=useState(''),[source,setSource]=useState(''),[search,setSearch]=useState(''),[listMode,setListMode]=useState(dueOnly),[manual,setManual]=useState<Partial<StudioOrder>|null>(null),[manualEvents,setManualEvents]=useState<Detail['events']>([]);
 const [orders,setOrders]=useState<StudioOrder[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading inquiries…'),[query,setQuery]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[truncated,setTruncated]=useState(false);
 const inFlight=useRef(false),loadSequence=useRef(0),openSequence=useRef(0),manualRequest=useRef<string|null>(null);
 const [manualOriginal,setManualOriginal]=useState(''),[loading,setLoading]=useState(true);
 const manualDirty=!!manual&&JSON.stringify({client:manual.client,title:manual.title})!==manualOriginal;

 const [moveRequest,setMoveRequest]=useState<{id:string;status:OrderStage}|null>(null),[moveReason,setMoveReason]=useState('');
 useUnsavedWork(manualDirty||!!moveReason);
 const load=useCallback(()=>{const request=++loadSequence.current;return studioFetch('/api/studio/orders?'+new URLSearchParams({page:String(page),q:search,stage,assignee:owner,source,product,category,from,to,due:dueOnly?'1':'0'})).then(data=>{if(request===loadSequence.current){setOrders(data.orders);setTruncated(data.hasMore);setMessage('Inquiries are saved in the shared Studio. Drag a card or use its stage menu.');}}).catch(e=>{if(request===loadSequence.current){setOrders([]);setTruncated(false);setMessage(e.message);}throw e;}).finally(()=>{if(request===loadSequence.current)setLoading(false);});},[page,search,stage,owner,source,product,category,from,to,dueOnly]);
 useEffect(()=>{void load().catch(()=>{});return()=>{loadSequence.current++;};},[load]);
 useEffect(()=>{const focus=()=>{if(!inFlight.current&&!detail&&!manual)void load().catch(()=>setMessage('Refresh failed. Check your connection.'));};window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[load,detail,manual]);
 function open(id:string){const request=++openSequence.current;return studioFetch('/api/studio/workspace?view=inquiry&id='+encodeURIComponent(id)).then(data=>{if(request!==openSequence.current)return;if(data.manual){setManual(data.manual);setManualOriginal(JSON.stringify({client:data.manual.client,title:data.manual.title}));setManualEvents(data.events);return;}setDetail(data);}).catch(e=>{if(request===openSequence.current)setMessage(e instanceof Error?e.message:'Unable to open inquiry.');});}
 async function move(id:string,status:OrderStage,confirmedReason?:string){const order=orders.find(o=>o.id===id);if(!order||order.status===status||inFlight.current)return;const needsReason=status==='CLOSED'||orderStages.indexOf(status)<orderStages.indexOf(order.status);if(needsReason&&confirmedReason===undefined){setMoveRequest({id,status});setMoveReason('');return;}const reason=confirmedReason||'';if(needsReason&&!reason.trim())return;inFlight.current=true;setBusy(true);const previous=orders;let committed=false;setOrders(v=>v.map(o=>o.id===id?{...o,status}:o));try{const result=await studioFetch('/api/studio/orders',{action:'move',id,status,version:order.version,reason});committed=true;if(result.order)setOrders(v=>v.map(o=>o.id===id?{...o,...result.order}:o));setMoveRequest(null);setMoveReason('');setMessage('Stage saved.');await load();}catch(e){if(!committed)setOrders(previous);setMessage(committed?'Stage saved, but the board refresh failed. Refresh before the next change.':e instanceof Error?e.message:'Move failed.');await load().catch(()=>{});}finally{inFlight.current=false;setBusy(false);}}

 const selectedRecord=params.get('record');
 useEffect(()=>{if(selectedRecord)void open(selectedRecord);return()=>{openSequence.current++;};},[selectedRecord]);
 async function saveManual(){if(!manual||inFlight.current)return;inFlight.current=true;setBusy(true);if(!manual.id&&!manualRequest.current)manualRequest.current=crypto.randomUUID();try{const saved=await studioFetch('/api/studio/orders',{action:manual.id?'edit':'create',requestId:manualRequest.current||undefined,id:manual.id,version:manual.version,client:manual.client,title:manual.title});setManual(saved.order);setManualOriginal(JSON.stringify({client:saved.order.client,title:saved.order.title}));await load();setManual(null);setMessage('Manual order saved.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed.');}finally{inFlight.current=false;setBusy(false);}}
 const visible=orders;
 return <><div className={s.heading}><div><h1>Work in motion.</h1><p>Every website inquiry arrives here, ready for a personal conversation.</p></div><button disabled={busy||loading} onClick={()=>void load().then(()=>setMessage('Board refreshed.')).catch(e=>setMessage(e.message))}><RefreshCw size={13} style={{display:'inline',verticalAlign:'text-bottom',marginRight:6}} aria-hidden="true" /><span>Refresh board</span></button></div>
  <div className={s.chipBar} role="tablist" aria-label="Filter inquiries by stage">
    <button type="button" role="tab" aria-selected={stage === ''} className={stage === '' ? s.filterChipActive : s.filterChip} onClick={() => { setLoading(true); setStage(''); setPage(1); }}>All stages ({orders.length})</button>
    {orderStages.map(v => <button key={v} type="button" role="tab" aria-selected={stage === v} className={stage === v ? s.filterChipActive : s.filterChip} onClick={() => { setLoading(true); setStage(v); setPage(1); }}>{stageLabel(v)}</button>)}
  </div>
  <form className={s.toolbar} onSubmit={e=>{e.preventDefault();setPage(1);setSearch(query);}}>
    <div className={s.searchWrap}>
      <input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an inquiry (name, piece, ref)…" aria-label="Find an inquiry" />
      {query && <button type="button" className={s.searchClearBtn} onClick={() => { setQuery(''); setSearch(''); setPage(1); }} aria-label="Clear search" title="Clear search"><X size={14} aria-hidden="true" /></button>}
    </div>
    <button disabled={busy}>Search</button>
    <label>Stage<select disabled={busy||loading} value={stage} onChange={e=>{setLoading(true);setStage(e.target.value);setPage(1);}}><option value="">All stages</option>{orderStages.map(v=><option key={v} value={v}>{stageLabel(v)}</option>)}</select></label>
    {admin&&<label>Assignee<select disabled={busy||loading} value={owner} onChange={e=>{setLoading(true);setOwner(e.target.value);setPage(1);}}><option value="">All staff</option><option value="unassigned">Unassigned website inquiries</option>{staff.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>}
    <label>Source<select disabled={busy||loading} value={source} onChange={e=>{setLoading(true);setSource(e.target.value);setPage(1);}}><option value="">All permitted records</option><option value="website">Website inquiry</option>{admin&&<option value="manual">Staff-entered order</option>}</select></label>
    <label>Product ID<input disabled={busy} value={product} maxLength={100} onChange={e=>{setLoading(true);setProduct(e.target.value);setPage(1);}}/></label>
    <label>Saved category<input disabled={busy} value={category} maxLength={80} onChange={e=>{setLoading(true);setCategory(e.target.value);setPage(1);}}/></label>
    <label>Received from (IST)<input type="date" disabled={busy} value={from} onChange={e=>{setLoading(true);setFrom(e.target.value);setPage(1);}}/></label>
    <label>Received through (IST)<input type="date" min={from||undefined} disabled={busy} value={to} onChange={e=>{setLoading(true);setTo(e.target.value);setPage(1);}}/></label>
    <div className={s.viewSwitcher} role="group" aria-label="View format">
      <button type="button" className={!listMode ? s.viewSwitcherActive : s.viewSwitcherBtn} onClick={() => setListMode(false)} aria-pressed={!listMode}><Grid size={13} aria-hidden="true" /><span>Board view</span></button>
      <button type="button" className={listMode ? s.viewSwitcherActive : s.viewSwitcherBtn} onClick={() => setListMode(true)} aria-pressed={listMode}><List size={13} aria-hidden="true" /><span>List view</span></button>
    </div>
    {admin&&<button type="button" onClick={()=>{manualRequest.current=null;setManual({client:'',title:''});setManualOriginal(JSON.stringify({client:'',title:''}));setManualEvents([]);}}><Plus size={13} style={{display:'inline',verticalAlign:'text-bottom',marginRight:4}} aria-hidden="true" /><span>Add manual order</span></button>}
  </form>
  <p className={s.status} role="status">{message}</p>
  <p>Page {page} · {orders.length} records{dueOnly?' · Follow-ups due today or earlier':''} · Stage counts cover this page only.</p>
  {listMode?<div className={s.tableWrap}><table><thead><tr><th>Record</th><th>Source</th><th>Stage</th><th>Assignee</th><th>Follow-up</th><th>Move to</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><button onClick={()=>void open(o.id)}>{o.client} · {o.title}</button><small>{o.reference||o.id.slice(0,8)}{o.createdAt?' · '+o.createdAt.slice(0,10):''}{o.referenceCount!==undefined?' · '+o.referenceCount+' references':''}</small></td><td>{o.source==='manual'?'Staff entered':o.requestKind==='bespoke'?'Custom request':'Product request'}</td><td>{stageLabel(o.status)}</td><td>{o.assigneeName||'Unassigned'}</td><td>{o.followUp?.slice(0,10)||'—'}</td><td><select aria-label={'Move '+o.client+' to stage'} disabled={busy||loading} value={o.status} onChange={e=>void move(o.id,e.target.value as OrderStage)}>{orderStages.map(v=><option key={v} value={v}>{stageLabel(v)}</option>)}</select></td></tr>)}</tbody></table></div>:<OrderKanban orders={visible} busy={busy||loading} onMove={(id,status)=>void move(id,status)} onOpen={id=>void open(id)}/>}<div className={s.actions}><button disabled={busy||loading||page===1} onClick={()=>setPage(p=>p-1)}>Previous page</button><button disabled={busy||loading||!truncated} onClick={()=>setPage(p=>p+1)}>Next page</button></div>{!orders.length&&<p className={s.empty}>New inquiries will appear here after a customer submits a product brief.</p>}
  <Dialog open={!!detail} title={detail?detail.inquiry.reference+' · '+detail.inquiry.name:'Inquiry'} onClose={()=>{if(document.querySelector('[data-studio-saving="true"]'))return;if(!document.querySelector('[data-unsaved="true"]')||window.confirm('Close this record and discard its unsaved edits?'))setDetail(null);}}>{detail&&<InquiryDetail key={detail.inquiry.id} initial={detail} staff={staff} admin={admin} onSaved={load}/>}</Dialog>
  <Dialog open={!!moveRequest} title="Explain this stage change" onClose={()=>{if(!busy&&(!moveReason||window.confirm('Discard the unsaved stage reason?'))){setMoveRequest(null);setMoveReason('');}}}><form data-unsaved={!!moveReason} onSubmit={e=>{e.preventDefault();if(moveRequest)void move(moveRequest.id,moveRequest.status,moveReason);}}><p>{moveRequest?'Move to '+stageLabel(moveRequest.status)+'. A reason is required for closing or moving work backward.':''}</p><label>Reason<textarea disabled={busy} value={moveReason} maxLength={500} required rows={3} onChange={e=>setMoveReason(e.target.value)}/></label><p role="status">{message}</p><div className={s.actions}><button type="button" disabled={busy} onClick={()=>{if(!moveReason||window.confirm('Discard the unsaved stage reason?')){setMoveRequest(null);setMoveReason('');}}}>Cancel</button><button disabled={busy||!moveReason.trim()}>Save stage change</button></div></form></Dialog>
  <Dialog open={!!manual} title={manual?.id?'Manual order':'Add a manual order'} onClose={()=>{if(!busy&&(!manualDirty||window.confirm('Discard unsaved manual-order edits?')))setManual(null);}}>{manual&&<form data-unsaved={manualDirty} onSubmit={e=>{e.preventDefault();void saveManual();}}><p>This record is entered by staff. It has no website inquiry or prepared WhatsApp message attached.</p><p role="status">{message}</p><label>Client name<input disabled={busy} value={manual.client||''} maxLength={120} required onChange={e=>setManual({...manual,client:e.target.value})}/></label><label>Brief<textarea disabled={busy} value={manual.title||''} maxLength={240} required onChange={e=>setManual({...manual,title:e.target.value})}/></label><div className={s.actions}><button disabled={busy}>Save manual order</button>{manual.id&&<button type="button" disabled={busy} onClick={()=>{if(!manualDirty||window.confirm("Discard edits and load the latest saved record?"))void open(manual.id!);}}>Reload saved record</button>}</div>{manualEvents.map((e,i)=><p key={i}>{formatBusinessTime(e.createdAt)} · {e.actor}: {e.from_status||'Created'} → {e.to_status}{e.reason?' · '+e.reason:''}</p>)}</form>}</Dialog>
  </>;
}
