'use client';
import {useEffect,useState} from 'react';
import type {ContentDocument} from '@/lib/content-model';
import {landingTypes,landingLimit,type LandingBlock,type LandingType} from '@/lib/landing-model';
import type {PublicMedia} from '@/lib/public-media';
import {studioFetch} from './workspace-api';
import {UsageFields,EditorialGalleryFields} from './editorial-record-fields';
import {EditorialBodyEditor} from './editorial-body-editor';
import s from './workspace.module.css';
type Choice={id:string;name:string;category?:string;kind?:string;route?:string};
type Options={products:Choice[];entries:Choice[];destinations:string[]};
const names:Record<LandingType,string>={hero:'Image opening',richText:'Reading column',productGrid:'Selected pieces',imageCta:'Image and invitation',faqPicker:'Selected answers',finalCta:'Closing invitation',collectionGrid:'Collections',portfolioGrid:'Portfolio stories',journalGrid:'Journal stories',testimonial:'Single statement',testimonialGrid:'Statements',videoHero:'Film opening',videoStory:'Film and story',masonryGallery:'Masonry gallery',bentoGallery:'Bento gallery',fullscreenGallery:'Fullscreen gallery'};
export function LandingEditor({document:d,media,onChange,initialBlock}:{initialBlock?:string;document:ContentDocument;media:PublicMedia[];onChange:(patch:Partial<ContentDocument>)=>void}){
 const blocks=d.landing!.blocks;
 const [selected,setSelected]=useState(initialBlock&&blocks.some(b=>b.id===initialBlock)?initialBlock:blocks[0]?.id),[type,setType]=useState<LandingType>('richText'),[options,setOptions]=useState<Options|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;void studioFetch('/api/studio/homepage-options').then(v=>{if(active){setOptions(v);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[attempt]);
 const b=blocks.find(v=>v.id===selected),index=blocks.findIndex(v=>v.id===selected);
 const write=(next:LandingBlock[])=>onChange({landing:{schemaVersion:1,blocks:next}});
 const patch=(value:Partial<LandingBlock>)=>write(blocks.map(v=>v.id===selected?{...v,...value}:v));
 const accepts=(v:Choice)=>!b?false:b.type==='collectionGrid'?['/collectible-design','/memory-art','/personal-art'].includes(v.route||''):b.type==='portfolioGrid'?v.kind==='portfolio':b.type==='journalGrid'?v.kind==='article':b.type==='faqPicker'?v.kind==='faq':['testimonial','testimonialGrid'].includes(b.type)?v.kind==='testimonial':false;
 const choices=b?.type==='productGrid'?options?.products||[]:(options?.entries||[]).filter(accepts);
 const list=b&&['productGrid','collectionGrid','portfolioGrid','journalGrid','faqPicker','testimonial','testimonialGrid'].includes(b.type);
 const add=()=>{const id='block-'+crypto.randomUUID().slice(0,8);write([...blocks,{id,type,enabled:false,heading:names[type],paragraphs:[]}]);setSelected(id);setNotice('New block added hidden. Complete its content and enable it when ready.');};
 return <section className={s.panel} aria-label="Landing page blocks"><h2>Build this page</h2><p>The page title above owns the main heading. Each block has its own content, references and independent image crops. Saving captures published dependencies for the exact preview.</p>{error&&<p role="alert">{error} <button type="button" onClick={()=>setAttempt(v=>v+1)}>Retry published choices</button></p>}<p role="status">{notice}</p><div className={s.sectionOutline} role="group" aria-label="Landing block outline">{blocks.map((v,i)=><button type="button" key={v.id} aria-pressed={v.id===selected} onClick={()=>setSelected(v.id)}>{i+1}. {v.heading}<small>{names[v.type]} · {v.enabled?'Visible':'Hidden'}</small></button>)}</div>
 {b&&<fieldset className={s.panel} id={'content-field-block-'+b.id} tabIndex={-1}><legend>{names[b.type]} · {b.id}</legend><label className={s.check}><input type="checkbox" checked={b.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Visible on this page</label><label>Block heading<input maxLength={150} required value={b.heading} onChange={e=>patch({heading:e.target.value})}/></label><label>Eyebrow<input maxLength={100} value={b.eyebrow||''} onChange={e=>patch({eyebrow:e.target.value||undefined})}/></label>{b.type==='richText'?<EditorialBodyEditor section={{id:b.id,heading:b.heading,paragraphs:b.paragraphs,body:b.body}} onChange={v=>patch({paragraphs:v.paragraphs||b.paragraphs,body:v.body})}/>:<label>Paragraphs — one per line<textarea rows={4} value={b.paragraphs.join('\n')} onChange={e=>patch({paragraphs:e.target.value?e.target.value.split('\n'):[]})}/></label>}
 {['hero','imageCta','videoHero','videoStory','finalCta'].includes(b.type)&&<><label>Button label<input maxLength={80} value={b.action?.label||''} onChange={e=>patch({action:e.target.value?{label:e.target.value,href:b.action?.href||'/commission'}:undefined})}/></label>{b.action&&<label>Button destination<input maxLength={240} list="landing-destinations" value={b.action.href} onChange={e=>patch({action:{...b.action!,href:e.target.value}})}/></label>}<datalist id="landing-destinations">{options?.destinations.map(path=><option key={path} value={path}/>)}</datalist></>}
 {b.type==='finalCta'&&<label className={s.check}><input type="checkbox" checked={!!b.whatsapp} onChange={e=>patch({whatsapp:e.target.checked})}/>Show Open WhatsApp using current business details; no message is sent</label>}
 {['hero','imageCta'].includes(b.type)&&<UsageFields label="Block image" usage={b.image} media={media} onChange={image=>patch({image})}/>}
 {['imageCta','videoStory'].includes(b.type)&&<label>Text placement<select value={b.side||'start'} onChange={e=>patch({side:e.target.value as LandingBlock['side']})}><option value="start">Text first</option><option value="end">Image or film first</option></select></label>}
 {['videoHero','videoStory'].includes(b.type)&&<><label>Verified film<select value={b.film||''} onChange={e=>patch({film:(e.target.value||undefined) as LandingBlock['film']})}><option value="">Choose a film</option><option value="resin-pour">Resin in motion · disclosed material visualization</option></select></label><p>The approved film includes its poster, WebM and MP4 sources. Playback waits for the visitor and includes a still-image fallback.</p></>}
 {['masonryGallery','bentoGallery','fullscreenGallery'].includes(b.type)&&<EditorialGalleryFields images={b.gallery||[]} media={media} limit={landingLimit(b.type)} onChange={gallery=>patch({gallery})}/>}
 {b.type==='testimonial'&&<label>Statement presentation<select value={b.variant||'editorial'} onChange={e=>patch({variant:e.target.value as LandingBlock['variant']})}><option value="editorial">Editorial column</option><option value="featured">Featured statement</option></select></label>}
 {list&&<fieldset className={s.panel}><legend>Published references</legend><label>Selection<select value={b.mode||'manual'} onChange={e=>patch({mode:e.target.value as LandingBlock['mode'],ids:undefined,category:undefined})}><option value="manual">Choose records in order</option>{['productGrid','testimonialGrid'].includes(b.type)&&<option value="featured">Explicit featured selection</option>}{['productGrid','journalGrid'].includes(b.type)&&<option value="category">By current category</option>}{['portfolioGrid','journalGrid','testimonialGrid'].includes(b.type)&&<option value="recent">Most recently published</option>}</select></label>{b.mode==='category'&&<label>Current category<select value={b.category||''} onChange={e=>patch({category:e.target.value})}><option value="">Choose…</option>{[...new Set(choices.map(v=>v.category).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select></label>}{['recent','category'].includes(b.mode||'')?<label>Maximum records<input type="number" min={1} max={landingLimit(b.type)} value={b.limit||landingLimit(b.type)} onChange={e=>patch({limit:Number(e.target.value)})}/></label>:<><ol className={s.selectionList}>{(b.ids||[]).map((id,i)=><li key={id}><span>{choices.find(v=>v.id===id)?.name||'Unavailable: '+id}</span><div className={s.actions}>{[-1,1].map(delta=><button type="button" key={delta} disabled={i+delta<0||i+delta>=b.ids!.length} onClick={()=>{const ids=[...b.ids!];[ids[i],ids[i+delta]]=[ids[i+delta],ids[i]];patch({ids});}}>Move reference {i+1} {delta===-1?'up':'down'}</button>)}<button type="button" onClick={()=>patch({ids:b.ids!.filter(v=>v!==id)})}>Remove reference {i+1}</button></div></li>)}</ol><label>Add published reference<select value="" disabled={!options||(b.ids?.length||0)>=landingLimit(b.type)} onChange={e=>{if(e.target.value)patch({ids:[...(b.ids||[]),e.target.value]});}}><option value="">Choose…</option>{choices.filter(v=>!b.ids?.includes(v.id)).map(v=><option key={v.id} value={v.id}>{v.name} · {v.id}</option>)}</select></label></>}<p>Unavailable or wrong-kind references block publication. Re-save and preview after any selected source changes.</p></fieldset>}
 <div className={s.actions}>{[-1,1].map(delta=><button type="button" key={delta} disabled={index+delta<0||index+delta>=blocks.length} onClick={()=>{const next=[...blocks];[next[index],next[index+delta]]=[next[index+delta],next[index]];write(next);setNotice('Block moved to position '+(index+delta+1)+'.');}}>Move block {delta===-1?'up':'down'}</button>)}<button type="button" disabled={blocks.length===1} onClick={()=>{const next=blocks.filter(v=>v.id!==b.id);write(next);setSelected(next[0].id);}}>Remove block</button></div></fieldset>}
 <div className={s.actions}><label>New block type<select value={type} onChange={e=>setType(e.target.value as LandingType)}>{landingTypes.map(t=><option key={t} value={t} disabled={(['hero','videoHero'].includes(t)&&blocks.some(b=>['hero','videoHero'].includes(b.type)))||(t==='finalCta'&&blocks.some(b=>b.type==='finalCta'))}>{names[t]}</option>)}</select></label><button type="button" disabled={blocks.length>=30||(['hero','videoHero'].includes(type)&&blocks.some(b=>['hero','videoHero'].includes(b.type)))||(type==='finalCta'&&blocks.some(b=>b.type==='finalCta'))} onClick={add}>Add block</button></div></section>;
}
