'use client';
import {useState} from 'react';
import {isDiscoveryRoute,detailedChapters,restoreDetailedChapters} from '@/lib/detailed-pages';
import type {ContentDocument,ContentSection} from '@/lib/content-model';
import {imprintContactId} from '@/lib/imprint-content';
import {sharedCopyId,sharedCopyFields,copyFieldId} from '@/lib/shared-copy-model';
import {EditorialBodyEditor} from './editorial-body-editor';
import {CropFields} from './homepage-editor';
import type {PublicMedia} from '@/lib/public-media';
import s from './workspace.module.css';
export function PageSectionsEditor({document:d,initialSection,onChange,media}:{document:ContentDocument;initialSection?:string;onChange:(patch:Partial<ContentDocument>)=>void;media:PublicMedia[]}){
 const [selected,setSelected]=useState(d.sections.some(s=>s.id===initialSection)?initialSection!:d.sections[0]?.id),[query,setQuery]=useState(''),[announcement,setAnnouncement]=useState('');
 const section=d.sections.find(s=>s.id===selected),index=d.sections.findIndex(s=>s.id===selected);
 const patch=(update:Partial<ContentSection>)=>onChange({sections:d.sections.map(s=>s.id===selected?{...s,...update}:s)});
 const move=(direction:number)=>{const next=[...d.sections],other=index+direction;[next[index],next[other]]=[next[other],next[index]];onChange({sections:next});setAnnouncement('Section moved to position '+(other+1)+'.');};
 if(d.id===sharedCopyId)return <><p>Shared labels have one owner here. Page paragraphs stay in their own page editor. Phone and email come from Business settings.</p><label>Find a shared label<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>{[...new Set(sharedCopyFields.map(f=>f.group))].map(group=><fieldset className={s.panel} key={group}><legend>{group}</legend>{sharedCopyFields.filter(f=>f.group===group&&(f.label+' '+f.group).toLowerCase().includes(query.toLowerCase())).map(f=>{const id=copyFieldId(f.id),b=d.sections.find(s=>s.id===id)!;return <label key={id}>{f.label}<input id={'content-field-section-'+id} maxLength={300} required value={b.paragraphs[0]} onChange={e=>onChange({sections:d.sections.map(s=>s.id===id?{...s,paragraphs:[e.target.value]}:s)})}/><small>{f.group} → {f.label}</small></label>;})}</fieldset>)}</>;
 const locked=d.id==='page:imprint'&&section?.id===imprintContactId;
 const browseRequired=isDiscoveryRoute(d.route)&&section?.id==='browse';
 return <>{detailedChapters[d.route]&&<div className={s.panel}><h3>Detailed page chapters</h3><p>Add missing editorial chapters as hidden drafts. Existing sections and facts stay in place. Review the text and image before enabling each chapter.</p><button type="button" disabled={detailedChapters[d.route].every(t=>d.sections.some(s=>s.id===t.id))} onClick={()=>{try{onChange({sections:restoreDetailedChapters(d).sections});setAnnouncement('Missing chapters added as hidden drafts. Review before enabling.');}catch(error){setAnnouncement(error instanceof Error?error.message:'Your draft was kept.');}}}>Add missing detailed chapters</button></div>}<div className={s.panel}><label>Find a section or question<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className={s.sectionOutline} role="group" aria-label="Page sections">{d.sections.filter(b=>(b.heading+' '+b.group+' '+b.id).toLowerCase().includes(query.toLowerCase())).map(b=><button type="button" key={b.id} aria-pressed={selected===b.id} onClick={()=>setSelected(b.id)}>{b.heading}<small>{b.group||b.stage||'Section'} · #{b.id} · {b.enabled===false?'Hidden':'Visible'}</small></button>)}</div><p role="status">{announcement}</p></div>
 {section&&<fieldset id={'content-field-section-'+section.id} tabIndex={-1} className={s.panel}><legend>{d.id==='page:faq'?'Question':'Section'} {index+1} · {section.id}</legend>{locked?<p>Telephone and email come from the published Business settings. This required section cannot be hidden or removed.</p>:<>
 <label>{d.id==='page:faq'?'Question':'Heading'}<input maxLength={150} required value={section.heading} onChange={e=>patch({heading:e.target.value})}/></label>
 <label className={s.check}><input type="checkbox" disabled={browseRequired} checked={section.enabled!==false} onChange={e=>patch({enabled:e.target.checked})}/>Visible on this page</label>{browseRequired&&<p>The browse section keeps this page connected to the published catalogue and cannot be hidden or removed.</p>}
 {d.id==='page:faq'&&<><label>Question group<input maxLength={80} value={section.group||''} onChange={e=>patch({group:e.target.value})}/></label><label>Canonical policy reference<input placeholder="/terms" value={section.policyHref||''} onChange={e=>patch({policyHref:e.target.value||undefined})}/></label><p className={s.help}>Compare this answer with the linked policy before publishing. Matching meaning requires editorial review.</p></>}
 {d.id==='page:process'&&<><label>Sequence<select value={section.stage||''} onChange={e=>patch({stage:(e.target.value||undefined) as ContentSection['stage']})}><option value="">Existing guidance — not assigned</option><option value="customer">Customer steps</option><option value="making">Making steps</option></select></label><p className={s.help}>Explain the action at this stage. Ordering steps does not change how requests or messages are sent.</p></>}
 {!['page:privacy','page:terms','page:shipping-delivery','page:returns-cancellations','page:imprint','page:accessibility'].includes(d.id)&&<label>Section composition<select value={section.layout||'prose'} onChange={e=>patch({layout:e.target.value as ContentSection['layout']})}><option value="prose">Reading column</option><option value="split">Image then text</option><option value="reverse">Text then image on desktop</option><option value="statement">Editorial statement</option></select></label>}
 <EditorialBodyEditor section={section} onChange={patch}/>
 <label>Checklist — one item per line<textarea rows={3} value={section.checklist?.join('\n')||''} onChange={e=>patch({checklist:e.target.value?e.target.value.split('\n'):undefined})}/></label>
 {d.id==='page:materials-care'&&<details className={s.panel}><summary>Structured material guidance</summary><p>Record only verified guidance for this material. Existing product facts are read-only.</p>{(['appearance','limitations','care','placement'] as const).map(key=><label key={key}>{key}<textarea maxLength={1000} value={section.material?.[key]||''} onChange={e=>patch({material:{appearance:'',limitations:'',care:'',placement:'',...section.material,[key]:e.target.value}})}/></label>)}</details>}
 <details className={s.panel}><summary>Section image and action</summary><label>Published editorial image<select value={section.image?.path||''} onChange={e=>{const m=media.find(m=>m.path===e.target.value);patch({image:m?{path:m.path,alt:m.alt,caption:m.caption,desktop:{x:m.focalX,y:m.focalY,ratio:'3/2'},mobile:{x:m.focalX,y:m.focalY,ratio:'4/5'}}:undefined});}}><option value="">Text only</option>{media.map(m=><option key={m.path} value={m.path}>{m.alt}</option>)}</select></label>{section.image&&<CropFields usage={section.image} onChange={image=>patch({image})}/>}<label>Action label<input value={section.action?.label||''} maxLength={80} onChange={e=>patch({action:e.target.value?{label:e.target.value,href:section.action?.href||'/contact'}:undefined})}/></label>{section.action&&<label>Action destination<input value={section.action.href} onChange={e=>patch({action:{...section.action!,href:e.target.value}})}/></label>}</details>
 <label>Factual source / review note (staff only)<textarea maxLength={500} value={section.sourceNote||''} onChange={e=>patch({sourceNote:e.target.value})}/></label><p className={s.help}>{section.sourceNote?'Source note recorded; publication remains a deliberate administrator action.':'Source review not recorded. Do not add unverified claims.'}</p>
 </>}<div className={s.actions}><button type="button" disabled={index===0} onClick={()=>move(-1)}>Move section up</button><button type="button" disabled={index===d.sections.length-1} onClick={()=>move(1)}>Move section down</button>{!locked&&!browseRequired&&<button type="button" disabled={d.sections.length===1} onClick={()=>{const sections=d.sections.filter(b=>b.id!==selected);const translations=structuredClone(d.translations||{});for(const t of Object.values(translations))if(t?.sections)delete t.sections[selected];onChange({sections,translations});setSelected(sections[0].id);}}>Remove section</button>}</div></fieldset>}
 <button type="button" disabled={d.sections.length>=20} onClick={()=>{const id='section-'+crypto.randomUUID().slice(0,8);onChange({sections:[...d.sections,{id,heading:'New section',paragraphs:[''],enabled:false}]});setSelected(id);setQuery('');}}>Add section</button></>;
}
