'use client';
import {useCallback,useEffect,useState} from 'react';
import {Dialog} from '@/components/shop/dialog';
import {studioFetch} from './workspace-api';
import s from './workspace.module.css';

export function ReferenceCleanup(){
 const [inventory,setInventory]=useState<{count:number;bytes:number;submitted:{count:number;bytes:number};intakeEnabled:boolean;dataMode:string}|null>(null);
 const [open,setOpen]=useState(false),[metadataOpen,setMetadataOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{setInventory(await studioFetch('/api/studio/cleanup'));}catch(e){setMessage(e instanceof Error?e.message:'Unable to count expired uploads.');}},[]);
 useEffect(()=>{let active=true;void studioFetch('/api/studio/cleanup').then(d=>{if(active)setInventory(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 async function remove(){setBusy(true);try{const result=await studioFetch('/api/studio/cleanup',{confirm:'delete-expired-unsubmitted'});setMessage(`${result.removed} expired uploads removed. ${result.failed} retained for retry.`);setOpen(false);await load();}catch(e){setMessage(e instanceof Error?e.message:'Cleanup did not finish. Please retry.');}finally{setBusy(false);}}
 async function clearMetadata(){setBusy(true);try{const result=await studioFetch('/api/studio/cleanup',{confirm:'delete-expired-access-metadata'});setMessage(`Removed ${result.removed.limits} expired rate limits, ${result.removed.sessions} expired staff sessions and ${result.removed.unsubmittedForms} empty expired forms.`);setMetadataOpen(false);}catch(e){setMessage(e instanceof Error?e.message:'Maintenance could not be confirmed. Refresh before retrying.');}finally{setBusy(false);}}
 return <section className={s.panel}><h2>Unsubmitted reference images</h2><p>Images left without a submitted inquiry expire after 24 hours. Saved inquiry references are excluded from this cleanup.</p><p>{inventory?`${inventory.count} expired uploads · ${(Number(inventory.bytes)/1048576).toFixed(1)} MB reserved`:'Loading expired upload count…'}</p>{inventory&&<><p>Retained with saved inquiries: {inventory.submitted.count} images · {(Number(inventory.submitted.bytes)/1048576).toFixed(1)} MB.</p><p>Saved reference images follow the approved 90-day retention policy after closure, subject to documented exceptions. This tool only removes unsubmitted uploads; use the privacy procedure for saved records.</p>{inventory.dataMode==='shared'&&<p>Shared storage: cleanup affects the reference store used by both environments.</p>}</>}<div className={s.actions}><button disabled={busy} onClick={()=>void load()}>Refresh count</button><button disabled={busy||!inventory?.count} onClick={()=>setOpen(true)}>Review cleanup</button></div><p role="status">{message}</p><Dialog open={open} title="Delete expired uploads?" onClose={()=>{if(!busy)setOpen(false);}}><p>This permanently removes up to 25 images that have no saved inquiry and are over 24 hours old. It frees their reserved storage. Images whose removal fails are retained for retry.</p><div className={s.actions}><button disabled={busy} onClick={()=>setOpen(false)}>Keep images</button><button disabled={busy} onClick={()=>void remove()}>{busy?'Removing…':'Delete expired uploads'}</button></div></Dialog><h2>Expired access records</h2><p>Remove expired staff sessions, rate-limit counters and empty unsubmitted forms in batches of up to 250 each. Active access and saved inquiries are retained.</p><button disabled={busy} onClick={()=>setMetadataOpen(true)}>Review access-record cleanup</button><Dialog open={metadataOpen} title="Remove expired access records?" onClose={()=>{if(!busy)setMetadataOpen(false);}}><p>Only expired records are eligible. This does not delete saved inquiries, their images or active rate limits.</p><div className={s.actions}><button disabled={busy} onClick={()=>setMetadataOpen(false)}>Cancel</button><button disabled={busy} onClick={()=>void clearMetadata()}>{busy?"Removing…":"Remove expired access records"}</button></div></Dialog></section>;
}
