'use client';
import {useEffect,useState} from 'react';
import type {LegacyRoute} from '@/lib/legacy-routes';
import {studioFetch} from './workspace-api';
import s from './workspace.module.css';
type Report={checkedAt:string;canonicalOrigin:string;indexing:boolean;routes:(LegacyRoute&{availability:string})[];categories:{name:string;count:number;collections:string[]}[];protectedPaths:string[]};
export function RouteReview(){
 const [report,setReport]=useState<Report|null>(null),[query,setQuery]=useState(''),[disposition,setDisposition]=useState('all'),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;void studioFetch('/api/studio/route-review').then(data=>{if(active)setReport(data);}).catch(()=>{if(active)setError('Published destinations could not be checked. Retry to see current evidence.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[]);
 async function recheck(){setBusy(true);setError('');try{setReport(await studioFetch('/api/studio/route-review'));}catch{setError('The recheck failed. Any previous results below are stale.');}finally{setBusy(false);}}
 const rows=report?.routes.filter(row=>(disposition==='all'||row.disposition===disposition)&&[row.source,row.destination,row.reason].join(' ').toLowerCase().includes(query.toLowerCase()))||[];
 return <><div className={s.heading}><div><h1>Old links and publication.</h1><p>Reviewed destinations and current published category counts.</p></div><button onClick={()=>void recheck()} disabled={busy}>{busy?'Checking…':'Recheck published sources'}</button></div>
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">Checking saved publication evidence…</p>}
 {report&&<><section className={s.panel}><h2>Search visibility</h2><p>Canonical website: <a href={report.canonicalOrigin}>{report.canonicalOrigin}</a></p><p>Indexing in this environment: <strong>{report.indexing?'Enabled':'Disabled'}</strong>.</p><p>Private and administrative paths remain excluded: {report.protectedPaths.join(', ')}.</p><p className={s.help}>Published-source check: {new Date(report.checkedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST{error?' · stale':''}. This checks saved publication sources, not a live HTTP response or a search engine listing. Deployment/indexing changes are managed separately.</p></section>
 <div className={s.toolbar}><label>Find an old destination<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Old path, new path or reason"/></label><label>Route disposition<select value={disposition} onChange={e=>setDisposition(e.target.value)}><option value="all">All decisions</option>{['redirect','existing','review','retired','private','planned'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><span role="status">{rows.length} route decisions</span></div>
 <div className={s.routeDecisions}>{rows.map(row=><article className={s.panel} key={row.source}><h2>{row.source}</h2><p><strong>{row.disposition}</strong> · {row.availability}</p><p>{row.reason}</p>{row.destination&&<p>Destination: {row.availability==='Available in published sources'?<a href={row.destination}>{row.destination}</a>:<span>{row.destination}</span>}</p>}<details><summary>Mapping evidence</summary><p>{row.evidence}</p></details></article>)}</div>{!rows.length&&<p className={s.empty}>No route decisions match. Clear the search or choose All decisions.</p>}
 <section className={s.panel}><h2>Current categories</h2><p>Counts use current published pieces. Category relationships and product records are unchanged.</p>{report.categories.length?<div className={s.routeDecisions}>{report.categories.map(category=><div key={category.name}><h3><a href={'/search?category='+encodeURIComponent(category.name)}>{category.name}</a></h3><p>{category.count} published pieces · {category.collections.join(' / ')}</p></div>)}</div>:<p>No eligible published pieces are available in this environment.</p>}</section>
 <p className={s.protectedNote}>Unverified product/article identities, language-prefixed links and genuine project stories remain explicit review work. These diagnostics do not import products, activate a legacy service or publish content.</p></>}
 </>;
}
