'use client';
import {useState} from 'react';
import {studioFetch,type StaffMember} from './workspace-api';
import s from './workspace.module.css';
const blank={id:'',login:'',name:'',role:'editor' as 'editor'|'admin',active:true,version:0,password:''};
export function StaffEditor({staff,onReload}:{staff:StaffMember[];onReload:()=>Promise<void>}){
 const [draft,setDraft]=useState(blank),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <><div className={s.heading}><div><h1>The people behind the pieces.</h1><p>Administrators publish and manage staff. Editors maintain catalogue drafts and handle inquiries.</p></div></div><p className={s.help}>The owner login remains controlled by secure hosting settings. Staff passwords are hashed, never displayed. Updating access signs out that staff member’s existing sessions.</p><div className={s.panel}><h2>Staff</h2>{staff.length?staff.map(person=><div key={person.id} className={s.member}><p>{person.name}<br/><small>{person.login} · {person.role} · {person.active?'Active':'Disabled'}</small></p><button onClick={()=>setDraft({...person,password:''})}>Edit access</button></div>):<p>No additional staff accounts yet.</p>}</div><form className={s.panel} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('Saving staff access…');try{await studioFetch('/api/studio/workspace',{action:'staff',...draft,id:draft.id||null});setDraft(blank);await onReload();setMessage('Staff access saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save.');}finally{setBusy(false);}}}><h2>{draft.id?'Edit staff access':'Add a staff member'}</h2><div className={s.grid}><label>Name<input required value={draft.name} maxLength={100} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Login ID<input required value={draft.login} minLength={3} maxLength={80} autoComplete="off" onChange={e=>setDraft({...draft,login:e.target.value})}/></label><label>Role<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value as 'editor'|'admin'})}><option value="editor">Editor</option><option value="admin">Administrator</option></select></label><label>{draft.id?'New password (leave blank to keep current)':'Password (at least 16 characters)'}<input type="password" autoComplete="new-password" minLength={16} maxLength={200} required={!draft.id} value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><label className={s.check}><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Account enabled</label></div><div className={s.actions}><button disabled={busy} className={s.primary}>Save staff access</button><button type="button" onClick={()=>setDraft(blank)}>Clear form</button></div><p role="status">{message}</p></form></>;
}
