'use client';
import {useSearchParams} from 'next/navigation';
import {useState} from 'react';
import type {ContentDocument} from '@/lib/content-model';
import {translationFields,translationRevision,translationStatus,reviewTranslationImport} from '@/lib/translation-review';
import s from './workspace.module.css';
export function TranslationEditor({document:d,onChange,version,dirty}:{document:ContentDocument;onChange:(document:ContentDocument)=>void;version:number;dirty:boolean}){
 const params=useSearchParams();
 const [locale,setLocale]=useState<'hi'|'gu'>(()=>params.get('translation')==='gu'?'gu':'hi'),[query,setQuery]=useState(''),[missingOnly,setMissingOnly]=useState(false),[input,setInput]=useState(''),[result,setResult]=useState<ReturnType<typeof reviewTranslationImport>|null>(null);
 const [checkedContext,setCheckedContext]=useState('');
 const t=d.translations?.[locale]||{},fields=translationFields(d),status=translationStatus(d,locale);
 const context=JSON.stringify([d.id,locale,fields,t.fields]);
 const change=(values:Record<string,string>,reviewedRevision?:string)=>onChange({...d,translations:{...d.translations,[locale]:{...t,fields:values,reviewedRevision}}});
 return <details className={s.panel}><summary>Translations and review</summary><p>Translate editorial text only. Product facts, identifiers, destinations, original images and contacts keep their source values. Missing, incomplete or stale translations display the English document; the language notice explains this fallback. Review covers the entire current document, including homepage actions and image descriptions.</p>
 <div className={s.toolbar}><label>Translation language<select value={locale} onChange={e=>{setLocale(e.target.value as 'hi'|'gu');setResult(null);}}><option value="hi">हिन्दी</option><option value="gu">ગુજરાતી</option></select></label><label>Find source text<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className={s.check}><input type="checkbox" checked={missingOnly} onChange={e=>setMissingOnly(e.target.checked)}/>Missing fields only</label></div>
 <p role="status">{status.state} · {status.total-status.missing} / {status.total} fields filled · Saved source revision {version}</p>
 {fields.filter(f=>(!missingOnly||!t.fields?.[f.path]?.trim())&&(f.path+' '+f.source).toLowerCase().includes(query.toLowerCase())).map(f=><label className={s.field} key={f.path}>{f.path}<small lang="en">English: {f.source}</small><textarea lang={locale} rows={2} maxLength={Math.min(6000,Math.max(500,f.source.length*4))} value={t.fields?.[f.path]||''} onChange={e=>change({...t.fields,[f.path]:e.target.value})}/></label>)}
 <div className={s.actions}><button type="button" disabled={status.missing>0||status.state==='reviewed'} onClick={()=>change(t.fields||{},translationRevision(d,t.fields||{}))}>Mark current translation reviewed</button>{version>0&&!dirty&&<a href={'/studio/preview/frame?record='+encodeURIComponent(d.id)+'&version='+version+'&locale='+locale} target="_blank" rel="noreferrer">Preview saved translation ↗</a>}</div><p>Review confirms that you checked meaning against the source. Save the draft, preview its exact revision, then use the existing publication controls. Review is invalidated when text changes. Saved history includes translations and review state.</p>
 <details><summary>Translation import · dry run and conflicts</summary><p>Paste JSON with documentId, locale and a fields object keyed by the source paths above. Maximum 64 KB. This operation does not accept catalogue, contact, routing or media fields. Existing translation text is compared before it enters this unsaved editor.</p><textarea aria-label="Translation JSON" rows={6} value={input} maxLength={65536} onChange={e=>{setInput(e.target.value);setResult(null);}}/><button type="button" onClick={()=>{try{setCheckedContext(context);setResult(reviewTranslationImport(d,locale,JSON.parse(input)));}catch{setResult({issues:['Invalid JSON. Correct the syntax and retry.'],fields:null});}}}>Check import</button>
 {result&&<section aria-label="Import review"><p role="status">{result.issues.length?result.issues.join(' '):'Dry run passed. Review changes below; nothing has been saved.'}</p>{result.fields&&<>{checkedContext!==context&&<p role="alert">The source or translation changed. Check the import again before applying it.</p>}<dl>{Object.entries(result.fields).map(([path,text])=><div key={path}><dt>{path}</dt><dd>Before: {t.fields?.[path]||'Missing'}</dd><dd>After: {text}</dd></div>)}</dl><button type="button" disabled={checkedContext!==context} onClick={()=>{if(checkedContext!==context)return;change({...t.fields,...result.fields});setResult(null);setInput('');}}>Apply checked text to unsaved draft</button></>}</section>}</details>
 </details>;
}
